/**
 * Class-feature classification shard: wave assignment "reachable6" — features
 * granted through some `RefData.classes[*].features` list (base or prestige),
 * so a `CLASS_FEATURE_CHANGE_PATCHES` entry can reach them. Owner-assigned
 * worklist; `index.ts` documents the shard convention.
 */

import type { ClassFeatureClassificationEntry } from "./types.js";

export const CLASS_FEATURE_CLASSIFICATION_REACHABLE_6: Readonly<
  Record<string, ClassFeatureClassificationEntry>
> = {
  "2Og23i3rRXu5QQlg": {
    id: "2Og23i3rRXu5QQlg",
    name: "Ki Pool",
    bucket: "subsystem",
    note: "the pool size already rides the generic resource-pool pipeline (deriveResourcePools), ki strike's DR-bypass tiers are modeled in dr-bypass.ts, and the per-point spends (extra flurry attack, +20ft speed, +4 dodge AC) are swift-action activations, not a baseline Change.",
  },
  oP2K87w7eqRJ9SBg: {
    id: "oP2K87w7eqRJ9SBg",
    name: "Ki Powers",
    bucket: "subsystem",
    note: "a choose-one-per-two-levels menu of a dozen ki-spend abilities gated by monastery choice, each activation-gated in its own right; no baseline number applies to every student of perfection.",
  },
  "2Az38ZPYwjYBKZd2": {
    id: "2Az38ZPYwjYBKZd2",
    name: "Rage (UC)",
    bucket: "situational",
    note: "already reaches the sheet through the generic grantsBuffs resolution (resources.ts's resolveGrantsBuffs), not this table: the vendored Rage (Unchained) buff (id ciAO4KwMonUzAGY0) carries the +2 melee attack/damage/Will and -2 AC changes and surfaces as a linked-buff toggle on the Rage pool row automatically. The 2-temp-HP-per-HD clause has no vendored Change or contextNote and stays unmodeled prose.",
  },
  YCT3N8TaDSPt1AQb: {
    id: "YCT3N8TaDSPt1AQb",
    name: "Founders' Favor",
    bucket: "subsystem",
    note: "a favor-point resource pool plus a menu of spend-gated sub-powers (one of which, Favor: Dotara's Shroud, is scoped to a source property this vocabulary can't express and is already a documented non-promotion in class-feature-effects.ts); no unconditional baseline number.",
  },
  pgixjJZ2e5K2zd2E: {
    id: "pgixjJZ2e5K2zd2E",
    name: "Chosen Ally",
    bucket: "situational",
    note: "a mutual trade (self takes -1 AC, a chosen ally adjacent to the Ulfen Guard gains +1 dodge AC/Reflex) gated on both raging and adjacency to a specific ally; not an unconditional self bonus.",
  },
  r3qzzfr6CETVEm0w: {
    id: "r3qzzfr6CETVEm0w",
    name: "Inexorable Cold",
    bucket: "blocked",
    note: "clCheck.sr and clCheck.dispel could carry the counterspell/dispel/SR-check bonus, but it (and the flat +1 caster level, and the +1 to the DC of dispelling these spells) is scoped to cold-descriptor spells only; no target carries a descriptor axis, and the dispel-DC-of-your-own-spells bonus has no target at all.",
  },
  vTE94sQboMmdAakT: {
    id: "vTE94sQboMmdAakT",
    name: "Vigilante Specialization",
    bucket: "subsystem",
    note: "structural, not Change-shaped: avenger's full-BAB-as-vigilante-level replaces the base attack progression outright, and stalker's hidden strike is scaling extra damage dice, matching this engine's existing documented posture (archetype-extracted/vigilante.ts) that this feature has no Change-shaped number.",
  },
  DbC7QZBYYIClw1m6: {
    id: "DbC7QZBYYIClw1m6",
    name: "Smite Good",
    bucket: "subsystem",
    note: "already modeled by the hand-authored smite resource mechanism in resources.ts (tag smiteGood, mirroring paladin Smite Evil) rather than a Change; that pipeline, not this table, is the correct route.",
  },
  BBRnJFFsFaVL6eqO: {
    id: "BBRnJFFsFaVL6eqO",
    name: "Eye for Detail",
    bucket: "situational",
    note: "a +8 Linguistics bonus scoped to a single action (forging a government document specifically), not to Linguistics checks generally; applying it unconditionally would over-apply to every other Linguistics use.",
  },
  Fjsv2wNC223ofCE8: {
    id: "Fjsv2wNC223ofCE8",
    name: "Expanded Element",
    bucket: "subsystem",
    note: "grants a chosen element's wild talents (a player pick from a list), with the level-14 self-element mastery variant granting attack/damage/CL/DC bonuses that are themselves conditioned on which element was chosen twice; no unconditional baseline number.",
  },
  G1z392b58wRybqjL: {
    id: "G1z392b58wRybqjL",
    name: "Improved Spell Combat",
    bucket: "situational",
    note: "a +2 concentration bonus that applies only while using the spell combat ability, which this engine does not track as a live toggle (spell combat is prose-only per archetype-extracted/magus.ts); an unconditional Change would apply the bonus to every concentration check instead of only those made during spell combat.",
  },
  MJShF8DIaDehk8VN: {
    id: "MJShF8DIaDehk8VN",
    name: "Mystic Tattoo",
    bucket: "subsystem",
    note: "a choose-one-per-two-levels menu of eight tattoos, each its own activation-gated or resource-spend ability; no baseline number shared by every tattooed mystic.",
  },
  QyW6ly6dN84Ev6AY: {
    id: "QyW6ly6dN84Ev6AY",
    name: "Banner (SAM)",
    bucket: "blocked",
    note: "an ally-only aura (bonuses to allies within 60 feet, none to the samurai himself); this sheet only models the character's own stats, and class-feature-effects.ts already documents cavalier/samurai Banner as a deliberate non-promotion for the same reason.",
  },
  U2YBSx1s8cT8iDq1: {
    id: "U2YBSx1s8cT8iDq1",
    name: "Favored Terrain",
    bucket: "subsystem",
    note: "already modeled by the dedicated ranger.ts / DerivedRanger pipeline (a live terrain selection, not an unconditional bonus per ranger.ts's own doc comment); not this table's route.",
  },
  cUagLrkUg75Lzq0T: {
    id: "cUagLrkUg75Lzq0T",
    name: "Aura of Calm",
    bucket: "blocked",
    note: "an ally-facing aura granting a size-category increase for wind-effect purposes (no Change target models pseudo-size for a specific effect category) plus a save bonus scoped to the air/water descriptors, an elemental-descriptor axis this vocabulary doesn't carry.",
  },
  kg2aBHv1n6Exxkb0: {
    id: "kg2aBHv1n6Exxkb0",
    name: "Sculpt Ice and Snow",
    bucket: "subsystem",
    note: "grants a stone-shape/fabricate-style utility spell-like ability usable a limited number of times per day; spell-equivalent, not the actual spell (works ice/snow only, adds its own hardness/melt rules), so left unwired.",
  },
  mpe3JHJMINddqLWr: {
    id: "mpe3JHJMINddqLWr",
    name: "Arcane Pool",
    bucket: "subsystem",
    note: "the pool size already derives generically via deriveResourcePools's uses.maxFormula path (same mechanism as the Extra Arcane Pool feat, per feat-classification.ts); the spend is surfaced as a toggle on the pool row rather than a baseline Change.",
  },
  pqu1Mvo46iRpVH3I: {
    id: "pqu1Mvo46iRpVH3I",
    name: "Banner",
    bucket: "blocked",
    note: "ally-only aura, no bonus to the cavalier himself; class-feature-effects.ts documents cavalier Banner as a deliberate non-promotion for exactly this reason.",
  },
  xGwfO0LGSpeBvcIp: {
    id: "xGwfO0LGSpeBvcIp",
    name: "Eye of the Storm",
    bucket: "blocked",
    note: "a save/AC bonus scoped to spells and effects with the air or water descriptor; class-feature-effects.ts already documents this exact feature as a deliberate non-promotion for lacking an elemental-descriptor axis.",
  },
  "1Yy6Fn3UD82uviFg": {
    id: "1Yy6Fn3UD82uviFg",
    name: "Greater Banner",
    bucket: "blocked",
    note: "ally-only save bonus and an activated extra-save grant, both scoped to allies rather than the cavalier; class-feature-effects.ts documents Greater Banner as a deliberate non-promotion alongside base Banner.",
  },
  "8iEcTEpCKgs5adln": {
    id: "8iEcTEpCKgs5adln",
    name: "Study Technology",
    bucket: "situational",
    note: "a move-action-activated study ability whose bonus applies only against the specific subject studied, for a limited number of rounds; not an unconditional number.",
  },
  A4uLypmBnc0eO1fh: {
    id: "A4uLypmBnc0eO1fh",
    name: "Grasping Darkness",
    bucket: "situational",
    note: "an extra daily use of an activated ability plus a conditional grapple-CMB substitution and a lighting-conditioned bonus; every clause is activation- or state-gated.",
  },
  FXSiQ0ppo3K6Xsrg: {
    id: "FXSiQ0ppo3K6Xsrg",
    name: "Spirit Bonus",
    bucket: "subsystem",
    note: "already fully modeled by the dedicated medium-spirits.ts pipeline (live daily spirit choice via live.mediumSpirit, mediumSpiritBonus formula, per-spirit Change targets); not this table's route.",
  },
  Fb7VxWMSOZRN71K8: {
    id: "Fb7VxWMSOZRN71K8",
    name: "Favor: Crucisal's Guidance",
    bucket: "situational",
    note: "a swift-action favor-point spend, active for 1 minute and only 'in an urban environment'; not an unconditional bonus. Also not reachable as a pool toggle: its Founders' Favor pool carries no vendored uses.maxFormula at all (unlike Judgment/Bardic Performance/Sacred Weapon) — resources.ts hand-resolves the pool's size (class level plus the highest of Int/Wis/Cha modifier) so a row derives, but this power itself still has no linked buff or tableOptions entry for a toggle to attach to.",
  },
  JKJoHy5NveXGaZqv: {
    id: "JKJoHy5NveXGaZqv",
    name: "Flurry of Blows",
    bucket: "subsystem",
    note: "grants extra attacks within a full-attack action at a lowered effective base attack bonus; a structural change to the attack routine, not a Change-shaped number.",
  },
  K6E9dkSHjpWLGqKk: {
    id: "K6E9dkSHjpWLGqKk",
    name: "Sivanah's Veils",
    bucket: "subsystem",
    note: "a veil-pool spend that grants a disguise-self-style transformation plus one of several race-specific bonus abilities depending on which veil is chosen; no unconditional baseline number.",
  },
  LYWqXODjRJjVJeQ1: {
    id: "LYWqXODjRJjVJeQ1",
    name: "Fiendish Boon",
    bucket: "subsystem",
    note: "a paladin-Divine-Bond-style dual choice (weapon-bond enhancement or a summoned servant), both resource-spend and player-choice gated; no baseline Change, same posture this engine already gives Divine Bond.",
  },
  LkbGAZaa2KDrnS89: {
    id: "LkbGAZaa2KDrnS89",
    name: "Aura of Depravity",
    bucket: "situational",
    note: "bundles a self DR value with an aura that imposes a save penalty on nearby enemies; class-feature-effects.ts already declines to promote antipaladin auras of this shape (Aura of Cowardice, Aura of Depravity) since the enemy-facing half isn't a bonus to the antipaladin.",
  },
  NOhmhKgboJ9qdGvg: {
    id: "NOhmhKgboJ9qdGvg",
    name: "Elemental Overflow",
    bucket: "situational",
    note: "already reaches the sheet through a dedicated live route, not this table: kinetic-blast.ts calls tables.ts's kineticOverflowBonus with the kineticist's current live burn total on every recompute, and the resulting attack/damage bonus is applied directly to the kinetic-blast line. An unconditional Change would be wrong here (the bonus tracks burn turn to turn), which is exactly why the dedicated route exists instead. The 6th/11th/16th-level ability-score-boost/crit-negation upgrades remain display-only (tables.ts's kineticOverflowLabel sibling, never applied).",
  },
  RzEzudurxQFirFoF: {
    id: "RzEzudurxQFirFoF",
    name: "Weapon Training",
    bucket: "subsystem",
    note: "already modeled by the dedicated weapon-groups.ts pipeline (per-group selection and stacking, per that file's own header), not a name-keyed Change; that is the correct route for this feature.",
  },
  WJEF9WHs27kaFYJL: {
    id: "WJEF9WHs27kaFYJL",
    name: "High Jump",
    bucket: "blocked",
    note: "the unconditional half of this feature adds monk level only to Acrobatics checks made to jump; this engine's skill targets have no sub-scope narrower than the whole Acrobatics skill, so a Change would incorrectly also boost balance/tumble/fly checks.",
  },
  XAMIufM24q2qAB7o: {
    id: "XAMIufM24q2qAB7o",
    name: "True Magus",
    bucket: "situational",
    note: "every clause applies only while using spell combat against the same target as the magus's melee attacks; spell combat isn't tracked as a live state in this engine (archetype-extracted/magus.ts), so none of this is expressible unconditionally.",
  },
  f2Xg4pkJelnVyTCH: {
    id: "f2Xg4pkJelnVyTCH",
    name: "Greater Banner (SAM)",
    bucket: "blocked",
    note: "ally-only save bonus and an activated extra-save grant for allies, not the samurai; mirrors class-feature-effects.ts's documented Greater Banner non-promotion.",
  },
  njhC71bB9E3EK9N1: {
    id: "njhC71bB9E3EK9N1",
    name: "Oceanic Spirit",
    bucket: "numeric",
    note: "an unconditional class-level bonus on Fly and Swim checks plus level-tiered electricity/sonic resistance, all reachable via a CLASS_FEATURE_CHANGE_PATCHES entry keyed on class level; see proposals-reachable6.json.",
  },
  p1jQ4nCjqaCWJ2AO: {
    id: "p1jQ4nCjqaCWJ2AO",
    name: "Tattoo: Binding Trine",
    bucket: "subsystem",
    note: "one of several selectable tattoos (see Mystic Tattoo), itself a Spellcraft-check-gated, spell-slot-spend ability that transforms a failed save into a suppressed effect; no baseline number.",
  },
  vKapZzmkqXs62B2A: {
    id: "vKapZzmkqXs62B2A",
    name: "AC Bonus",
    bucket: "numeric",
    note: "Dodge AC and CMD bonus while wearing light or no armor and carrying no more than a light load (+1 at 1st, +2 at 5th, +3 at 9th), wired via the per-class 'studentOfPerfection:AC Bonus' key using the @armor.type/@attributes.encumbrance.level gate, which keeps this bearer's formula separate from Stalwart Defender's differently-scoped, unconditional 'AC Bonus' sharing the bare name. The immobilized/helpless clause is live condition state this collection path can't read and is dropped.",
  },
  NvdCjOAQyVCqb7Tl: {
    id: "NvdCjOAQyVCqb7Tl",
    name: "Unnerving Gaze",
    bucket: "situational",
    note: "a swift-action-activated gaze attack usable a limited number of rounds per day; the shaken/staggered effect is also a status imposition this engine doesn't model as a Change.",
  },
  O8OAFDU1c7tK9NsQ: {
    id: "O8OAFDU1c7tK9NsQ",
    name: "Storm Shape",
    bucket: "subsystem",
    note: "a standard-action-activated whirlwind polymorph usable a limited number of minutes per day; a form change, not a baseline stat bonus.",
  },
  "1jWdphZfvOQLR2cN": {
    id: "1jWdphZfvOQLR2cN",
    name: "Tenebrous Magic",
    bucket: "subsystem",
    note: "grants a bonus feat plus a metamagic-application rule and, for darkness/shadow-descriptor or shadow-subschool spells, +2 caster level, +2 to those spells' save DCs, and a bigger penalty on dispel checks made against them in darkness; the bonus feat isn't this table's route, spellDC has no descriptor/subschool axis to match the scope, and neither the CL bump nor the dispel-DC-of-your-own-spells bonus has a target at all.",
  },
  "2YA3Ken4K90rB0EE": {
    id: "2YA3Ken4K90rB0EE",
    name: "Aura of Evil",
    bucket: "subsystem",
    note: "sets the strength of the antipaladin's own detect-evil aura as read by OTHER creatures, and grants a paladin's smite-evil extra damage against the antipaladin; neither is a Change to the antipaladin's own sheet.",
  },
  "5GZUKheeuViri7GV": {
    id: "5GZUKheeuViri7GV",
    name: "Guarded Thoughts",
    bucket: "subsystem",
    note: "grants a conditional extra saving throw with a circumstance bonus, only against charm/compulsion effects that would make the guard attack her chosen ally; a re-roll mechanic has no Change-shaped target, matching this engine's existing treatment of similar re-roll abilities.",
  },
  "7rz2y33UeER5Hnev": {
    id: "7rz2y33UeER5Hnev",
    name: "Tattoo: Rune of Fangs",
    bucket: "situational",
    note: "the bonus applies only while polymorphed or otherwise transformed into a form with natural attacks, and only to one chosen natural attack; state-gated, not unconditional.",
  },
  DsJyjV9Oj57MXU9j: {
    id: "DsJyjV9Oj57MXU9j",
    name: "Freeze and Thaw",
    bucket: "subsystem",
    note: "a standard-action-activated freeze/melt utility ability usable a limited number of times per day; not a stat bonus.",
  },
  EYejyvbnCJKiWeel: {
    id: "EYejyvbnCJKiWeel",
    name: "Veil Pool",
    bucket: "subsystem",
    note: "the prose describes a class-level-plus-ability-modifier pool that funds a disguise-self-style transformation with level-gated sensory upgrades, but the vendored feature carries no uses field at all (unlike Ki Pool/Arcane Pool), so deriveResourcePools never derives a Veil Pool row for a toggle to attach to. Unlike Founders' Favor's formula, the ability score is a locked-in 1st-level player pick ('the character makes this choice at 1st level, after which it cannot be changed'), not an automatic highest-of-three — this table has no stored field for that pick, so the formula can't be hand-resolved either.",
  },
  EpDI0Qi5SDRmL4lK: {
    id: "EpDI0Qi5SDRmL4lK",
    name: "Mount (SAM)",
    bucket: "subsystem",
    note: "grants an animal companion (a whole separate creature with its own stat block), not a Change to the samurai's own sheet.",
  },
  GZ4ZGhHPS4sR8f63: {
    id: "GZ4ZGhHPS4sR8f63",
    name: "Ki Pool",
    bucket: "subsystem",
    note: "stacks the student of perfection's levels into an existing (or new) ki pool that rides the generic resource-pool pipeline; same posture as base monk Ki Pool above, no baseline Change of its own.",
  },
  IA4Z4xwEeubcDqF4: {
    id: "IA4Z4xwEeubcDqF4",
    name: "Mounted Archer",
    bucket: "situational",
    note: "reduces an existing mounted-ranged-attack penalty, but only while the mount is making a double move or running; an unconditional Change would apply the reduction even when standing still.",
  },
  LHPUMNPUGGmak5mV: {
    id: "LHPUMNPUGGmak5mV",
    name: "Favor: Dotara's Shroud",
    bucket: "blocked",
    note: "every bonus is scoped to checks/attacks/saves involving city guards specifically, a source-property scope class-feature-effects.ts already documents as a deliberate non-promotion (grouped with Founders' Favor) for having no vocabulary axis.",
  },
  N4WwxQrSEbDrZuha: {
    id: "N4WwxQrSEbDrZuha",
    name: "Favor: Eye of Vadrus",
    bucket: "situational",
    note: "a full-round-action favor-point spend granting a temporary Disable Device bonus or limited-duration wall transparency; not unconditional.",
  },
  N7m9fQTtzgZAWUdb: {
    id: "N7m9fQTtzgZAWUdb",
    name: "Umbral Courtier",
    bucket: "numeric",
    note: "an unconditional competence bonus equal to class level on Bluff, Diplomacy, and Knowledge (nobility), reachable via a CLASS_FEATURE_CHANGE_PATCHES entry (skill.blf/skill.dip/skill.kno); see proposals-reachable6.json.",
  },
  NKUVAqFlA93zmC4E: {
    id: "NKUVAqFlA93zmC4E",
    name: "Guard Dedications",
    bucket: "subsystem",
    note: "a choose-one-per-two-levels menu of nine dedications (bonus feats, rage powers, uncanny dodge, a Diplomacy bonus, etc.); no baseline number shared by every Ulfen Guard.",
  },
  P0EhxFOJJXWMBiZi: {
    id: "P0EhxFOJJXWMBiZi",
    name: "Spellbooks (MAG)",
    bucket: "subsystem",
    note: "governs which spells a magus may prepare (spellbook rules), not a stat or check bonus.",
  },
  P2XyBCDEUGOFwRAF: {
    id: "P2XyBCDEUGOFwRAF",
    name: "Mount",
    bucket: "subsystem",
    note: "grants an animal companion (a whole separate creature with its own stat block), not a Change to the cavalier's own sheet.",
  },
  QGv2YjclwgkruFE6: {
    id: "QGv2YjclwgkruFE6",
    name: "Cavalier's Charge",
    bucket: "situational",
    note: "the attack bonus and AC-penalty waiver both apply only to a mounted charge attack; not an unconditional bonus.",
  },
  QsZDnb8CN80wU6LD: {
    id: "QsZDnb8CN80wU6LD",
    name: "Ki Power: Master of Riddles (Sp, Unblinking Flame)",
    bucket: "subsystem",
    note: "one of the Ki Powers menu's monastery-restricted options (see Ki Powers above); the class-skill grant and the ki-spend suggestion effect are both a chosen ability, not a baseline number.",
  },
  TMpfSlpC7To6uXGE: {
    id: "TMpfSlpC7To6uXGE",
    name: "Seamless Guise",
    bucket: "situational",
    note: "the +20 Disguise bonus applies only when someone actually suspects the vigilante's dual identity and he attempts the specific check to reinforce it; not an unconditional bonus to every Disguise check.",
  },
  TWitZQ75kcIwm5uT: {
    id: "TWitZQ75kcIwm5uT",
    name: "Shared Infusion",
    bucket: "subsystem",
    note: "changes how many creatures an infusion extract can affect, not a stat bonus.",
  },
  VBUnbageuuu32UYK: {
    id: "VBUnbageuuu32UYK",
    name: "Fickle Winds",
    bucket: "situational",
    note: "a swift-action-activated fickle winds effect usable a limited number of rounds per day; activation- and resource-gated.",
  },
  XJtvco1XWggmr5LU: {
    id: "XJtvco1XWggmr5LU",
    name: "Abundant Step",
    bucket: "subsystem",
    note: "grants a dimension door spell-like ability paid for with ki points; pool-spend cast, rides the ki pool, so left unwired rather than minting a synthetic counter that misstates the cost.",
  },
  XmALhWqXdN9yOmtd: {
    id: "XmALhWqXdN9yOmtd",
    name: "Favored Enemy",
    bucket: "subsystem",
    note: "already modeled by the dedicated ranger.ts / DerivedRanger pipeline (a live favored-enemy selection), same posture as Favored Terrain above; not this table's route.",
  },
  aabyB4FV9OH7hcYZ: {
    id: "aabyB4FV9OH7hcYZ",
    name: "Touch of Corruption",
    bucket: "subsystem",
    note: "already modeled by the hand-authored touch-of-corruption resource mechanism in resources.ts (mirroring paladin Lay on Hands), not a Change; that pipeline, not this table, is the correct route.",
  },
  dhBZs1g1QQNQM3vm: {
    id: "dhBZs1g1QQNQM3vm",
    name: "Aura of Cowardice",
    bucket: "situational",
    note: "imposes a save penalty on enemies within range rather than a bonus to the antipaladin; class-feature-effects.ts already documents this exact feature as a deliberate non-promotion for that reason.",
  },
  knfcYfPniQcT4u3F: {
    id: "knfcYfPniQcT4u3F",
    name: "Wave Breaker",
    bucket: "numeric",
    note: "the swim speed grant (twice base land speed) is wired via CLASS_FEATURE_CHANGE_PATCHES; the water-breathing per-day-per-level half stays unmodeled prose.",
  },
  n4SWyKVcdmZK4t7d: {
    id: "n4SWyKVcdmZK4t7d",
    name: "Quivering Palm",
    bucket: "subsystem",
    note: "a once-per-day death-attack special ability; its save DC is a real sheet line via ability-dcs.ts's quiveringPalm family (computed independently of this catalog), but the death-or-negate outcome itself is not a stat bonus this catalog's Change patches can express.",
  },
  nNCWIq0FyYUpBuZG: {
    id: "nNCWIq0FyYUpBuZG",
    name: "Dedication: Curiosity",
    bucket: "subsystem",
    note: "one of several Guard Dedications a player may or may not select (see Guard Dedications above); no build-choice tracking exists for which dedication was chosen, so an unconditional Change would apply the Diplomacy bonus to every Ulfen Guard regardless of pick.",
  },
  o4FeJzhEdocIO4mY: {
    id: "o4FeJzhEdocIO4mY",
    name: "Vigilante Talent",
    bucket: "subsystem",
    note: "a choose-one-per-two-levels menu of vigilante talents (see vigilante-talents.ts's own dedicated catalog); no baseline number shared by every vigilante.",
  },
  qCl2cw0leReIXuRn: {
    id: "qCl2cw0leReIXuRn",
    name: "Startling Appearance",
    bucket: "situational",
    note: "imposes flat-footed and an attack penalty on a foe unaware of the vigilante, not a bonus to the vigilante himself, and only on the vigilante's turn against that specific foe; enemy- and action-scoped.",
  },
  wNCdfdUHynq6gigh: {
    id: "wNCdfdUHynq6gigh",
    name: "Taboo",
    bucket: "subsystem",
    note: "already covered by the dedicated medium-spirits.ts pipeline (spirit surge / influence mechanics); not this table's route.",
  },
};
