/**
 * Class-feature classification shard: wave assignment "reachable2" — features
 * granted through some `RefData.classes[*].features` list (base or prestige),
 * so a `CLASS_FEATURE_CHANGE_PATCHES` entry can reach them. Owner-assigned
 * worklist; `index.ts` documents the shard convention.
 */

import type { ClassFeatureClassificationEntry } from "./types.js";

export const CLASS_FEATURE_CLASSIFICATION_REACHABLE_2: Readonly<
  Record<string, ClassFeatureClassificationEntry>
> = {
  V4rFQp52p7nzcijL: {
    id: "V4rFQp52p7nzcijL",
    name: "Ki Pool (NIN)",
    bucket: "subsystem",
    note: "Grants a resource pool spent on swift-action abilities (extra attack, speed boost, Stealth bonus); the pool and its Acrobatics-jump perk are subsystem grants, not an unconditional number.",
  },
  qz3sBtaFF0ykzxFG: {
    id: "qz3sBtaFF0ykzxFG",
    name: "Adrenaline Deed",
    bucket: "subsystem",
    note: "Meta-feature: choose one deed from a list, only active while adrenaline rush is running. Each individual deed appears as its own worklist entry.",
  },
  GLOiOEA87imlBmxT: {
    id: "GLOiOEA87imlBmxT",
    name: "Cypher Lore",
    bucket: "subsystem",
    note: "Meta-feature: choose one cypher lore per level from a list of scroll/writing tricks. Each named lore appears as its own worklist entry.",
  },
  MUBqCaR3D1IXfnwx: {
    id: "MUBqCaR3D1IXfnwx",
    name: "Energumen",
    bucket: "situational",
    note: "Once-per-day activation with a rounds-long possession duration and a confusion aftermath; matches the class-feature-effects.ts precedent for activation/resource-gated non-promotions (named there explicitly).",
  },
  "5op6M5xchCJNsYRt": {
    id: "5op6M5xchCJNsYRt",
    name: "Bloodrage",
    bucket: "situational",
    note: "Core rage-state activation: a rounds/day resource, an AC penalty, and post-rage fatigue, all only present while bloodraging. Textbook 'while raging'-style state.",
  },
  CPz8QrQRSTdYF8IU: {
    id: "CPz8QrQRSTdYF8IU",
    name: "Spiritual Form",
    bucket: "situational",
    note: "Standard-action transformation with a minutes/day budget; the ability-score bonus and physical transformation only apply while the form is active.",
  },
  ESmEnSFVwQBCV6e7: {
    id: "ESmEnSFVwQBCV6e7",
    name: "Aspect of Divinity",
    bucket: "numeric",
    note: "The Disguise penalty is an unconditional, always-on -4 once gained at 7th level. The accompanying protection-from-alignment effect is a subsystem grant with no expressible number, so only the penalty is proposed for wiring.",
  },
  "1HQUUhQhowqKfmCA": {
    id: "1HQUUhQhowqKfmCA",
    name: "Inspired Rage",
    bucket: "situational",
    note: "Bardic-performance-style activation buffing allies while sustained; the Strength/Constitution/Will bonuses and AC penalty only exist during the performance.",
  },
  K0modP8yUhhYONJh: {
    id: "K0modP8yUhhYONJh",
    name: "Trapster",
    bucket: "blocked",
    note: "Real numbers, but every bonus is scoped to 'poisoned traps' specifically, narrower than any Perception/Craft/Disable Device target the engine carries. Wiring it generically would over-apply to non-poison traps.",
  },
  sYpUn32u8UCvhGAb: {
    id: "sYpUn32u8UCvhGAb",
    name: "Adrenaline Rush",
    bucket: "situational",
    note: "Rounds/day activation; the skill/ability-check bonus and end-of-rush fatigue only apply while active.",
  },
  YbufiQZokxwani8Q: {
    id: "YbufiQZokxwani8Q",
    name: "Alien Mind",
    bucket: "situational",
    note: "Rounds/day activation granting a mental-ability and mind-effect save bonus; matches the class-feature-effects.ts precedent for activation/resource-gated non-promotions (named there explicitly).",
  },
  eCz4wuetgyn1PllQ: {
    id: "eCz4wuetgyn1PllQ",
    name: "Harmonious Strike",
    bucket: "situational",
    note: "Panache-point activation on a successful attack against a flourished target, with a further choice of sub-effect. None of the numbers are unconditional.",
  },
  kXysARGzQKiAYmhR: {
    id: "kXysARGzQKiAYmhR",
    name: "Demonic Form",
    bucket: "situational",
    note: "Standard-action transformation with a minutes/day budget, like Spiritual Form; the resistances and natural attack only apply while transformed.",
  },
  "00Hl38rPsiXyEVrh": {
    id: "00Hl38rPsiXyEVrh",
    name: "Valiant Stand",
    bucket: "situational",
    note: "The sacred bonus only applies while adjacent to more than one enemy and no ally, an enemy-state condition the static sheet can't detect.",
  },
  "1aCmkiPPk6Thn2Cb": {
    id: "1aCmkiPPk6Thn2Cb",
    name: "Infernal Charisma",
    bucket: "situational",
    note: "The Charisma-check bonus is scoped to interactions with devils specifically, an enemy-type condition outside any general skill target.",
  },
  "5pOxkF0no21CGJ07": {
    id: "5pOxkF0no21CGJ07",
    name: "Solar Invocation",
    bucket: "situational",
    note: "Rounds/day activation (later usable as a move or swift action) with an outdoor-lighting precondition; the attack/damage/DC bonus only applies while invoked.",
  },
  AADeI9AH0yvh6cwW: {
    id: "AADeI9AH0yvh6cwW",
    name: "Enchanting Touch",
    bucket: "subsystem",
    note: "Spell-delivery mechanic that imposes a penalty on the touched target's observers, not a bonus to the courtesan's own stats.",
  },
  AsX63pTWDTd9RjSr: {
    id: "AsX63pTWDTd9RjSr",
    name: "Covert Spells",
    bucket: "subsystem",
    note: "Bluff/Sleight of Hand opposed-check mechanic for hiding spellcasting; its only numeric bonus is conditional on having a second, similar ability.",
  },
  BHRh4Kz6G9j5lvhN: {
    id: "BHRh4Kz6G9j5lvhN",
    name: "Toxic Trick",
    bucket: "subsystem",
    note: "Choose-a-trick-per-level resource of extraordinary/spell-like abilities, the same shape as a rogue-talent-style catalog.",
  },
  CSRimOtiqsmzjmGG: {
    id: "CSRimOtiqsmzjmGG",
    name: "Hidden Spell",
    bucket: "situational",
    note: "The save-DC and caster-level-check bonuses are scoped to the target's awareness/flanking state, an enemy-state condition the static sheet can't detect.",
  },
  FpEvs6vZADoZlm4J: {
    id: "FpEvs6vZADoZlm4J",
    name: "Shield the Weak",
    bucket: "situational",
    note: "Once-per-round immediate-action activation whose cover/Reflex benefit lands on adjacent allies while the champion forgoes his own save; ally-only and activation-gated.",
  },
  IRzgSlmFjgIGwVKh: {
    id: "IRzgSlmFjgIGwVKh",
    name: "Cypher: Defensive Scrollcaster",
    bucket: "situational",
    note: "The concentration bonus only applies when casting defensively from a scroll specifically, an action-scoped condition.",
  },
  KbH78K4CQJqWBOns: {
    id: "KbH78K4CQJqWBOns",
    name: "Opposition Alignment",
    bucket: "blocked",
    note: "The +1 bonus is on caster level checks to overcome the spell resistance of creatures with the divine scion's chosen opposition alignment subtype; clCheck only carries `sr`/`dispel` kinds, with no alignment-subtype axis, so an unconditional clCheck.sr Change would over-apply against every creature regardless of alignment.",
  },
  KvTvQsGXYoa7nbmZ: {
    id: "KvTvQsGXYoa7nbmZ",
    name: "Deadly Conviction",
    bucket: "blocked",
    note: "Matches the class-feature-effects.ts precedent for source-property-scoped save bonuses ('created by undead creatures'). The separate once/day negative-level ignore is a binary ability with no number.",
  },
  Lv1PWQrPMCb6prvi: {
    id: "Lv1PWQrPMCb6prvi",
    name: "Cypherlord",
    bucket: "blocked",
    note: "The save bonus is scoped to writing-based magical symbols/glyphs/sigils and traps specifically, narrower than the general `traps` category (which now exists) since it excludes non-writing traps; the free-action upgrade is a separate action-economy perk with no number.",
  },
  QyCuPG69WyxYp70i: {
    id: "QyCuPG69WyxYp70i",
    name: "Protective Grace",
    bucket: "numeric",
    note: "Unconditional dodge bonus to AC (+1 at 2nd level, +2 at 7th); the 'lost when denied Dexterity bonus' clause just restates the engine's existing generic dodge/flat-footed handling, not a special condition of this feature.",
  },
  Rfv9SNHDdNjyM9I1: {
    id: "Rfv9SNHDdNjyM9I1",
    name: "Incisive Spells",
    bucket: "situational",
    note: "The caster-level-check bonus only applies against creatures with an alignment subtype, an enemy-state condition.",
  },
  l1mHy5MiWcgCKftc: {
    id: "l1mHy5MiWcgCKftc",
    name: "Creedence: Sun's Mercy",
    bucket: "subsystem",
    note: "Removes the nonlethal-attack penalty for allies benefiting from solar invocation; a rules exception with no number of its own, dependent on another activation-gated ability.",
  },
  oPOknDxP2dsdvmXg: {
    id: "oPOknDxP2dsdvmXg",
    name: "Genie-Tongue",
    bucket: "situational",
    note: "The Charisma-check and Knowledge-check bonuses are scoped to genies and genie allies specifically, an enemy/topic-type condition outside any general skill target.",
  },
  "prestige:dragon-disciple:natural-armor": {
    id: "prestige:dragon-disciple:natural-armor",
    name: "Natural Armor",
    bucket: "numeric",
    note: "Unconditional cumulative natural armor bonus (+1/+2/+3 at 1st/4th/7th level), a clean level-gated formula with no activation involved.",
  },
  "prestige:duelist:elaborate-defense": {
    id: "prestige:duelist:elaborate-defense",
    name: "Elaborate Defense",
    bucket: "situational",
    note: "The extra dodge bonus only applies while fighting defensively or using total defense, a per-round stance choice the static sheet can't detect.",
  },
  "prestige:duelist:enhanced-mobility": {
    id: "prestige:duelist:enhanced-mobility",
    name: "Enhanced Mobility",
    bucket: "situational",
    note: "The AC bonus is scoped to attacks of opportunity provoked specifically by movement, an action-type condition outside any general AC target, even though the light-armor/no-shield gate is otherwise expressible.",
  },
  "prestige:duelist:improved-reaction": {
    id: "prestige:duelist:improved-reaction",
    name: "Improved Reaction",
    bucket: "numeric",
    note: "Unconditional initiative bonus (+2 at 2nd level, +4 at 8th), untyped like Improved Initiative so it stacks as the text describes.",
  },
  xvBGDYUbsE4Ozean: {
    id: "xvBGDYUbsE4Ozean",
    name: "Blood Sanctuary",
    bucket: "blocked",
    note: "Matches the class-feature-effects.ts precedent by name: the save bonus is scoped to spells 'he or an ally casts' specifically, a source-property scope outside the vocabulary.",
  },
  "5NS7Ec3WhKIkhygg": {
    id: "5NS7Ec3WhKIkhygg",
    name: "Quarry",
    bucket: "situational",
    note: "Designated-target bonus (attack rolls, auto-confirmed crits). slayer-talents.ts already documents Quarry/Studied Target as not modeled as a toggle on this sheet; this entry mirrors that treatment.",
  },
  HHSN56BJ90E4nsmM: {
    id: "HHSN56BJ90E4nsmM",
    name: "Credence",
    bucket: "subsystem",
    note: "Meta-feature: choose one credence per two levels from a list of largely non-numeric benefits (bonus feats, class-feature-level stacking, weapon properties). Named sub-benefits with their own numbers appear as their own worklist entries.",
  },
  PeRuht2i67Ad63Dn: {
    id: "PeRuht2i67Ad63Dn",
    name: "Deed: Unstoppable",
    bucket: "situational",
    note: "Temporary hit points and a doubled Constitution-check bonus only apply while the adrenaline rush is active, matching the parent Adrenaline Deed's activation gate.",
  },
  QkceRDLMpXqRJ5AQ: {
    id: "QkceRDLMpXqRJ5AQ",
    name: "Guerrilla Tactics",
    bucket: "subsystem",
    note: "Choose-one-active-tactic-at-a-time list (flanking exploit, sneak attack dice, Stealth-DC reduction, Acrobatics/Climb bonus); a talent-catalog shape, not an unconditional number.",
  },
  T4DKHIf0kNbafXQo: {
    id: "T4DKHIf0kNbafXQo",
    name: "Strike: Inspirational Strike",
    bucket: "situational",
    note: "Attack-activated ally buff lasting until the muse's next turn (longer on a critical hit); activation-gated and ally-facing.",
  },
  VNAS2B13lmCeQgwK: {
    id: "VNAS2B13lmCeQgwK",
    name: "Schismatic Apostle",
    bucket: "blocked",
    note: "The DC bonus is scoped to mind-affecting effects used against followers of two specific deities, a target-population scope with no vocabulary axis.",
  },
  Wl3FUflcmvQP0PaQ: {
    id: "Wl3FUflcmvQP0PaQ",
    name: "Sneak Attack (SLA)",
    bucket: "situational",
    note: "Dice-scaling extra damage that only applies when the target is flanked or denied its Dexterity bonus. slayer-talents.ts already treats this shape (Studied Target, Quarry) as not modeled as a toggle, and dice-based conditional damage isn't expressible as an unconditional Change.",
  },
  q7aOR0jKvbkVHhyF: {
    id: "q7aOR0jKvbkVHhyF",
    name: "Master Skald",
    bucket: "subsystem",
    note: "20th-level capstone removing inspired rage's AC penalty/skill restriction for allies and granting them an extra full-attack action; a rules-exception grant with no number of its own.",
  },
  "4hkvJKRAMWZf51V9": {
    id: "4hkvJKRAMWZf51V9",
    name: "Dare",
    bucket: "situational",
    note: "Swift-action activation spending a round of adrenaline rush to add a scaling die to one check; activation-gated and consumed per use.",
  },
  "9uivowmU43JcW1tH": {
    id: "9uivowmU43JcW1tH",
    name: "Phantom Strike",
    bucket: "situational",
    note: "Uses-per-day precision damage or cower effect against an unaware target; resource-gated and enemy-state scoped.",
  },
  FilJoixrjecBgjh1: {
    id: "FilJoixrjecBgjh1",
    name: "Channel Hellfire",
    bucket: "subsystem",
    note: "Free-action, per-day-limited swap of a spell's energy type to hellfire damage; a rules exception with no number carried by the sheet.",
  },
  JnXrphJlr1ULx1MK: {
    id: "JnXrphJlr1ULx1MK",
    name: "Studied Target",
    bucket: "situational",
    note: "Designated-target bonus. slayer-talents.ts already documents Studied Target as not modeled as a toggle on this sheet; this entry mirrors that treatment.",
  },
  S9lYCsz7oA7v3GzR: {
    id: "S9lYCsz7oA7v3GzR",
    name: "Discern Lies",
    bucket: "subsystem",
    note: "Rounds/day spell-like-ability grant (Discern Lies as the spell); an activation grant with no unconditional number.",
  },
  V3TQ2f5HeX4K6l4p: {
    id: "V3TQ2f5HeX4K6l4p",
    name: "No Trace",
    bucket: "situational",
    note: "The Survival-DC increase is unconditional, but the Disguise/Stealth bonus only applies while stationary and taking no action for a round, an activity-state condition the static sheet can't detect. Downgrading the whole entry avoids half-wiring a mixed feature.",
  },
  VEe4FTvo4iJn1SxV: {
    id: "VEe4FTvo4iJn1SxV",
    name: "Feyskinned",
    bucket: "situational",
    note: "Minutes/day-budgeted damage reduction that only becomes permanent at 7th level; resource-gated below that, and the level split isn't safely collapsible to one unconditional formula.",
  },
  paXeMHigQFWycaSn: {
    id: "paXeMHigQFWycaSn",
    name: "Fiendish Studies",
    bucket: "situational",
    note: "Designated-target bonus against evil outsiders, the crimson templar's version of Quarry/Studied Target; mirrors slayer-talents.ts's precedent of not modeling this shape as a toggle.",
  },
  "0uwZPvawcGIwE4j0": {
    id: "0uwZPvawcGIwE4j0",
    name: "Contravening Armament",
    bucket: "situational",
    note: "Standard-action, uses-per-day transfer of a damage-reduction-bypass property to an ally; activation-gated and largely ally-facing.",
  },
  "2kMumWrYA0V8IUup": {
    id: "2kMumWrYA0V8IUup",
    name: "Ki Pool",
    bucket: "subsystem",
    note: "Resource pool that functions like the monk's, usable to trigger lay on hands or smite evil; a pool grant, not an unconditional number.",
  },
  "4inISy7G5Ngd7S64": {
    id: "4inISy7G5Ngd7S64",
    name: "Religious Speaker",
    bucket: "situational",
    note: "The competence bonus only applies while the exalted's divine brand is visible, a toggleable cosmetic state the sheet can't track.",
  },
  "60CG4wbViDiKY9RX": {
    id: "60CG4wbViDiKY9RX",
    name: "Recklessness",
    bucket: "situational",
    note: "The morale bonus only applies on the round the chevalier enters a battle, once per day per opponent; a timing/resource condition.",
  },
  ATsERP3UJdSOvi14: {
    id: "ATsERP3UJdSOvi14",
    name: "Glib Lie",
    bucket: "subsystem",
    note: "Forces an opposed caster-level check on truth-detecting magic used against the mesmerist; a magic-effect rule, not a bonus to the mesmerist's own stats.",
  },
  DS7QqTVnyo4MAJUJ: {
    id: "DS7QqTVnyo4MAJUJ",
    name: "Genie's Friend",
    bucket: "situational",
    note: "The caster-level bonus is scoped to conjuring genies specifically, an action-type condition outside any general caster-level target.",
  },
  HvWaRPRZi8kzf1Cx: {
    id: "HvWaRPRZi8kzf1Cx",
    name: "Deed: Powerful Leaper",
    bucket: "situational",
    note: "Running-start and tripled Acrobatics-jump bonus only apply while the adrenaline rush is active, matching the parent Adrenaline Deed's activation gate.",
  },
  JZlCwRBCgOeFxIk7: {
    id: "JZlCwRBCgOeFxIk7",
    name: "Mesmerist Tricks",
    bucket: "subsystem",
    note: "Daily resource that implants one trick from a list, triggered later as a free action; a talent-catalog shape.",
  },
  KCI6s5ij0fU3KeJk: {
    id: "KCI6s5ij0fU3KeJk",
    name: "Seductive Intuition",
    bucket: "numeric",
    note: "Unconditional competence bonus (half class level) to four named skills, with no activation or scope narrower than the skills themselves.",
  },
  LzY5SyQjQkK0GyIL: {
    id: "LzY5SyQjQkK0GyIL",
    name: "Controlled Charge",
    bucket: "subsystem",
    note: "Removes the standard -2 AC penalty for charging; a rules exception, not a number the sheet carries.",
  },
  MEbgc7ZeWSi87LOP: {
    id: "MEbgc7ZeWSi87LOP",
    name: "Divine Deception",
    bucket: "situational",
    note: "The Bluff/Sense Motive bonus and Spellcraft DC increase are scoped to coded messages specifically; the added spells and their conditional doubled duration are a subsystem grant.",
  },
  P7twWlT0rRRprd92: {
    id: "P7twWlT0rRRprd92",
    name: "Creedence: Solar Defense",
    bucket: "situational",
    note: "The AC/Reflex bonus only applies while solar invocation is active, matching that ability's own activation gate.",
  },
  Q3x319WbNkCssApD: {
    id: "Q3x319WbNkCssApD",
    name: "Indomitable Will",
    bucket: "situational",
    note: "Matches the class-feature-effects.ts precedent by name: the save bonus only applies while raging or bloodraging and only from 14th level, a live-buff-state condition this loop cannot read.",
  },
  QLKF297AVzq8DKWo: {
    id: "QLKF297AVzq8DKWo",
    name: "Cascading Strike",
    bucket: "situational",
    note: "A chained awesome-blow maneuver triggered off a successful awesome blow hitting a second creature; an activation/combat-maneuver-state condition, not an unconditional number.",
  },
  Uo3PcMxXIO5kETjs: {
    id: "Uo3PcMxXIO5kETjs",
    name: "Shield of Wings",
    bucket: "situational",
    note: "Fire resistance/immunity is suppressed for a stretch of time whenever the swift-action wings are manifested or recently were; the two states (resistant, or flying-and-vulnerable) can't be told apart by a static sheet.",
  },
  WD8GoAUfMIzhdHSl: {
    id: "WD8GoAUfMIzhdHSl",
    name: "Toxic Manufactory",
    bucket: "subsystem",
    note: "A crafting-throughput rule for poisons/antitoxins (extra doses, gp-as-sp progress); a crafting mechanic, not a sheet number.",
  },
  XwM9u3NIYkxVdjrj: {
    id: "XwM9u3NIYkxVdjrj",
    name: "Cypher: Thassilonian Focus",
    bucket: "numeric",
    note: "Player picks one of the seven Thassilonian schools of magic, wired via the classFeature pick-choice mechanism (CLASS_FEATURE_CHOICES). SAVE_CATEGORIES names four of the seven as a school (enchantment, illusion, necromancy, transmutation), so those picks grant the +2 insight save bonus; Abjuration/Conjuration/Evocation have no matching category, so those picks emit nothing.",
  },
  Z95i8p91EoxGvlcP: {
    id: "Z95i8p91EoxGvlcP",
    name: "Deed: Untouchable",
    bucket: "situational",
    note: "Dodge bonus to AC only applies while the adrenaline rush is active, matching the parent Adrenaline Deed's activation gate.",
  },
  esX3xpUV8ndwzZzb: {
    id: "esX3xpUV8ndwzZzb",
    name: "Cypher: Analyze Scroll",
    bucket: "situational",
    note: "The Use Magic Device bonus only applies to casting spells from scrolls specifically, an action-scoped condition.",
  },
  f5IZh3FE9Vj3pFxH: {
    id: "f5IZh3FE9Vj3pFxH",
    name: "Master Poisoner",
    bucket: "situational",
    note: "The Craft (alchemy) bonus is scoped to working with poison specifically, narrower than the general Craft (alchemy) skill target; wiring it generically would over-apply to unrelated Craft (alchemy) work.",
  },
  f5jL22pjjlgghTLK: {
    id: "f5jL22pjjlgghTLK",
    name: "Heresy",
    bucket: "blocked",
    note: "The bonus is on 'checks to research devils' sigils or true names' without naming a specific skill, an ambiguous target the vocabulary can't resolve.",
  },
  lOYalHX4eZ75GDHo: {
    id: "lOYalHX4eZ75GDHo",
    name: "Expanded Portfolio",
    bucket: "subsystem",
    note: "Grants access to a chosen cleric domain plus its spells as once/day spell-like abilities; a subsystem grant, not a number.",
  },
  lRmf8xptuEyiZ8o5: {
    id: "lRmf8xptuEyiZ8o5",
    name: "Ardent Vision",
    bucket: "subsystem",
    note: "Grants at-will detect chaos/evil/good/law against a chosen opposed alignment; a spell-like-ability grant, not a number.",
  },
  oRac7XDHBN0JzuyY: {
    id: "oRac7XDHBN0JzuyY",
    name: "Improved Quarry",
    bucket: "situational",
    note: "Upgrade to Quarry's insight bonus and action economy; mirrors Quarry's own not-modeled-as-a-toggle treatment in slayer-talents.ts.",
  },
  "prestige:duelist:crippling-critical": {
    id: "prestige:duelist:crippling-critical",
    name: "Crippling Critical",
    bucket: "situational",
    note: "A secondary effect triggered only on a confirmed critical hit with a qualifying weapon, with the player picking which of five effects to apply; a crit-triggered, choice-dependent condition.",
  },
  "prestige:duelist:grace": {
    id: "prestige:duelist:grace",
    name: "Grace",
    bucket: "numeric",
    note: "Unconditional competence bonus to Reflex saves while wearing light or no armor and using no shield; the armor/shield gate is expressible via @armor.type/@shield.type, the same pattern archetype-effects.ts already uses for an armor-conditioned AC bonus.",
  },
  rm3Fp5N9av1lLxfK: {
    id: "rm3Fp5N9av1lLxfK",
    name: "Advanced Tactics",
    bucket: "subsystem",
    note: "Adds two more choices (Preemptive Strike, Trick Shot) to Guerrilla Tactics' switchable-tactic list; the same choice-catalog shape as its parent.",
  },
  rrVK10NncsIXozJH: {
    id: "rrVK10NncsIXozJH",
    name: "Runefinding",
    bucket: "situational",
    note: "The trapfinding-bonus increase is scoped to magical writings specifically, narrower than any general trapfinding target the engine carries, and it also grants the trap-spotter rogue talent (itself scoped to magical writings) as a subsystem addition.",
  },
};
