/**
 * Class-feature classification shard: wave assignment "reachable3" — features
 * granted through some `RefData.classes[*].features` list (base or prestige),
 * so a `CLASS_FEATURE_CHANGE_PATCHES` entry can reach them. Owner-assigned
 * worklist; `index.ts` documents the shard convention.
 */

import type { ClassFeatureClassificationEntry } from "./types.js";

export const CLASS_FEATURE_CLASSIFICATION_REACHABLE_3: Readonly<
  Record<string, ClassFeatureClassificationEntry>
> = {
  "4r83TfLHXrRmXtIn": {
    id: "4r83TfLHXrRmXtIn",
    name: "Animal Focus",
    bucket: "situational",
    note: "Swift-action activation, minutes-per-day duration, and the bonus depends on which of twelve animal aspects is currently chosen; no unconditional number to carry.",
  },
  WXjbAV4Cr2mmbHBq: {
    id: "WXjbAV4Cr2mmbHBq",
    name: "Terrain Dominance",
    bucket: "subsystem",
    note: "Grants a bonus scoped to whichever terrain the character already mastered, chosen from a list of a dozen wildly different spell-like abilities, resistances, and combat bonuses; the target depends entirely on an unrecorded pick.",
  },
  RIjKEsxj9nYs2W0f: {
    id: "RIjKEsxj9nYs2W0f",
    name: "Terrain Mastery",
    bucket: "subsystem",
    note: "Same shape as Terrain Dominance one level up: a move-action skill bonus plus a chosen-from-a-list always-on benefit that differs per terrain (resistance, DR, skill bonus, speed, or a rules exception) with no single expressible target.",
  },
  WSqWT9ZIshtC5vlV: {
    id: "WSqWT9ZIshtC5vlV",
    name: "Rage",
    bucket: "situational",
    note: "The barbarian's signature activated buff (rounds/day, morale bonus to Str/Con/Will, AC penalty, post-rage fatigue); modeled as a toggleable buff elsewhere in the engine (see rage-fatigue.ts), never as a static Change on this entry.",
  },
  s5ulrkl449ddAjdF: {
    id: "s5ulrkl449ddAjdF",
    name: "Allied Retribution",
    bucket: "situational",
    note: "Requires selecting a designated adversary who attacked an ally, caps the number of adversaries by class level, and the bonus only applies against that adversary for a limited duration; entirely activation and target-state gated.",
  },
  "8wPhoiyqd0HQvMl5": {
    id: "8wPhoiyqd0HQvMl5",
    name: "Utility Shot",
    bucket: "subsystem",
    note: "A gunslinger deed already covered by the dedicated deeds.ts reference catalog (grit-spend, choice of blast-lock/scoot-object/stop-bleeding); not modeled as an automatic Change there either.",
  },
  UBv1y1h93jrnhWxO: {
    id: "UBv1y1h93jrnhWxO",
    name: "Sacred Armor",
    bucket: "subsystem",
    note: "Swift-action activated, minutes-per-day resource (the pool itself is already tracked via the vendored uses.maxFormula), and the enhancement bonus plus chosen armor special ability vary daily by player pick; no single flat Change.",
  },
  YGbFrqaGvnCbAKKV: {
    id: "YGbFrqaGvnCbAKKV",
    name: "Sacred Weapon",
    bucket: "subsystem",
    note: "Weapon damage-by-level table plus a swift-action, rounds-per-day (uses.maxFormula already wired) enhancement bonus with a player-chosen special ability from an alignment-gated list; not a flat Change target.",
  },
  k5S5PArYaCZhUqnh: {
    id: "k5S5PArYaCZhUqnh",
    name: "Sure Shot",
    bucket: "situational",
    note: "Limited to a number of uses per day equal to class level, applies only to crossbow attacks, and adds Charisma bonus plus per-level damage only on a spent use; activation and weapon-scope gated.",
  },
  "6yGbgontLAsforzc": {
    id: "6yGbgontLAsforzc",
    name: "Proven Weapon Familiarity",
    bucket: "blocked",
    note: "Attack/damage bonus scoped to a fixed list of specific weapon types (composite longbow/shortbow, longbow, longsword, rapier, shortbow, short sword, any 'elven' weapon); the engine's attack-bonus target has no per-weapon-type axis, so an unconditional Change would over-apply to every weapon.",
  },
  CpGRtCFDyats5Oqt: {
    id: "CpGRtCFDyats5Oqt",
    name: "Pirate Talent: Classic Duelist",
    bucket: "blocked",
    note: "Attack bonus scoped to cutlass/rapier/short sword specifically; same weapon-type-scoping gap as Proven Weapon Familiarity, no expressible target.",
  },
  FZLqcO9hvP5WEyqU: {
    id: "FZLqcO9hvP5WEyqU",
    name: "Defy Danger",
    bucket: "blocked",
    note: "Save bonus scoped to a danger the player chooses from a list (charms/curses/disease/fear/poison/traps/one creature type's innate powers); this is the class-feature-effects.ts header's own cited choice-dependent-scope example, so it stays unpromoted.",
  },
  J2rIdwacRuGkgwVJ: {
    id: "J2rIdwacRuGkgwVJ",
    name: "Shared Consciousness",
    bucket: "situational",
    note: "Only applies while the phantom is confined in the spiritualist's consciousness (not manifested or banished), a live buff/creature state the class-feature loop cannot read; cited directly in class-feature-effects.ts's header as a deliberate non-promotion.",
  },
  Rao7jnaGBzSbltiw: {
    id: "Rao7jnaGBzSbltiw",
    name: "Spiritual Interference",
    bucket: "situational",
    note: "AC/save bonuses depend on the phantom's manifestation state and proximity, and are voided if the phantom is grappled/helpless/unconscious; cited directly in class-feature-effects.ts's header as a deliberate non-promotion.",
  },
  Rby6hVRn8hpm69ba: {
    id: "Rby6hVRn8hpm69ba",
    name: "Blessed Conviction",
    bucket: "blocked",
    note: "Save bonus scoped to 'spells and effects created by undead creatures' -- a property of the effect's source, not a kind of effect; cited directly in class-feature-effects.ts's header (with its Deadly Conviction sibling) as having no SAVE_CATEGORIES axis.",
  },
  YMWTuWtjAsmoBgmP: {
    id: "YMWTuWtjAsmoBgmP",
    name: "Authority",
    bucket: "situational",
    note: "The +4 Diplomacy/Intimidate bonus only applies to checks 'regarding matters of the law and her authority,' not general use of either skill; narrower than the skill target, so an unconditional Change would over-apply.",
  },
  eBMtTdKIROnXb5fF: {
    id: "eBMtTdKIROnXb5fF",
    name: "Poison Resistance",
    bucket: "numeric",
    note: "+2 vs. poison, +4 at 7th (the vendored grant level is 7th itself, so the +2 tier is never seen in practice), wired via the per-class 'liberator:Poison Resistance' key, which keeps this bearer's formula separate from the Alchemist/Investigator entry's different pace sharing the bare name.",
  },
  gwZJB6sOfwrkSpUD: {
    id: "gwZJB6sOfwrkSpUD",
    name: "Tower of Intelligence",
    bucket: "situational",
    note: "The caster-level-check bonus is per Intelligence-suit card drawn during Harrow casting, a per-activation random outcome, not a static number.",
  },
  iBcNsOdYL4GQMhsr: {
    id: "iBcNsOdYL4GQMhsr",
    name: "Pirate Talent: Rigging Monkey",
    bucket: "situational",
    note: "The Climb bonus and reduced movement penalty only apply while climbing with a rope specifically, narrower than the full Climb skill and action-scoped.",
  },
  jOwHfnBNsAw5x8sb: {
    id: "jOwHfnBNsAw5x8sb",
    name: "Favored Terrain (Ex)",
    bucket: "situational",
    note: "The initiative/skill bonuses only apply within a radius of a small settlement, a location-scoped condition; mirrors ranger.ts's treatment of favored terrain as a situational selection, never an automatic Change.",
  },
  jkigrVeg3TUKg0Gy: {
    id: "jkigrVeg3TUKg0Gy",
    name: "Consume Spells",
    bucket: "situational",
    note: "Expending a spell slot to add points to the arcane reservoir is a move action the player chooses to take a limited number of times per day (uses.maxFormula already tracks the daily cap); the reservoir gain itself is not an unconditional sheet number.",
  },
  nOLAYJpzuRmt1GdB: {
    id: "nOLAYJpzuRmt1GdB",
    name: "Greater Spiritual Interference",
    bucket: "situational",
    note: "Same phantom-manifestation-state gating as Spiritual Interference, scaled up to affect allies too; cited directly in class-feature-effects.ts's header as a deliberate non-promotion.",
  },
  uKVudFr94iVPQK0X: {
    id: "uKVudFr94iVPQK0X",
    name: "Master of All Lands",
    bucket: "subsystem",
    note: "Grants a +2 bonus in all favored terrains plus treating every other terrain as favored, automatic success on weather/temperature checks, and an ally aura -- all riding on the already choice-dependent Terrain Mastery scope, with no single expressible target.",
  },
  "4IKq91F9t96FbdPj": {
    id: "4IKq91F9t96FbdPj",
    name: "Trick: Shipboard Authority",
    bucket: "situational",
    note: "Once-per-day standard action granting a chosen bonus (attack or a specific skill, player's pick each use) to allies within range; activation and choice gated.",
  },
  "7GNdI4zKfTcxNCk4": {
    id: "7GNdI4zKfTcxNCk4",
    name: "Alchemy",
    bucket: "situational",
    note: "Most of the entry describes the extract/bomb/mutagen framework (subsystem-shaped). The class-level competence bonus on Craft (alchemy) is scoped to checks made 'to create an alchemical item', not the skill wholesale -- published stat blocks list it parenthetically as a conditional -- so an unconditional skill.crf.alchemy Change would over-apply to identification and other non-crafting checks.",
  },
  "7gHiZBNHjwefbBLI": {
    id: "7gHiZBNHjwefbBLI",
    name: "Bomb",
    bucket: "subsystem",
    note: "Bomb count and damage die scale with level and Intelligence (uses.maxFormula already tracks the daily use cap), but throwing a bomb is a standard action the player chooses to take, and the ability is really a resource-gated attack option, not a static bonus.",
  },
  B9j7nJOZ8vna9geL: {
    id: "B9j7nJOZ8vna9geL",
    name: "Know the Ropes",
    bucket: "situational",
    note: "The Climb bonus, one-handed climbing, and the other listed benefits only apply while climbing ropes/rigging specifically; action-scoped, same pattern as Rigging Monkey.",
  },
  HRbY7bS8JXAi1w9b: {
    id: "HRbY7bS8JXAi1w9b",
    name: "Pirate Talent",
    bucket: "subsystem",
    note: "The umbrella entry describing the whole pirate-talent list (Classic Duelist, Rigging Monkey, Drink for Free, and the rest); a choice-from-a-talent-list feature with no number of its own.",
  },
  KCzCnIRL0kXH8Aaz: {
    id: "KCzCnIRL0kXH8Aaz",
    name: "To the Rescue",
    bucket: "situational",
    note: "Standard-action activated buff granting attack/Escape Artist/fear-save bonuses to allies within 30 feet for a limited duration; ally-scoped and activation-gated, cited directly in class-feature-effects.ts's header as a deliberate non-promotion.",
  },
  KeqW25zOjSQAl3n2: {
    id: "KeqW25zOjSQAl3n2",
    name: "Gun Training",
    bucket: "blocked",
    note: "Damage bonus (and reduced misfire increase) scoped to one specific firearm type the player chooses, with more types picked up at later levels; no per-weapon-type target exists, and the picks themselves aren't recorded anywhere the engine can read.",
  },
  O93n7H9kMd1xC58Q: {
    id: "O93n7H9kMd1xC58Q",
    name: "Advanced Tricks",
    bucket: "subsystem",
    note: "The umbrella entry for advanced pirate tricks (Burst of Speed, Defensive Climber, Fearsome Advance, Foot Sweep, Shipboard Authority); a choice-from-a-list feature with no number of its own.",
  },
  XiKmX8tAtsWYd75f: {
    id: "XiKmX8tAtsWYd75f",
    name: "Wraithwall",
    bucket: "situational",
    note: "Once-per-day standard action granting ghost-touch armor and a save bonus to allies within 30 feet for one minute; ally-scoped and activation-gated.",
  },
  n1PlbzPfZGklyUVV: {
    id: "n1PlbzPfZGklyUVV",
    name: "Maneuver Training (BRA)",
    bucket: "blocked",
    note: "The combat-maneuver-check and CMD bonuses are scoped to whichever maneuver(s) the brawler selects (progressively more as she levels), and CharacterDoc has no field recording that pick; no reachable target for an unrecorded choice.",
  },
  qXbFw1qEdelMGNH4: {
    id: "qXbFw1qEdelMGNH4",
    name: "Gunslinger's Dodge",
    bucket: "subsystem",
    note: "A gunslinger deed already covered by the dedicated deeds.ts reference catalog (spend grit to move-and-dodge, or drop prone for a bigger AC bonus); not modeled as an automatic Change there either.",
  },
  tRF0m0XTwkYquQhx: {
    id: "tRF0m0XTwkYquQhx",
    name: "Favored Enemy",
    bucket: "situational",
    note: "Explicitly 'functions like the ranger class feature of the same name' -- mirrors ranger.ts's treatment of Favored Enemy as a situational selection, never an automatic Change.",
  },
  uHxDgXFUFHTl0OSn: {
    id: "uHxDgXFUFHTl0OSn",
    name: "Force of Will",
    bucket: "blocked",
    note: "Save bonus scoped to a subschool/descriptor the player chooses from a list, expanding to three simultaneous picks by 9th level; this is the class-feature-effects.ts header's own cited choice-dependent-scope example, so it stays unpromoted.",
  },
  vbStoN1C4NIIIW2D: {
    id: "vbStoN1C4NIIIW2D",
    name: "Authoritative Command",
    bucket: "situational",
    note: "Move-action (later swift-action) activation naming up to several allies each round, and the bonus is conditioned on at least one selected ally actually complying with the order that round; activation and external-agent gated.",
  },
  "11jZ6ijPMGXY4t72": {
    id: "11jZ6ijPMGXY4t72",
    name: "United Defense",
    bucket: "situational",
    note: "Swift-action selection of one ally each round; the AC penalty/dodge bonus only apply while adjacent to that specific selected ally, a live per-round state the static sheet can't track.",
  },
  "2WAZhPWZw3wH9zCV": {
    id: "2WAZhPWZw3wH9zCV",
    name: "Fade from Sight",
    bucket: "situational",
    note: "Swift-action activated, rounds-per-day Stealth-without-cover ability; a rules exception gated behind a limited daily resource, not an unconditional bonus.",
  },
  "3Jy5Y4DhjmQprvLj": {
    id: "3Jy5Y4DhjmQprvLj",
    name: "Bane",
    bucket: "situational",
    note: "Explicitly identical to the inquisitor's Bane ability: a rounds-per-day weapon enhancement against a favored-enemy-style target chosen at the moment of use; activation and target-choice gated.",
  },
  NgGQ80uiwIbckeUh: {
    id: "NgGQ80uiwIbckeUh",
    name: "Harrow Casting",
    bucket: "subsystem",
    note: "A meta-mechanic layered on spellcasting (draw three Harrow cards, which may alter the spell's parameters depending on alignment match), limited per day; not itself a flat number.",
  },
  V7cGG7vKN0BY2Bhb: {
    id: "V7cGG7vKN0BY2Bhb",
    name: "Animal Companion (HUN)",
    bucket: "subsystem",
    note: "Grants an animal companion (the druid animal-companion subsystem, with hunter-specific tweaks to trick lists and summon-duration on death); the companion's own stat block, not a Change on the hunter's sheet.",
  },
  ZvwRtHL9eolE7jSJ: {
    id: "ZvwRtHL9eolE7jSJ",
    name: "Discern Lies",
    bucket: "subsystem",
    note: "Grants discern lies as a spell-like ability a number of times per day; a granted ability, not a flat sheet number.",
  },
  "2qcz39w9O2Qlms0Q": {
    id: "2qcz39w9O2Qlms0Q",
    name: "Poison Resistance",
    bucket: "numeric",
    note: "+2 vs. poison at 2nd, +4 at 5th, +6 at 8th, wired for the Alchemist and Investigator via the per-class 'alchemist:Poison Resistance' and 'investigator:Poison Resistance' keys, which keep this bearer's formula separate from the Liberator's differently-paced entry sharing the bare name. The alchemist's separate 10th-level poison immunity is a different named feature, not modeled here.",
  },
  "6QPYuJ1grudBotuu": {
    id: "6QPYuJ1grudBotuu",
    name: "Lockbreaker",
    bucket: "blocked",
    note: "Half of the bonus targets 'Open Lock,' a 3.5-era skill that doesn't exist in this system's vendored skill list (folded into Disable Device in PF1), and the Escape Artist half is scoped only to escaping bindings/shackles, narrower than the full skill; no single clean target.",
  },
  A31OFBWvPFQCTFt7: {
    id: "A31OFBWvPFQCTFt7",
    name: "Stern Gaze",
    bucket: "numeric",
    note: "Unconditional morale bonus equal to half class level on Intimidate and Sense Motive; the same feature already exists on Inquisitor with its own vendored Change using this exact formula.",
  },
  A9PNCXFvh5CobB3j: {
    id: "A9PNCXFvh5CobB3j",
    name: "Opportunity Attacker",
    bucket: "subsystem",
    note: "Removes the flat-footed/denied-Dex requirement for sneak attack on attacks of opportunity; a rules exception with no Change-shaped number of its own (the sneak attack dice themselves are tracked elsewhere).",
  },
  CK0R5YUIA2nZtBuy: {
    id: "CK0R5YUIA2nZtBuy",
    name: "Dramatic Interrogation",
    bucket: "situational",
    note: "The +5 bonus only applies to Diplomacy/Intimidate/Perform checks made while threatening a helpless creature, targeting creatures with a specific attitude toward that helpless creature; heavily action- and target-state-scoped.",
  },
  D13TR3rNmjwMPXuD: {
    id: "D13TR3rNmjwMPXuD",
    name: "Deadeye",
    bucket: "subsystem",
    note: "A gunslinger deed already covered by the dedicated deeds.ts reference catalog (spend grit per range increment to target touch AC); not modeled as an automatic Change there either.",
  },
  IQGNLG7hseEG8WG0: {
    id: "IQGNLG7hseEG8WG0",
    name: "Spirit Deck",
    bucket: "situational",
    note: "Standard-action activated, limited-per-day blast whose damage depends on a random Harrow card draw matched against the harrower's alignment; no static number to carry.",
  },
  M9f0p2kKrGsyZPgE: {
    id: "M9f0p2kKrGsyZPgE",
    name: "Unbounded Stride",
    bucket: "situational",
    note: "Swift-action activated, rounds-per-day immunity to movement-impeding terrain and magic; a rules exception gated behind a limited daily resource.",
  },
  ObLvghHyt1YYufR4: {
    id: "ObLvghHyt1YYufR4",
    name: "Favored Port",
    bucket: "situational",
    note: "The skill/initiative/Will bonuses only apply within a chosen favored port (or a ship whose home port is one); location-scoped condition.",
  },
  Oj0q0P6Mep8NKjaj: {
    id: "Oj0q0P6Mep8NKjaj",
    name: "Pirate Talent: Drink for Free",
    bucket: "situational",
    note: "The Diplomacy/Intimidate bonus only applies within a chosen favored tavern; location-scoped condition (plus a non-mechanical free-drinks perk).",
  },
  OnSt4sMon27ojQ53: {
    id: "OnSt4sMon27ojQ53",
    name: "Infernal Armor",
    bucket: "situational",
    note: "The Charisma-check bonus and darkvision/energy resistances only apply while wearing Hellknight armor specifically, an equipment-state condition the static sheet can't verify without over-applying.",
  },
  Ozz41Xbq0eIH1Na6: {
    id: "Ozz41Xbq0eIH1Na6",
    name: "Exploitive Maneuver",
    bucket: "situational",
    note: "Requires an immediate-action combat maneuver check against an enemy's CMD, triggered only when an enemy targets the halfling in combat; fully activation and opposed-check gated.",
  },
  PgeWNSXKjNi4AcNy: {
    id: "PgeWNSXKjNi4AcNy",
    name: "Aura of Law",
    bucket: "blocked",
    note: "Describes the strength of a detect-law-style aura, which has no corresponding field anywhere in DerivedSheet; there is no expressible engine target for 'aura power.'",
  },
  Rh4www7gtV7wvUzg: {
    id: "Rh4www7gtV7wvUzg",
    name: "Grit",
    bucket: "subsystem",
    note: "Defines the grit resource pool (the daily maximum is already tracked via the vendored uses.maxFormula); spending and regaining grit are activation-driven, not a flat Change.",
  },
  Rzexvt4z8taA8dCu: {
    id: "Rzexvt4z8taA8dCu",
    name: "Fervor",
    bucket: "subsystem",
    note: "Defines the fervor resource pool (daily maximum already tracked via uses.maxFormula); each use is a player-chosen heal/harm/spontaneous-cast action, not a flat bonus.",
  },
  SqIzpeNFCPHPCDzq: {
    id: "SqIzpeNFCPHPCDzq",
    name: "Trick: Defensive Climber",
    bucket: "subsystem",
    note: "Removes the Dexterity-bonus-to-AC penalty while climbing; a rules exception with no Change-shaped number.",
  },
  UyFmxdJKtmiqs2Oc: {
    id: "UyFmxdJKtmiqs2Oc",
    name: "Diabolic Harbinger",
    bucket: "subsystem",
    note: "Grants telepathy, all-darkness perfect vision, and immunity to blindness/dazzling effects while wearing the signifer mask; predominantly ability/sense grants, with a secondary Charisma bonus scoped to lawful/outsider creatures folded in.",
  },
  WyrFeMHvGdFsFQKU: {
    id: "WyrFeMHvGdFsFQKU",
    name: "Spellbooks (ARC)",
    bucket: "subsystem",
    note: "Describes the arcanist's spellbook-preparation mechanic (which spells can be prepared, how new formulae are learned); a rules framework, not a flat number.",
  },
  Yhggkol6uVcgsGPs: {
    id: "Yhggkol6uVcgsGPs",
    name: "Oathmark",
    bucket: "subsystem",
    note: "A narrative divination/curse-linking ability (magically seals an agreement, marks the breaker) with limited uses per day; no Change-shaped number involved.",
  },
  YqNHTHTTWUwyTFW9: {
    id: "YqNHTHTTWUwyTFW9",
    name: "Heritor's Honor",
    bucket: "blocked",
    note: "Cha-mod Will bonus is unconditional, but the source adds 'The bonus from this ability doesn't stack with those from similar effects' (divine grace and kin). Untyped bonuses always stack in this engine, so an untyped Change double-counts Charisma for the plausible antipaladin (Unholy Resilience) entrant; no non-stacking axis exists to express it.",
  },
  Zv5eTbRpRYavLGcK: {
    id: "Zv5eTbRpRYavLGcK",
    name: "Anonymity",
    bucket: "situational",
    note: "The Bluff/Disguise bonus only applies to checks made to conceal identity, narrower than the full skill target.",
  },
  bs5eXqt2sECncoWz: {
    id: "bs5eXqt2sECncoWz",
    name: "Intercept",
    bucket: "situational",
    note: "The combat-maneuver-check and CMD bonuses only apply when using the Stand Still feat or defending a specific threatened square against an Acrobatics-based move-through; both are action-scoped.",
  },
  fth3wHPJRTiAQkuQ: {
    id: "fth3wHPJRTiAQkuQ",
    name: "Exceptionally Lucky",
    bucket: "numeric",
    note: "Overrides the character's Halfling Luck racial bonus on saving throws (+1) to a higher flat value (+2, then +3 at 4th level); expressible as an allSavingThrows racial-type Change matching the vendored race change's own type, since typed stacking already resolves to the higher of the two same-type bonuses.",
  },
  ik7YjF6IXgTNeqrq: {
    id: "ik7YjF6IXgTNeqrq",
    name: "Ectoplasmic Bonded Manifestation",
    bucket: "situational",
    note: "The AC bonus and tendril attacks depend on the phantom being manifested in ectoplasmic form specifically, a live buff/creature-state condition; class-feature-effects.ts's header names 'a manifested phantom's mode' directly as this shape of gating.",
  },
  izFlIPdU4a9yHBDm: {
    id: "izFlIPdU4a9yHBDm",
    name: "Detect Undead",
    bucket: "subsystem",
    note: "Grants detect undead as an at-will spell-like ability; a granted ability, not a flat sheet number.",
  },
  p1UI7pVRl5B0hyKK: {
    id: "p1UI7pVRl5B0hyKK",
    name: "Reforged Heart (Su or Sp)",
    bucket: "subsystem",
    note: "Grants greater make whole as a once-per-day spell-like ability; a granted ability, not a flat sheet number.",
  },
  rJ8E3SxHrK2PR5S8: {
    id: "rJ8E3SxHrK2PR5S8",
    name: "Lantern Arcana",
    bucket: "subsystem",
    note: "Grants a large tiered list of spell-like abilities gained at different levels with per-day use counts; a granted-ability list, not a flat number.",
  },
  rVgbJRQKdL8Qxx0S: {
    id: "rVgbJRQKdL8Qxx0S",
    name: "Slaver Slayer",
    bucket: "situational",
    note: "Attack/damage bonus scoped to targets known to be slavers or slave-owners, a specific-enemy condition the static sheet can't detect; same shape as ranger.ts's Favored Enemy treatment.",
  },
  umr9pzGSXWhyVxX3: {
    id: "umr9pzGSXWhyVxX3",
    name: "Greater Sunder",
    bucket: "numeric",
    note: 'The +2 morale bonus on the sunder combat maneuver check is wired via CLASS_FEATURE_CHANGE_PATCHES (cmb, maneuverCategories: ["sunder"]) — the text\'s own "but not when defending" confirms it\'s cmb-only. The hardness-ignoring half has no Change target.',
  },
  v5euWGtNKvsdk1eq: {
    id: "v5euWGtNKvsdk1eq",
    name: "Signifer Mask",
    bucket: "blocked",
    note: "The primary save bonus is scoped to 'spells and abilities that rely on visual effects,' one of the class-feature-effects.ts header's own cited narrower-than-vocabulary categories; the Sense Motive bonus is also gated on wearing this specific granted item, so the whole entry stays unpromoted.",
  },
  vLBLeepb4eyERA8G: {
    id: "vLBLeepb4eyERA8G",
    name: "Assiduous Gaze",
    bucket: "subsystem",
    note: "Swift-action activated, rounds-per-day gaze power chosen from a list (Elucidation/Morality/Scrutiny/Veracity/Vigilance); a choice-from-a-list feature, not a flat number.",
  },
  xtSXGphDhzkMwbpW: {
    id: "xtSXGphDhzkMwbpW",
    name: "Bonded Senses",
    bucket: "subsystem",
    note: "Grants shared senses with the manifested phantom, rounds per day; a granted sensory ability, not a Change-shaped number.",
  },
  zQ2c1v3t7F5EeL2u: {
    id: "zQ2c1v3t7F5EeL2u",
    name: "Elemental Seal",
    bucket: "subsystem",
    note: "A binding-pool-gated rune with an effect that depends on which of four elements is chosen and whether the target is a matching genie, a non-genie creature, or a surface; no single expressible target.",
  },
  zrTVb83VhkFnEv6G: {
    id: "zrTVb83VhkFnEv6G",
    name: "Mutagen",
    bucket: "subsystem",
    note: "Brewing and drinking a mutagen is an activated choice (which physical ability score to boost, at the cost of a mental one) with a single-dose resource already tracked via uses.maxFormula; not an unconditional bonus.",
  },
};
