/**
 * Class-feature classification shard: wave assignment "reachable5" — features
 * granted through some `RefData.classes[*].features` list (base or prestige),
 * so a `CLASS_FEATURE_CHANGE_PATCHES` entry can reach them. Owner-assigned
 * worklist; `index.ts` documents the shard convention.
 */

import type { ClassFeatureClassificationEntry } from "./types.js";

export const CLASS_FEATURE_CLASSIFICATION_REACHABLE_5: Readonly<
  Record<string, ClassFeatureClassificationEntry>
> = {
  J2q6ZzQy1lXpsXBq: {
    id: "J2q6ZzQy1lXpsXBq",
    name: "Enduring Scar",
    bucket: "subsystem",
    note: "Parent 'choose one scar every two levels, usable a limited number of times per day' framework; each specific scar (Scar: Tenacity, Scar: Suffering, etc.) is its own catalog entry.",
  },
  eGRZ9h4vBfTTg1BC: {
    id: "eGRZ9h4vBfTTg1BC",
    name: "Sidereal Arcana (Su or Sp)",
    bucket: "subsystem",
    note: "Parent 'choose one arcanum every two levels' framework; each specific arcanum (Arcana: The Daughter, The Stargazer, etc.) is its own catalog entry.",
  },
  VqNBvy3NcMW5JAkW: {
    id: "VqNBvy3NcMW5JAkW",
    name: "Scar: Tenacity",
    bucket: "situational",
    note: "Immediate-action morale bonus triggered only when the scar seeker is struck by a critical hit or sneak attack, lasting a Charisma-modifier number of rounds; not an always-on number.",
  },
  "6sqnxX09yZphuSUN": {
    id: "6sqnxX09yZphuSUN",
    name: "Red Shroud",
    bucket: "situational",
    note: "Move-action activation, Constitution-modifier uses per day, and a fixed rounds-per-level duration; the dodge bonus and fast healing only apply while the shroud is up.",
  },
  tqJwOCmypbhz2Lu3: {
    id: "tqJwOCmypbhz2Lu3",
    name: "Defensive Stance",
    bucket: "situational",
    note: "The dodge AC, Strength/Constitution, and Will save bonuses only apply while the stance is active, a toggled state the static sheet cannot track (same shape as barbarian rage).",
  },
  v65MtgBZiOUOTJxu: {
    id: "v65MtgBZiOUOTJxu",
    name: "Subtle Manipulator",
    bucket: "situational",
    note: "Requires a full-round action and a successful opposed Sense Motive check before the Diplomacy bonus applies, and then only against that one studied target.",
  },
  LYSvRZnyYUFW67ZV: {
    id: "LYSvRZnyYUFW67ZV",
    name: "Arcana: The Daughter",
    bucket: "blocked",
    note: "Stargazer's vendored feature list auto-lists all twelve Sidereal Arcana choices at level 1 with no choice-tracking in collect.ts's classes[*].features loop, so a name-keyed patch would grant this fear-save bonus to every stargazer, not just those who picked The Daughter; what would otherwise be a clean unconditional bonus stays blocked.",
  },
  Vh3QCBA3W76CzMoP: {
    id: "Vh3QCBA3W76CzMoP",
    name: "Virtuous Rune",
    bucket: "subsystem",
    note: "Parent 'choose one virtuous rune, eventually mastering all seven by 9th level' framework; each specific rune (Virtuous Rune: Love, Humility, Generosity, etc.) is its own catalog entry.",
  },
  wMZRhD7D4VayGNx0: {
    id: "wMZRhD7D4VayGNx0",
    name: "Eradication",
    bucket: "blocked",
    note: "The save and DC/CL bonus is scoped to outsiders specifically, an attacker-property carve-out SAVE_CATEGORIES excludes; matches this file's own documented Eradication non-promotion.",
  },
  "7dp70UraLifmgIXp": {
    id: "7dp70UraLifmgIXp",
    name: "Arcana: The Newlyweds",
    bucket: "blocked",
    note: "Same Sidereal Arcana reachability defect as every arcanum (all twelve auto-listed at Stargazer level 1, no choice-tracking); its Bluff/Diplomacy bonus and DC increase are also scoped to romantically-attracted targets specifically, with no matching Change target.",
  },
  NlWyrq09da7twytD: {
    id: "NlWyrq09da7twytD",
    name: "Scar: Suffering",
    bucket: "situational",
    note: "This file's own header lists Scar: Suffering among the activation-gated non-promotions: the DR and save bonus only last from the swift action until the start of the scar seeker's next turn.",
  },
  Y9LSWuESrJ8LXpEf: {
    id: "Y9LSWuESrJ8LXpEf",
    name: "Legal Judgment",
    bucket: "subsystem",
    note: "Parent 'pronounce one judgment type, swift action to change it' framework; each specific judgment (Judgment: Justice, Destruction, Lucky Dodge, etc.) is its own catalog entry, and only the currently active judgment applies.",
  },
  su4BFzxn5pSyDFLt: {
    id: "su4BFzxn5pSyDFLt",
    name: "Divine Luck",
    bucket: "situational",
    note: "Charisma-modifier uses per day, added after the roll but before the result is known; a resource-gated swingy bonus, not an always-on number.",
  },
  "1P1gpI24ajcoVfoP": {
    id: "1P1gpI24ajcoVfoP",
    name: "Arcana: The Stargazer",
    bucket: "blocked",
    note: "Same Sidereal Arcana reachability defect as every arcanum: all twelve are auto-listed at Stargazer level 1 with no choice-tracking, so a name-keyed patch for this initiative bonus would apply to every stargazer regardless of pick.",
  },
  D2XKqo13tiVc2vPF: {
    id: "D2XKqo13tiVc2vPF",
    name: "Tyrant's Discipline",
    bucket: "subsystem",
    note: "Parent 'choose one discipline every two levels' framework; the only child discipline in this shard (Discipline: Driving Assault) is separately catalogued and is itself activation-gated.",
  },
  GCBmMGUXTJH5D3aQ: {
    id: "GCBmMGUXTJH5D3aQ",
    name: "Arcana: The Patriarch",
    bucket: "blocked",
    note: "Same Sidereal Arcana reachability defect as every arcanum (all twelve auto-listed at level 1, no choice-tracking); the navigation bonus is also scoped to a specific skill use rather than the whole skill.",
  },
  JFeEmxRujCStrxOi: {
    id: "JFeEmxRujCStrxOi",
    name: "Virtuous Rune: Love",
    bucket: "situational",
    note: "Requires sacrificing a prepared spell or slot as an immediate action; the save bonus only applies while that rune's bond is active, and a runeguard only masters this specific rune at 5th level regardless of the vendored level-1 listing.",
  },
  Knq0NLW6iOqv3KhR: {
    id: "Knq0NLW6iOqv3KhR",
    name: "Chainbreaker",
    bucket: "situational",
    note: "The +10 bonus only applies to checks made to escape bindings with manacles or ropes, narrower than the whole Escape Artist skill; the hardness-bypass half has no matching damage-to-objects target.",
  },
  Ku49E979YEHlxZW6: {
    id: "Ku49E979YEHlxZW6",
    name: "Judgment: Justice",
    bucket: "situational",
    note: "Only applies while the shieldmarshal's currently active judgment (chosen and swappable as a swift action) is set to Justice; the other judgment types grant different, mutually exclusive bonuses.",
  },
  MvEkKLOdviN7uNJI: {
    id: "MvEkKLOdviN7uNJI",
    name: "Grapple Ship",
    bucket: "subsystem",
    note: "Ship-to-ship grappling mechanic resolved against a vessel's own Strength check, not a bonus on the pirate's own character sheet.",
  },
  QsDvIB5mfC5c9DKG: {
    id: "QsDvIB5mfC5c9DKG",
    name: "Danger Sense",
    bucket: "blocked",
    note: "'Danger Sense' also names the Rogue (Unchained)/Barbarian (Unchained) trap-sense variant (Reflex/AC/Perception bonuses vs. traps), a wholly different mechanic; a name-keyed patch for the shieldmarshal's initiative bonus would misapply to that entry too.",
  },
  RfI1XamDv8W2xaCB: {
    id: "RfI1XamDv8W2xaCB",
    name: "Sanguine Sacrifice",
    bucket: "situational",
    note: "Triggered only by using the painful purification ability, granting a scaling morale bonus that lasts 1 hour per use; resource- and trigger-gated.",
  },
  TfIhNvaOmjUVBUMi: {
    id: "TfIhNvaOmjUVBUMi",
    name: "Defensive Powers",
    bucket: "subsystem",
    note: "Parent 'gain a new defensive power every two levels, usable only in a defensive stance' framework; the only child power in this shard (Defensive Power: Smash) is separately catalogued and itself stance-gated.",
  },
  WScx0eyqD2Q5W9Zx: {
    id: "WScx0eyqD2Q5W9Zx",
    name: "Arcana: The Follower",
    bucket: "blocked",
    note: "Same Sidereal Arcana reachability defect as every arcanum (all twelve auto-listed at Stargazer level 1, no choice-tracking); the demon-specific immunity clause is also narrower than the vocabulary.",
  },
  mKu2EKf5CzQtyagr: {
    id: "mKu2EKf5CzQtyagr",
    name: "Apocalyptic Vow",
    bucket: "numeric",
    note: "Unconditional +3 bonus on saves against death effects (only the death half of the text is expressible; negative energy has no SAVE_CATEGORIES entry). See proposals-reachable5.json.",
  },
  nVwveeNV71Bg7YnY: {
    id: "nVwveeNV71Bg7YnY",
    name: "Studied Combat",
    bucket: "situational",
    note: "Move-action activation on a single studied target, lasting until a studied strike lands or the investigator's Intelligence modifier in rounds elapses; a classic activation-gated bonus.",
  },
  sA1CQYtItcIYUCuJ: {
    id: "sA1CQYtItcIYUCuJ",
    name: "Fogcraft",
    bucket: "subsystem",
    note: "Once-per-day ability to conjure a separate fog vessel with its own stat block (AC, Strength, capacity); not a bonus on the pirate's own character sheet.",
  },
  w94RfJoOeOglCrVU: {
    id: "w94RfJoOeOglCrVU",
    name: "Tempering Touch",
    bucket: "situational",
    note: "Triggered by healing an ally with a spell or class feature, and the resulting defensive bonus applies to that ally, not to the sacred sentinel's own sheet.",
  },
  wSDv38kqtw1AhDhC: {
    id: "wSDv38kqtw1AhDhC",
    name: "Judgment: Destruction",
    bucket: "situational",
    note: "Only applies while the shieldmarshal's currently active judgment is set to Destruction; mutually exclusive with the other judgment types.",
  },
  weJ9bU8SEUO0ok87: {
    id: "weJ9bU8SEUO0ok87",
    name: "Judgment: Lucky Dodge",
    bucket: "situational",
    note: "Only applies while the shieldmarshal's currently active judgment is set to Lucky Dodge; mutually exclusive with the other judgment types.",
  },
  wiNqDlELVgIdt4MS: {
    id: "wiNqDlELVgIdt4MS",
    name: "Gunhunter",
    bucket: "situational",
    note: "The Stealth and movement benefits only apply in urban terrain, a location state the static sheet cannot detect.",
  },
  "8qdAbOFRHVzYwb2h": {
    id: "8qdAbOFRHVzYwb2h",
    name: "Virtuous Rune: Humility",
    bucket: "situational",
    note: "Triggered only when an ally uses aid another on the runeguard, and requires expending a prepared spell or slot as an immediate action; resource- and trigger-gated.",
  },
  DZDOevpF9bXZlV4K: {
    id: "DZDOevpF9bXZlV4K",
    name: "Ancestral Weapon",
    bucket: "situational",
    note: "The extra weapon damage and Intimidate bonus only apply against giant, goblin, and orc subtype creatures, a favored-enemy-shaped scope with no modeled target, and require a specific ritual-designated weapon.",
  },
  NKTj2J2kMxUwPKkQ: {
    id: "NKTj2J2kMxUwPKkQ",
    name: "Virtuous Rune: Generosity",
    bucket: "situational",
    note: "Triggered only by using aid another and expending a prepared spell or slot as an immediate action, and the resulting bonus goes to the aided ally, not the runeguard.",
  },
  WeDWbYxCLwzK5lfz: {
    id: "WeDWbYxCLwzK5lfz",
    name: "Defensive Power: Smash",
    bucket: "situational",
    note: "The extra attack only applies while in a defensive stance, the same toggled-state gap as Defensive Stance itself.",
  },
  gotW1ETzGrrwVtk2: {
    id: "gotW1ETzGrrwVtk2",
    name: "Alchemy (INV)",
    bucket: "subsystem",
    note: "Grants the investigator's whole extract-preparation spellcasting subsystem; the embedded Craft (alchemy) bonus is also scoped to creating alchemical items, narrower than the whole skill.",
  },
  iyxcqRZc8HNtgMSA: {
    id: "iyxcqRZc8HNtgMSA",
    name: "Talmandor's Blessing",
    bucket: "numeric",
    note: "Unconditional +4 bonus on Perception checks (the Acrobatics half is scoped to jump checks only, and feather fall has no matching Change target). See proposals-reachable5.json.",
  },
  kP2ZUR0IYYuE3VYN: {
    id: "kP2ZUR0IYYuE3VYN",
    name: "Symbolic Weapon",
    bucket: "situational",
    note: "The attack/damage bonus only applies while wielding the sentinel's deity's favored weapon, an equipment state the static sheet cannot track.",
  },
  mbAS6gYfksKP0noW: {
    id: "mbAS6gYfksKP0noW",
    name: "Predictive Riposte",
    bucket: "situational",
    note: "Standard-action activation designating a single opponent; the AC bonus and counter-attack only apply against that designated target.",
  },
  oY2gnKODQav7fe0w: {
    id: "oY2gnKODQav7fe0w",
    name: "Street Sentinel",
    bucket: "situational",
    note: "The initiative and skill bonuses only apply while in an urban area, a location state the static sheet cannot detect.",
  },
  "prestige:shadowdancer:shadow-master": {
    id: "prestige:shadowdancer:shadow-master",
    name: "Shadow Master",
    bucket: "situational",
    note: "The DR and luck save bonus only apply while in an area of dim light, a lighting state the static sheet cannot detect.",
  },
  qhDs2AuUaAegMUUO: {
    id: "qhDs2AuUaAegMUUO",
    name: "Swarm Form",
    bucket: "subsystem",
    note: "Grants a temporary alternate swarm form with its own stat block (fly speed, immunities), not an ongoing bonus to the spherewalker's normal-form sheet.",
  },
  "0F3fra3luKV49r78": {
    id: "0F3fra3luKV49r78",
    name: "Angel of Eiseth",
    bucket: "numeric",
    note: "Unconditional fire resistance 30, telepathy 50 ft, see-in-darkness, and a 50-ft fly speed, all fixed once the sanguine angel reaches 10th level (the outsider type change itself is not modeled). See proposals-reachable5.json.",
  },
  A3QO3Z9rRKiyheCF: {
    id: "A3QO3Z9rRKiyheCF",
    name: "Damage Reduction",
    bucket: "blocked",
    note: "'Damage Reduction' also names Bloodrager/Barbarian's DR (+1 at 7th, +1 per 3 levels) and Pain Taster's DR (+1 at 2nd, +1 per 2 levels), each a different progression; a name-keyed patch cannot serve all three without wrong numbers for the others.",
  },
  O6hbHICweSxh0y7Z: {
    id: "O6hbHICweSxh0y7Z",
    name: "Heroic Speech",
    bucket: "situational",
    note: "Functions as bardic performance's inspire courage, gated on a rounds-per-day pool and requiring active performance; same activation shape as the bard ability it mirrors.",
  },
  PdtS1uCSjdQ9etSY: {
    id: "PdtS1uCSjdQ9etSY",
    name: "Fading",
    bucket: "situational",
    note: "Immediate-action activation, Constitution-modifier uses per day, triggered only by an incoming weapon attack or Reflex save; entirely trigger- and resource-gated.",
  },
  R7Byu97rL8jPeqaz: {
    id: "R7Byu97rL8jPeqaz",
    name: "Discern Lies",
    bucket: "subsystem",
    note: "Grants use of discern lies as a spell-like ability from a rounds-per-day pool; a subsystem grant, not a flat bonus. Several sibling class features share this exact name across other classes with the same shape.",
  },
  TewYQ3TQt5nbzZUG: {
    id: "TewYQ3TQt5nbzZUG",
    name: "Manifest Will",
    bucket: "situational",
    note: "Immediate-action activation substituting Wisdom for a chosen physical ability's modifier on a single roll, gated on a Charisma-plus-half-level use pool.",
  },
  dlZ6lutR7rC5dafO: {
    id: "dlZ6lutR7rC5dafO",
    name: "Strategic Protection",
    bucket: "situational",
    note: "Move-action aura; the CMD and stabilize bonuses apply to allies within range, not the sacred sentinel unconditionally, and only last until her next turn.",
  },
  oWEDOuSLfiScnyU3: {
    id: "oWEDOuSLfiScnyU3",
    name: "Pierce Deception",
    bucket: "subsystem",
    note: "Grants use of true seeing from a rounds-per-day pool; a subsystem grant, not a flat bonus.",
  },
  r4c0rB7XE9KGLisb: {
    id: "r4c0rB7XE9KGLisb",
    name: "Swift Shield Other",
    bucket: "subsystem",
    note: "Grants use of shield other as a quickened spell-like ability on an ally, gated on a Charisma-bonus use pool.",
  },
  "2PyGmB1R6ciYAaBb": {
    id: "2PyGmB1R6ciYAaBb",
    name: "Mystique of Ardad Lili (Ex and Sp)",
    bucket: "situational",
    note: "The Diplomacy/Intimidate bonus is scoped to targets of the sanguine angel's own creature type, a favored-enemy-shaped scope with no modeled target; the dominate person half is a once-per-day spell-like ability.",
  },
  "2rnVuPmVOKZpZ7dd": {
    id: "2rnVuPmVOKZpZ7dd",
    name: "Arcana: The Rider",
    bucket: "subsystem",
    note: "Grants phantom steed and sanctuary as spell-like effects while riding; a subsystem grant, not a flat bonus.",
  },
  "9jImL8ktlHUGcNoa": {
    id: "9jImL8ktlHUGcNoa",
    name: "Anonymity",
    bucket: "situational",
    note: "The Bluff/Disguise bonus only applies to checks made specifically to conceal one's identity, narrower than the whole skill.",
  },
  AKSeHYIPuy8e1Fq0: {
    id: "AKSeHYIPuy8e1Fq0",
    name: "Runes of Resistance",
    bucket: "situational",
    note: "Move-action activation, dismissible as a swift action, gated on a rounds-per-day pool; the spell resistance value only applies while active.",
  },
  EC3p8ctSreBlNBrS: {
    id: "EC3p8ctSreBlNBrS",
    name: "AC Bonus",
    bucket: "blocked",
    note: "'AC Bonus' also names Student of Perfection's dodge bonus, which has a different progression and is lost while wearing medium/heavy armor or carrying a medium/heavy load; a name-keyed patch cannot serve both without wrong numbers for one.",
  },
  EE0cYrzPcCFoZbuC: {
    id: "EE0cYrzPcCFoZbuC",
    name: "Forensic Thaumaturgy",
    bucket: "subsystem",
    note: "Grants detect magic at will plus an enhanced lingering-aura reading ability; a subsystem grant, not a flat bonus.",
  },
  F9RBv0eTNHdIg6pP: {
    id: "F9RBv0eTNHdIg6pP",
    name: "Arcana: The Stranger",
    bucket: "subsystem",
    note: "Grants cultural adaptation as a spell-like ability from a uses-per-day pool; a subsystem grant, not a flat bonus.",
  },
  JHMjcL8WElA3MopJ: {
    id: "JHMjcL8WElA3MopJ",
    name: "Efficient Sleep",
    bucket: "numeric",
    note: "Unconditional +4 sacred bonus to resist sleep effects (the reduced-sleep-requirement half is a rules exception with no Change target). See proposals-reachable5.json.",
  },
  L8eMZWSaDNW4fv64: {
    id: "L8eMZWSaDNW4fv64",
    name: "Righteous Leader",
    bucket: "subsystem",
    note: "Grants Leadership as a bonus feat plus modifiers to the unmodeled Leadership score; a subsystem grant, not a Change-shaped sheet number.",
  },
  TLFiwIpn9Aogn7QT: {
    id: "TLFiwIpn9Aogn7QT",
    name: "Deductive Examination",
    bucket: "subsystem",
    note: "Grants use of residual tracking as a spell-like ability three times per day; a subsystem grant, not a flat bonus.",
  },
  UfQ6HFpCWDPyQ9Kz: {
    id: "UfQ6HFpCWDPyQ9Kz",
    name: "Summon Mantis",
    bucket: "subsystem",
    note: "Once-per-day summon monster-equivalent spell-like ability; a subsystem grant, not a flat bonus.",
  },
  WCLjLkw2CREssenw: {
    id: "WCLjLkw2CREssenw",
    name: "Hematomancy",
    bucket: "subsystem",
    note: "Grants use of blood biography as a spell-like ability three times per day; a subsystem grant, not a flat bonus.",
  },
  X0cBoKchAsSVfgwJ: {
    id: "X0cBoKchAsSVfgwJ",
    name: "Eye for Detail",
    bucket: "blocked",
    note: "'Eye for Detail' also names Twilight Talon's forgery bonus and Sleepless Detective's free trap-Perception-check ability, both wholly different mechanics from the shieldmarshal's own Intelligence-plus-Wisdom Perception/Sense Motive stacking; a name-keyed patch cannot serve all three.",
  },
  Y1LZmoF3BpLMgUey: {
    id: "Y1LZmoF3BpLMgUey",
    name: "Student of Mysteries",
    bucket: "situational",
    note: "The Intelligence-check bonus only applies to checks made to learn new occult rituals, narrower than a general ability-check bonus.",
  },
  cREFsbYTS8hi7VaZ: {
    id: "cREFsbYTS8hi7VaZ",
    name: "Mantis Doom",
    bucket: "subsystem",
    note: "Grants use of creeping doom as a spell-like ability three times per day; a subsystem grant, not a flat bonus.",
  },
  fOyqwhx4vvA2PEG4: {
    id: "fOyqwhx4vvA2PEG4",
    name: "Bogstep",
    bucket: "situational",
    note: "The movement-cost reduction and Tumble bonus/penalty only apply in bog terrain, a location state the static sheet cannot detect.",
  },
  g4JPVAjmupFmF0E3: {
    id: "g4JPVAjmupFmF0E3",
    name: "Spirit Conduit",
    bucket: "subsystem",
    note: "Grants Augment Summoning-style bonuses to the summoned animus creature's own stat block, not the Rivethun emissary's own sheet.",
  },
  gHlXKXXFXQkgAa2B: {
    id: "gHlXKXXFXQkgAa2B",
    name: "Stalwart",
    bucket: "blocked",
    note: "The save bonus is scoped to divine spells specifically, a spellcasting-tradition distinction SAVE_CATEGORIES does not carry (matches this file's own Nonbeliever/Mistrust of Magic precedent); the name also collides with the Inquisitor/Skyseeker 'stalwart' reroll-and-avoid ability, a wholly different mechanic.",
  },
  gNIhgXDhQOnOqjwj: {
    id: "gNIhgXDhQOnOqjwj",
    name: "Gunmarshal",
    bucket: "situational",
    note: "The gunslinger-deeds grant is a subsystem, not a number; the Charisma-skill bonus is further scoped to the Grand Duchy of Alkenstar while displaying the shieldmarshal's badge, both a location and an equipment-display state.",
  },
  hP1d1doncPpYU6zQ: {
    id: "hP1d1doncPpYU6zQ",
    name: "Discipline: Driving Assault",
    bucket: "situational",
    note: "Requires declaring the -2 attack penalty during a full attack and only grants the bull rush bonus on a subsequent hit that round; fully activation-gated.",
  },
  iVSxsXGKJrPPX6ht: {
    id: "iVSxsXGKJrPPX6ht",
    name: "Arcana: The Thrush",
    bucket: "blocked",
    note: "Same Sidereal Arcana reachability defect as every arcanum: all twelve are auto-listed at Stargazer level 1 with no choice-tracking, so a name-keyed patch for this Diplomacy/Perform bonus would apply to every stargazer regardless of pick.",
  },
  l8MAdB7OvusCjbXY: {
    id: "l8MAdB7OvusCjbXY",
    name: "Enemy of Slavers",
    bucket: "situational",
    note: "Favored-enemy-shaped bonus scoped to slavers and slave owners specifically, a creature-category scope with no modeled target.",
  },
  "prestige:shadowdancer:uncanny-dodge": {
    id: "prestige:shadowdancer:uncanny-dodge",
    name: "Uncanny Dodge (Shadowdancer)",
    bucket: "subsystem",
    note: "Grants the uncanny dodge (or improved uncanny dodge, if already possessed) rules exception; not a Change-shaped bonus.",
  },
  r2kjS9fJTI9gbmlF: {
    id: "r2kjS9fJTI9gbmlF",
    name: "Follow Clues",
    bucket: "subsystem",
    note: "Duplicates the rogue talent of the same name (rogue-talents.ts), which attaches only a contextNote rather than a Change; mirrored here.",
  },
  r7GARd2nWqcsODuV: {
    id: "r7GARd2nWqcsODuV",
    name: "Natural Traps",
    bucket: "subsystem",
    note: "Grants Learn Ranger Trap as a bonus feat plus a chosen extraordinary trap, gated on a class-level-plus-Wisdom use pool; a subsystem grant.",
  },
  tgEObk0nFqZPZYFd: {
    id: "tgEObk0nFqZPZYFd",
    name: "Superior Aid",
    bucket: "situational",
    note: "The +4 (instead of +2) bonus only applies while performing the aid another action.",
  },
  wlfWioBaK9Ihu0uk: {
    id: "wlfWioBaK9Ihu0uk",
    name: "Longstrider",
    bucket: "subsystem",
    note: "Once-per-day use of longstrider as a spell-like ability; a subsystem grant, not a flat bonus.",
  },
  zFGzzj29uhZLSCB4: {
    id: "zFGzzj29uhZLSCB4",
    name: "Divine Quickness",
    bucket: "situational",
    note: "The initiative bonus only applies while carrying the sentinel's deity's favored weapon, an equipment state the static sheet cannot track.",
  },
};
