/**
 * Class-feature classification shard: wave assignment "reachable4" — features
 * granted through some `RefData.classes[*].features` list (base or prestige),
 * so a `CLASS_FEATURE_CHANGE_PATCHES` entry can reach them. Owner-assigned
 * worklist; `index.ts` documents the shard convention.
 */

import type { ClassFeatureClassificationEntry } from "./types.js";

export const CLASS_FEATURE_CLASSIFICATION_REACHABLE_4: Readonly<
  Record<string, ClassFeatureClassificationEntry>
> = {
  KmtDDLu690DySH1e: {
    id: "KmtDDLu690DySH1e",
    name: "Fervor",
    bucket: "situational",
    note: "Rounds-per-day activation (free action to enter or end); the attack/damage/DR/caster-level/speed benefits and the Charisma penalty only apply while the fervor is active.",
  },
  nAf2hU0pfOBrOSAr: {
    id: "nAf2hU0pfOBrOSAr",
    name: "Monitor Expression",
    bucket: "subsystem",
    note: "Player picks one of four demigod expressions, each granting a different activation-gated ability (save bonus, spiritsense, deflection AC, or freedom of movement spell-like ability); choice- and activation-dependent, not a flat number.",
  },
  awikzWDddpbaic29: {
    id: "awikzWDddpbaic29",
    name: "Pathfinder Training",
    bucket: "subsystem",
    note: "Umbrella choice feature: the agent picks specific trainings (wild empathy, sneak attack, trapfinding, etc.) as she levels. The vendored data lists every training as an automatic level-1 grant in Pathfinder Field Agent's features list, which is a vendoring artifact, not RAW; see the standalone Training: * entries for the same trap.",
  },
  D00WDZUSAheogWri: {
    id: "D00WDZUSAheogWri",
    name: "Advanced Mutagen",
    bucket: "subsystem",
    note: "Umbrella choice feature: the master chymist picks one advanced mutagen per slot from a long list. The vendored data lists every option (Burly, Dual Mind, Draconic Mutagen, etc.) as automatic level-1 grants in Master Chymist's features list, which would over-apply every sub-option to every master chymist if patched.",
  },
  "6L4ShtncIU6yBXOw": {
    id: "6L4ShtncIU6yBXOw",
    name: "Gigantic Steed",
    bucket: "blocked",
    note: "Modifies the mammoth rider's steed, an untracked mount not covered by the animal-companion model in companion.ts and not the character's own sheet; no character-facing target exists for the mount's size/Strength/Constitution/attack/AC changes.",
  },
  QyZuFZuT98jA78iq: {
    id: "QyZuFZuT98jA78iq",
    name: "Masochism",
    bucket: "situational",
    note: "Core benefit is a self-damage swift-action activation (attack/damage bonus scales with chosen self-inflicted damage); the +4 save bonus against pain effects also has no SAVE_CATEGORIES entry, since pain is not a modeled category.",
  },
  msenGlypfNllZQuX: {
    id: "msenGlypfNllZQuX",
    name: "Silent Soul",
    bucket: "numeric",
    note: "The +10 circumstance bonus on Stealth checks is unconditional at 10th level. Spell resistance 20 against mind-affecting effects is a separate subsystem grant this table can't express.",
  },
  yGtUHJT3P3DG61h9: {
    id: "yGtUHJT3P3DG61h9",
    name: "Vanth Wings",
    bucket: "numeric",
    note: "The 60-ft fly speed, cold resistance (10 + class level), and +5 circumstance Acrobatics bonus are all unconditional at 9th level. The concentration-check bonus has no matching target, since concentration isn't its own skill, and is left unexpressed.",
  },
  "2TsDfK0SKC8IGVx4": {
    id: "2TsDfK0SKC8IGVx4",
    name: "Smite Evil",
    bucket: "situational",
    note: "Once-per-day swift-action activation against a chosen target; the Charisma-to-attack, level-to-damage, DR bypass, and deflection AC all only apply while smite is active against that target.",
  },
  ciyImu4uU8FDRucB: {
    id: "ciyImu4uU8FDRucB",
    name: "Wayfinder Upgrade",
    bucket: "subsystem",
    note: "Umbrella choice feature: the agent picks one wayfinder upgrade per slot from a list (Daylight, Shielding, Silence, etc.), most of which are themselves per-day activated abilities; no single unconditional number to extract.",
  },
  gccTXY701Hlgsw2w: {
    id: "gccTXY701Hlgsw2w",
    name: "Ruthless",
    bucket: "situational",
    note: "Triggered only on a killing or downing blow (swift-action follow-up attack); the damage bonus equal to character level applies to that triggered attack only.",
  },
  "5q20EcI3V9MD2Vta": {
    id: "5q20EcI3V9MD2Vta",
    name: "Soul Stone",
    bucket: "numeric",
    note: "The +2 save bonus against death effects and mind-affecting effects is unconditional. The negative-level clause has no SAVE_CATEGORIES entry, and the 3/day enlarge-person activation is a separate subsystem grant.",
  },
  "9N5fuIg0zB8SrwRh": {
    id: "9N5fuIg0zB8SrwRh",
    name: "Path of Darkness - Path of Light",
    bucket: "subsystem",
    note: "Player picks a path (darkness or light) that waives one alignment trait for alignment-based magical effects, a rules exception with no number; the accompanying Diplomacy bonus is scoped to creatures of a specific alignment subtype, narrower than the flat skill target.",
  },
  "9ewVQ2Nd8oySPajt": {
    id: "9ewVQ2Nd8oySPajt",
    name: "Arena Weapon Expertise",
    bucket: "situational",
    note: "Bonus applies only while wielding a weapon with the performance quality, a weapon-equipped state the static sheet doesn't track.",
  },
  AMSzoMIYIwbh1aLg: {
    id: "AMSzoMIYIwbh1aLg",
    name: "Move with the Crowd",
    bucket: "situational",
    note: "The Acrobatics bonus is scoped to a specific use (avoiding attacks of opportunity or moving through an enemy's square at above half speed), narrower than a flat skill.acr target, which would over-apply to every Acrobatics check.",
  },
  U23BBZ0CW4t36X91: {
    id: "U23BBZ0CW4t36X91",
    name: "Dilettante Studies",
    bucket: "subsystem",
    note: "Umbrella choice feature: the noble scion picks two dilettante studies from four options. The vendored data lists all four (Performer/Scholar/Scoundrel/Warrior) as automatic level-1 grants in Noble Scion's features list, a vendoring artifact that would over-apply every option if patched.",
  },
  bNMKUlTvjAs7m4VC: {
    id: "bNMKUlTvjAs7m4VC",
    name: "Mistrust of Magic",
    bucket: "blocked",
    note: "Scoped to a spellcasting tradition (arcane/divine/psychic); class-feature-effects.ts's precedent list names Mistrust of Magic directly, since SAVE_CATEGORIES has no tradition axis.",
  },
  eOfQ8noTHhx9nGI2: {
    id: "eOfQ8noTHhx9nGI2",
    name: "Auspicious Display",
    bucket: "situational",
    note: "Conditioned on wearing 1,000+ gp of decorative jewelry (the threshold scales with level), an equipment-value state the static sheet doesn't track.",
  },
  ebzvByLwDGVfXgbF: {
    id: "ebzvByLwDGVfXgbF",
    name: "Training: Know Thy Enemy",
    bucket: "subsystem",
    note: "One of the Pathfinder Field Agent's chosen trainings (see Pathfinder Training); also scoped to a player-picked creature type, so even standalone it wouldn't be a flat Knowledge bonus.",
  },
  gPtkhDYMA008bdTr: {
    id: "gPtkhDYMA008bdTr",
    name: "Dilettante Warrior",
    bucket: "subsystem",
    note: "One of the four Dilettante Studies choices (see that entry). The +1 attack/damage bonus is clean on its own, but the vendored data lists it as an automatic level-1 grant alongside its three siblings, so patching it would apply to every noble scion regardless of which study was chosen.",
  },
  lERtmvBNYcOq7bxB: {
    id: "lERtmvBNYcOq7bxB",
    name: "Summon Sphinx",
    bucket: "subsystem",
    note: "Primarily grants a once-per-day (later greater) planar-ally-style summon; the +4 Diplomacy bonus is scoped to negotiating with sphinxes specifically, too narrow for the flat skill target.",
  },
  mznovwcbTMsYfx2u: {
    id: "mznovwcbTMsYfx2u",
    name: "Sigil Master",
    bucket: "blocked",
    note: "Save bonus against writing-based magical traps; class-feature-effects.ts's precedent list names Sigil Master directly, since SAVE_CATEGORIES has no axis for traps.",
  },
  "prestige:loremaster:greater-lore": {
    id: "prestige:loremaster:greater-lore",
    name: "Greater Lore",
    bucket: "blocked",
    note: "The +10 Spellcraft bonus is scoped to identifying a magic item's properties specifically, not general Spellcraft; promoting it would over-apply to crafting and other Spellcraft checks the ability doesn't cover.",
  },
  "prestige:pathfinder-chronicler:pathfinding": {
    id: "prestige:pathfinder-chronicler:pathfinding",
    name: "Pathfinding",
    bucket: "blocked",
    note: "The Survival bonus is scoped to avoiding getting lost specifically, not general Survival, and the Intelligence-check clause is for escaping a maze spell, which isn't a skill at all.",
  },
  "4cNd8JT1ObquZuj9": {
    id: "4cNd8JT1ObquZuj9",
    name: "Voice of Law",
    bucket: "situational",
    note: "Standard-action Intimidate activation against worshipers of a chosen deity within range; the concentration penalty it imposes lands on affected enemies, not the enforcer.",
  },
  hoQt3MeCK99cFfhO: {
    id: "hoQt3MeCK99cFfhO",
    name: "Dirty Fighting",
    bucket: "numeric",
    note: "The +2 bonus on all combat maneuver checks is unconditional. The improvised-weapon proficiency waiver and the crit-table swap option are rules exceptions this table can't express.",
  },
  pqWmGx4Q29QZvoic: {
    id: "pqWmGx4Q29QZvoic",
    name: "Decree of Law",
    bucket: "situational",
    note: "The attack/damage bonus only applies against creatures currently affected by the enforcer's own voice of law activation, an enemy state the sheet can't detect unconditionally.",
  },
  "prestige:mystic-theurge:spell-synthesis": {
    id: "prestige:mystic-theurge:spell-synthesis",
    name: "Spell Synthesis",
    bucket: "situational",
    note: "Once-per-day activation (a single action casting two spells at once); the save penalty and spell-resistance-check bonus only apply to that triggered cast.",
  },
  xPzMXlWdYXVrkWnG: {
    id: "xPzMXlWdYXVrkWnG",
    name: "Grandmaster of Disguise",
    bucket: "numeric",
    note: "The +2 circumstance bonus on Disguise checks is unconditional at 9th level. The non-stacking note with an actual disguise kit is not relevant to the sheet, since no kit bonus is modeled.",
  },
  "1GzwbdUfwooiRKjW": {
    id: "1GzwbdUfwooiRKjW",
    name: "Discern Lies",
    bucket: "situational",
    note: "Rounds-per-day activation (immediate action) granting discern lies; only active for the rounds spent.",
  },
  dfuszKVFrbP8vsrS: {
    id: "dfuszKVFrbP8vsrS",
    name: "Training: Skill Specialization",
    bucket: "subsystem",
    note: "One of the Pathfinder Field Agent's chosen trainings (see Pathfinder Training); the bonus applies to a player-picked skill, so even standalone it needs a choice the static table can't encode.",
  },
  etOoJgoeaBRenCir: {
    id: "etOoJgoeaBRenCir",
    name: "Charmed Life",
    bucket: "situational",
    note: "Limited-use (starting 3/day) immediate-action activation before a save roll; the Charisma-modifier bonus only applies when spent.",
  },
  wdi1pSAXbTqBMeGx: {
    id: "wdi1pSAXbTqBMeGx",
    name: "Fortified Flesh",
    bucket: "numeric",
    note: "The unbypassable damage reduction (1 at 3rd level, 2 at 5th, 3 at 8th) is unconditional. The fortification-percent critical-hit/sneak-attack immunity has no matching engine target (the same gap noted for fortification-style item effects elsewhere), and the disease immunity is a separate unmodeled boolean.",
  },
  "0fTqdeF3IPAGg7oQ": {
    id: "0fTqdeF3IPAGg7oQ",
    name: "Mystic Harmony",
    bucket: "situational",
    note: "AC bonus only applies while in the warden's favored terrain, and is lost while immobilized or helpless.",
  },
  "3BofvEJKeLJa2bxJ": {
    id: "3BofvEJKeLJa2bxJ",
    name: "Second Ritual",
    bucket: "subsystem",
    note: "Primarily adds spells to the priest's spell list, which isn't modeled; the Bluff bonus is conditioned on using False Casting to cast a specific spell level.",
  },
  "9gJwJ0KbbNi49mMl": {
    id: "9gJwJ0KbbNi49mMl",
    name: "Disciple of Insight",
    bucket: "subsystem",
    note: "One of the Pain Taster's seven ritual routines (Disciple of *). The vendored data lists all seven as automatic level-1 grants, a vendoring artifact, and each is individually a 1-hour ritual granting a 24-hour temporary bonus, not an always-on number.",
  },
  AyxrTS91cPId2UtF: {
    id: "AyxrTS91cPId2UtF",
    name: "Soultended",
    bucket: "numeric",
    note: "The +2 Will save bonus is unconditional. The resurrection-DC and afterlife-transformation flavor text has no engine hook.",
  },
  BGd5i33PQ1AiBBMK: {
    id: "BGd5i33PQ1AiBBMK",
    name: "Nonbeliever",
    bucket: "blocked",
    note: "Scoped to divine spellcasting specifically; class-feature-effects.ts's precedent list names Nonbeliever directly, since SAVE_CATEGORIES has no tradition axis.",
  },
  D23ZMeJOnnwYT53k: {
    id: "D23ZMeJOnnwYT53k",
    name: "Planar Contacts",
    bucket: "situational",
    note: "The cost discount and Charisma-check bonus only apply while negotiating with a planar ally or planar binding target, a narrow interaction context.",
  },
  EEpEzEpl4s3YKCB4: {
    id: "EEpEzEpl4s3YKCB4",
    name: "Disciple of Torment",
    bucket: "subsystem",
    note: "One of the Pain Taster's seven ritual routines (see Disciple of Insight); same choice/ritual-duration trap.",
  },
  EN32EMpk9zwreK4A: {
    id: "EN32EMpk9zwreK4A",
    name: "Quick Change",
    bucket: "situational",
    note: "Reduces a Disguise-check penalty only when using the specific quick-change action (2d4 rounds instead of the normal time); not a bonus to ordinary Disguise checks.",
  },
  GlEugbBJcSQNWJ37: {
    id: "GlEugbBJcSQNWJ37",
    name: "Morrigna Wrappings",
    bucket: "subsystem",
    note: "Primarily an item-enchantment mechanic (assign whip properties to a designated item); the natural armor bonus depends on possessing that designated item, a state the sheet doesn't track.",
  },
  GzU6NwRwFMtMWaex: {
    id: "GzU6NwRwFMtMWaex",
    name: "Crusader",
    bucket: "blocked",
    note: "Scoped to chaotic evil outsiders specifically; class-feature-effects.ts's precedent list names Crusader directly as an example with no vocabulary axis for a creature-type-scoped bonus.",
  },
  HQSJqAuGMUFB0Lyv: {
    id: "HQSJqAuGMUFB0Lyv",
    name: "Lasting Goodness",
    bucket: "blocked",
    note: "Extends the duration of good-descriptor spells; the engine has no Change target for spell duration at all, so there's nothing to wire regardless of the descriptor scoping.",
  },
  J1QHd5YQmMKzcDFI: {
    id: "J1QHd5YQmMKzcDFI",
    name: "Glib Lie",
    bucket: "subsystem",
    note: "Sets a DC other creatures must beat with a caster level check to detect the spy's lies; not a bonus to the spy's own rolls, so no character-facing number.",
  },
  KQXe3ofgN2gcIZUs: {
    id: "KQXe3ofgN2gcIZUs",
    name: "Valiant Devotion",
    bucket: "blocked",
    note: "Bonus applies to the mammoth rider's steed's saves, not the rider's own; matches the ally/mount-only precedent (untracked mount, no character target).",
  },
  LGaYfwlBmmcL0C3T: {
    id: "LGaYfwlBmmcL0C3T",
    name: "Superficial Knowledge",
    bucket: "situational",
    note: "Untrained-Knowledge/Profession access and the half-level bonus only apply to checks about the spy's chosen cover identity, a session-specific detail the sheet doesn't track.",
  },
  LPAbzynGlOwYcGx7: {
    id: "LPAbzynGlOwYcGx7",
    name: "Panache",
    bucket: "subsystem",
    note: "A resource-pool mechanic (points gained and spent on deeds), not a Change-shaped stat bonus.",
  },
  LU9yx9bMZskEmMiL: {
    id: "LU9yx9bMZskEmMiL",
    name: "Disciple of Acuity",
    bucket: "subsystem",
    note: "One of the Pain Taster's seven ritual routines (see Disciple of Insight).",
  },
  N7aX9aHXhPbdlfOJ: {
    id: "N7aX9aHXhPbdlfOJ",
    name: "Dirge of Misfortune",
    bucket: "situational",
    note: "Once-per-round immediate-action activation while performing, forcing an enemy reroll; only applies to that triggered reroll.",
  },
  OnpskzWyjYsZCc0S: {
    id: "OnpskzWyjYsZCc0S",
    name: "Pain Mastery",
    bucket: "subsystem",
    note: "Lets the pain taster combine two ritual routines into one; a rules exception on the choice mechanic, not its own number.",
  },
  SY96O48qbFnXat9N: {
    id: "SY96O48qbFnXat9N",
    name: "Plant Speech",
    bucket: "subsystem",
    note: "Grants an at-will (in favored terrain) or once-per-day spell-like ability; no Change-shaped number.",
  },
  SqnjRLbrfDk4DyS7: {
    id: "SqnjRLbrfDk4DyS7",
    name: "Damnation - Redemption",
    bucket: "subsystem",
    note: "Grants a planar cohort via a Leadership-like mechanic and a Leadership-score bonus; Leadership isn't a tracked stat in this engine.",
  },
  T8jF1LURViyIo56i: {
    id: "T8jF1LURViyIo56i",
    name: "Companion Soul",
    bucket: "blocked",
    note: "The Will-save bonus and the scrying/revival abilities belong to the warden's animal companion, not the warden; class-feature-effects.ts's precedent list names Companion Soul directly.",
  },
  TVNMlZUmKtoMPkRd: {
    id: "TVNMlZUmKtoMPkRd",
    name: "Aristocratic Erudition",
    bucket: "numeric",
    note: "The half-class-level bonus on Diplomacy, Knowledge (local), and Knowledge (nobility) is unconditional at 3rd level. The DC reduction for others' checks about the scion has no self-facing target.",
  },
  TVUC6bsJcsJ10UkR: {
    id: "TVUC6bsJcsJ10UkR",
    name: "Advanced Mutagen: Dual Mind",
    bucket: "subsystem",
    note: "One of the Master Chymist's Advanced Mutagen choices (see Advanced Mutagen). The +2 Will bonus is clean on its own, but the vendored data lists every advanced-mutagen option as an automatic level-1 grant alongside its siblings, so patching it would apply to every master chymist regardless of choice.",
  },
  TxCpMYXkcluFttnz: {
    id: "TxCpMYXkcluFttnz",
    name: "Stability",
    bucket: "situational",
    note: "The +4 CMD bonus only applies against bull rush or trip attempts while standing on the ground, narrower than the flat cmd target, which would over-apply to every combat maneuver.",
  },
  UCy6y1M5q7O241Tb: {
    id: "UCy6y1M5q7O241Tb",
    name: "Disciple of Vigor",
    bucket: "subsystem",
    note: "One of the Pain Taster's seven ritual routines (see Disciple of Insight).",
  },
  WHU1f5mIMyVPDUXe: {
    id: "WHU1f5mIMyVPDUXe",
    name: "Training: Deft Defender",
    bucket: "subsystem",
    note: "One of the Pathfinder Field Agent's chosen trainings; also only applies after a successful aid-another action, an action-triggered state.",
  },
  WhE4j0Jc82npdMCP: {
    id: "WhE4j0Jc82npdMCP",
    name: "Lay on Hands",
    bucket: "situational",
    note: "A per-day resource pool spent as a standard or swift action to heal or harm undead; the healing amount only applies when the ability is activated.",
  },
  Wl2U58dKZvo9YlFA: {
    id: "Wl2U58dKZvo9YlFA",
    name: "Enduring Rage",
    bucket: "situational",
    note: "Free-action activation that trades a spell slot to extend rage duration; only applies when spent.",
  },
  g7dOocadCrEgbO2F: {
    id: "g7dOocadCrEgbO2F",
    name: "Aura of Good",
    bucket: "subsystem",
    note: "Sets the Magaambyan arcanist's detect-good aura strength to her class level; not a bonus to any of her own rolls or defenses, so no Change target applies.",
  },
  gsBI2aOv9G2YgRKX: {
    id: "gsBI2aOv9G2YgRKX",
    name: "Iconoclast",
    bucket: "situational",
    note: "The sunder-combat-maneuver bonus is scoped to divine paraphernalia and magic items specifically, narrower than a flat cmb target.",
  },
  iOYvcmxnuOA5h5H8: {
    id: "iOYvcmxnuOA5h5H8",
    name: "Righteous Contravention",
    bucket: "blocked",
    note: "Scoped to overcoming the spell resistance of evil creatures/objects and dispelling evil-sourced magic, a source-property scope the vocabulary has no axis for, matching class-feature-effects.ts's precedent pattern for this kind of scoping.",
  },
  iu1bWa1gesZkMOEL: {
    id: "iu1bWa1gesZkMOEL",
    name: "Animal Speech",
    bucket: "subsystem",
    note: "Grants an at-will (in favored terrain) or once-per-day spell-like ability; no Change-shaped number.",
  },
  kBTSp8Q0cTjvAjNa: {
    id: "kBTSp8Q0cTjvAjNa",
    name: "Disciple of Flexibility",
    bucket: "subsystem",
    note: "One of the Pain Taster's seven ritual routines (see Disciple of Insight).",
  },
  mDLVSAfxmo0KekY0: {
    id: "mDLVSAfxmo0KekY0",
    name: "Colossus Hunter",
    bucket: "situational",
    note: "The attack/damage bonus is scoped to the target's size category (Large/Huge versus Gargantuan/Colossal), an enemy state the static sheet can't detect without over-applying.",
  },
  mcOTEtvfbuYaDnxx: {
    id: "mcOTEtvfbuYaDnxx",
    name: "Third Ritual",
    bucket: "subsystem",
    note: "Primarily adds spells to the priest's spell list, which isn't modeled; the Bluff bonus is conditioned on using False Casting to cast a specific spell level (see Second Ritual).",
  },
  nzqkSBc6tvAqG8o2: {
    id: "nzqkSBc6tvAqG8o2",
    name: "Aura of Good",
    bucket: "subsystem",
    note: "Sets the paladin's detect-good aura strength to her paladin level; not a bonus to any of her own rolls or defenses, so no Change target applies.",
  },
  oI019H6rZvmsRMts: {
    id: "oI019H6rZvmsRMts",
    name: "Confiscate",
    bucket: "situational",
    note: "The disarm/steal combat-maneuver bonus is scoped to divine paraphernalia and magic items specifically, narrower than a flat cmb target.",
  },
  oxrtX2VJ7Kk2XaDD: {
    id: "oxrtX2VJ7Kk2XaDD",
    name: "Advanced Mutagen: Burly",
    bucket: "subsystem",
    note: "One of the Master Chymist's Advanced Mutagen choices (see Advanced Mutagen: Dual Mind); same automatic-grant-list trap.",
  },
  "prestige:pathfinder-chronicler:improved-aid": {
    id: "prestige:pathfinder-chronicler:improved-aid",
    name: "Improved Aid",
    bucket: "situational",
    note: "Only changes the bonus granted by a successful aid-another action; not a standalone number outside that action.",
  },
  qqRv6BA2sfcZA0pT: {
    id: "qqRv6BA2sfcZA0pT",
    name: "Glorious Aura",
    bucket: "situational",
    note: "Rounds-per-day activation, granting a Charisma bonus and fear aura only while shrouded; not always-on.",
  },
  rgb6nobTmD6hMrsZ: {
    id: "rgb6nobTmD6hMrsZ",
    name: "Inspiring Poise",
    bucket: "situational",
    note: "The competence bonus only applies while maintaining the Lion Blade's performance, and is to a player-chosen skill.",
  },
  rocL3E7pHuBbUHTZ: {
    id: "rocL3E7pHuBbUHTZ",
    name: "Flag of Convenience",
    bucket: "numeric",
    note: "The +2 bonus on all Bluff and Disguise checks is unconditional. The Linguistics-forgery bonus is narrower (checks made to create forgeries specifically), and the Leadership-related clauses aren't modeled.",
  },
  woNYqzlTSHOo5Sgo: {
    id: "woNYqzlTSHOo5Sgo",
    name: "Ironpaw",
    bucket: "blocked",
    note: "Grants damage reduction to the warden's animal companion and summoned creatures, not the warden herself; matches the ally/companion-only precedent, and this table's patch route only feeds the granting character's own sheet, not companion.ts's separate computation.",
  },
  y20pzrzm7hDwvwUt: {
    id: "y20pzrzm7hDwvwUt",
    name: "Intoned Recollection",
    bucket: "situational",
    note: "Uses-per-day (Intelligence modifier) ritual activation to prepare a spell into an open slot; only applies when spent.",
  },
  yZD1LIn8HusOZ4rq: {
    id: "yZD1LIn8HusOZ4rq",
    name: "Disciple of Spirit",
    bucket: "subsystem",
    note: "One of the Pain Taster's seven ritual routines (see Disciple of Insight).",
  },
};
