/**
 * Class-feature classification shard: granted powers outside every
 * `RefData.classes[*].features` list, covering wizard school powers,
 * druid-domain powers, inquisition granted powers, and warpriest blessing
 * powers. No
 * patch hook reaches any of these; a real unconditional number buckets
 * `blocked` with a note naming the unrouted path (see
 * `class-feature-effects.ts`'s header).
 */

import type { ClassFeatureClassificationEntry } from "./types.js";

export const CLASS_FEATURE_CLASSIFICATION_UNROUTED_GRANTED: Readonly<
  Record<string, ClassFeatureClassificationEntry>
> = {
  "druid-domain:vulture:death-s-companion": {
    id: "druid-domain:vulture:death-s-companion",
    name: "Death's Companion",
    bucket: "situational",
    note: "Immediate-action save bonus with a per-day use limit and a round-limited duration equal to druid level; not always-on.",
  },
  dcCZW51UewXFLLGo: {
    id: "dcCZW51UewXFLLGo",
    name: "Bolster",
    bucket: "subsystem",
    note: "Standard-action touch effect that buffs an undead creature the caster touches, not the caster's own sheet; no Change lands on self.",
  },
  JR0T67kfvoS5RQ9w: {
    id: "JR0T67kfvoS5RQ9w",
    name: "Wave",
    bucket: "subsystem",
    note: "Creates a moving wave that knocks foes prone or carries them via an opposed caster-level check; a combat effect, not a stat bonus.",
  },
  Lz9i4zNAH50umw3s: {
    id: "Lz9i4zNAH50umw3s",
    name: "Shape Emotions",
    bucket: "situational",
    note: "Activated 30-foot aura with a rounds-per-day budget and a caster-chosen mode (ward self and allies, or penalize enemies); no unconditional number.",
  },
  ROJkE2g2kWfhy6TI: {
    id: "ROJkE2g2kWfhy6TI",
    name: "Aura of Prescience",
    bucket: "subsystem",
    note: "Activated aura granting allies (not clearly the caster) an insight bonus; a castable ability rather than a bonus landing on the caster's own sheet.",
  },
  "inquisition-power:illumination:aura-of-enlightenment": {
    id: "inquisition-power:illumination:aura-of-enlightenment",
    name: "Aura of Enlightenment",
    bucket: "subsystem",
    note: "Activated light aura that grants a skill bonus to allies in range, not the inquisitor casting it.",
  },
  vQ6i4zS5T7z1UNOM: {
    id: "vQ6i4zS5T7z1UNOM",
    name: "Foretell",
    bucket: "situational",
    note: "Activated aura, rounds-per-day budget, explicitly includes 'you and your allies' when aiding; scoped to an activation the static sheet cannot represent as always-on.",
  },
  EzZ8XZHjMCBwaL5o: {
    id: "EzZ8XZHjMCBwaL5o",
    name: "Assume Control",
    bucket: "subsystem",
    note: "An opposed caster-level check to seize a summoned creature; the mechanic is a contest, not a sheet number.",
  },
  "blessing-power:godclaw:major": {
    id: "blessing-power:godclaw:major",
    name: "Tactical Readiness",
    bucket: "subsystem",
    note: "Grants nearby allies free actions and a temporary dodge bonus; the warpriest is not the target of the bonus.",
  },
  "druid-domain:jungle:brachiation": {
    id: "druid-domain:jungle:brachiation",
    name: "Brachiation",
    bucket: "situational",
    note: "Free-action climb speed and Acrobatics bonus limited to a rounds-per-day budget, not a permanent stat.",
  },
  "druid-domain:plane-of-water:aquatic-veil": {
    id: "druid-domain:plane-of-water:aquatic-veil",
    name: "Aquatic Veil",
    bucket: "situational",
    note: "Standard-action activation, duration capped at Wisdom-modifier rounds, and a per-day use limit gate the Swim bonus.",
  },
  "75Y2PY8Uha3o0fHE": {
    id: "75Y2PY8Uha3o0fHE",
    name: "Aura of Despair",
    bucket: "subsystem",
    note: "Activated aura that penalizes enemies within range; the bonus (a penalty) never lands on the caster's sheet.",
  },
  "druid-domain:plane-of-air:aerial-agility": {
    id: "druid-domain:plane-of-air:aerial-agility",
    name: "Aerial Agility",
    bucket: "situational",
    note: "Free-action activation with a Wisdom-modifier round cap and a per-day use limit around Fly/Acrobatics.",
  },
  "druid-domain:serpent:slither": {
    id: "druid-domain:serpent:slither",
    name: "Slither",
    bucket: "situational",
    note: "Free-action, 1-round duration, per-day use limit around a dodge/CMB bonus while squeezing through terrain.",
  },
  "inquisition-power:reformation:awaken-discontent": {
    id: "inquisition-power:reformation:awaken-discontent",
    name: "Awaken Discontent",
    bucket: "subsystem",
    note: "A charm-person-equivalent spell-like effect cast on a target; no bonus to the inquisitor's own sheet.",
  },
  "inquisition-power:sedition:undermine-authority": {
    id: "inquisition-power:sedition:undermine-authority",
    name: "Undermine Authority",
    bucket: "subsystem",
    note: "A social/mind-affecting effect used against a designated target's attitude; not a self-facing modifier.",
  },
  "5JrtpLs5AJZ5NI40": {
    id: "5JrtpLs5AJZ5NI40",
    name: "Life Sight",
    bucket: "subsystem",
    note: "Grants blindsight (a sense, not a Change-shaped bonus), gated to a rounds-per-day budget.",
  },
  PmO50ReytvNYsuFW: {
    id: "PmO50ReytvNYsuFW",
    name: "Fire Supremacy",
    bucket: "blocked",
    note: "The base fire resistance (5, then 10 at 10th, immunity at 20th) is unconditional and self-targeted, a real number this domain/school path has no patch hook to carry.",
  },
  "blessing-power:curse:major": {
    id: "blessing-power:curse:major",
    name: "Retributive Curse",
    bucket: "subsystem",
    note: "A triggered curse inflicted on an attacker who crits or sneak-attacks the warpriest; the effect lands on the enemy, not the caster's sheet.",
  },
  "blessing-power:curse:minor": {
    id: "blessing-power:curse:minor",
    name: "Hexing Attack",
    bucket: "subsystem",
    note: "A weapon-touch curse that debuffs whatever it strikes; targets an enemy, not the caster.",
  },
  "blessing-power:death:minor": {
    id: "blessing-power:death:minor",
    name: "From the Grave",
    bucket: "situational",
    note: "Activated for 1 minute; Disguise/Intimidate and save bonuses only apply while the ability is active, not unconditionally.",
  },
  "blessing-power:destruction:major": {
    id: "blessing-power:destruction:major",
    name: "Heart of Carnage",
    bucket: "subsystem",
    note: "A touch buff the warpriest grants to an ally; the crit-confirm bonus never applies to the warpriest's own sheet.",
  },
  "blessing-power:nobility:minor": {
    id: "blessing-power:nobility:minor",
    name: "Inspiring Word",
    bucket: "subsystem",
    note: "A ranged touch-equivalent buff spoken to another creature; ally-directed, not a self bonus.",
  },
  "blessing-power:protection:minor": {
    id: "blessing-power:protection:minor",
    name: "Increased Defense",
    bucket: "situational",
    note: "Activated for 1 minute with a level-scaled bonus; not an always-on save/AC bonus.",
  },
  "blessing-power:war:major": {
    id: "blessing-power:war:major",
    name: "Battle Lust",
    bucket: "subsystem",
    note: "A touch buff granted to an ally's weapon attacks; the bonuses apply to the ally, not the warpriest.",
  },
  "blessing-power:war:minor": {
    id: "blessing-power:war:minor",
    name: "War Mind",
    bucket: "subsystem",
    note: "A touch buff granted to an ally, who then picks one of four bonuses each round; ally-directed and choice-dependent.",
  },
  "druid-domain:mountain:foothold": {
    id: "druid-domain:mountain:foothold",
    name: "Foothold",
    bucket: "subsystem",
    note: "Alters a stone surface's terrain properties (difficult terrain or a Climb bonus for whoever crosses it); not a bonus to the druid's own sheet.",
  },
  "druid-domain:mountain:thin-air": {
    id: "druid-domain:mountain:thin-air",
    name: "Thin Air",
    bucket: "subsystem",
    note: "An activated aura that fatigues and ability-damages enemies standing in it; a debuff on foes, not a bonus for the druid.",
  },
  "druid-domain:plane-of-water:hydraulic-crush": {
    id: "druid-domain:plane-of-water:hydraulic-crush",
    name: "Hydraulic Crush",
    bucket: "subsystem",
    note: "An area damage/knockdown attack (or alternatively a familiar grant); no Change-shaped bonus to the druid's own sheet.",
  },
  "inquisition-power:execution:chosen-victim": {
    id: "inquisition-power:execution:chosen-victim",
    name: "Chosen Victim",
    bucket: "situational",
    note: "A real skill bonus, but scoped to whichever creature is designated as the chosen victim, once per day; not a general bonus.",
  },
  "inquisition-power:heresy:word-of-anathema": {
    id: "inquisition-power:heresy:word-of-anathema",
    name: "Word of Anathema",
    bucket: "subsystem",
    note: "A bestow-curse-equivalent spell-like effect cast on an enemy; not a bonus to the inquisitor.",
  },
  "inquisition-power:possession:self-control": {
    id: "inquisition-power:possession:self-control",
    name: "Self-Control",
    bucket: "blocked",
    note: "An unconditional +2 competence bonus on saves against charm/compulsion effects; charm and compulsion are valid save categories, but this granted-power path has no patch hook.",
  },
  "inquisition-power:restoration:cleanse-impunity": {
    id: "inquisition-power:restoration:cleanse-impunity",
    name: "Cleanse Impunity",
    bucket: "blocked",
    note: "A passive bonus to caster level checks scoped to a player-chosen alignment axis; caster-level-check bonuses have no expressible engine target, and the alignment choice adds ambiguity on top of the missing route.",
  },
  khGQDuyL6TKASqYb: {
    id: "khGQDuyL6TKASqYb",
    name: "Receptive Vibrations",
    bucket: "blocked",
    note: "The Perception bonus is unconditional but scoped narrowly to 'avoid being surprised' rather than the general Perception skill; applying it broadly would over-apply, and the flat-footed immunity clause is a rules exception with no Change target either.",
  },
  qIFUwyCjea79rUri: {
    id: "qIFUwyCjea79rUri",
    name: "Protective Ward",
    bucket: "situational",
    note: "Standard-action activation, Intelligence-modifier round duration, and a per-day use limit gate the deflection bonus.",
  },
  tJCegZfiuMpDkVEd: {
    id: "tJCegZfiuMpDkVEd",
    name: "Battleshaping",
    bucket: "subsystem",
    note: "Grows a temporary natural weapon; grants a new attack option rather than a bonus to an existing stat.",
  },
  u7r3RkiMNAhv9I2d: {
    id: "u7r3RkiMNAhv9I2d",
    name: "Augment",
    bucket: "situational",
    note: "Standard-action touch, level-scaled bonus, and a rounds/uses-per-day cap gate the ability-score or natural-armor bonus.",
  },
  "blessing-power:air:major": {
    id: "blessing-power:air:major",
    name: "Soaring Assault",
    bucket: "subsystem",
    note: "A touch buff granting an ally flight for 1 minute; the fly speed and Fly bonus apply to the ally, not the warpriest.",
  },
  "blessing-power:community:major": {
    id: "blessing-power:community:major",
    name: "Fight as One",
    bucket: "subsystem",
    note: "An activated aura that buffs allies' attack rolls when the warpriest lands a hit; the bonus lands on allies, not the warpriest.",
  },
  "blessing-power:knowledge:major": {
    id: "blessing-power:knowledge:major",
    name: "Monster Lore",
    bucket: "situational",
    note: "Activated swift action after a successful Knowledge check, 1-minute duration, scoped to a single identified creature; not unconditional.",
  },
  "druid-domain:frog:sticky-strike": {
    id: "druid-domain:frog:sticky-strike",
    name: "Sticky Strike",
    bucket: "situational",
    note: "A real bonus to one specific pull-maneuver combat check, gated behind a standard-action activation and a per-day use limit.",
  },
  "druid-domain:panther:hunter-s-senses": {
    id: "druid-domain:panther:hunter-s-senses",
    name: "Hunter's Senses",
    bucket: "subsystem",
    note: "Grants scent and upgrades vision (low-light or darkvision), a sense grant rather than a Change-shaped bonus, gated to a minutes-per-day budget.",
  },
  "druid-domain:plane-of-fire:fire-hardened": {
    id: "druid-domain:plane-of-fire:fire-hardened",
    name: "Fire Hardened",
    bucket: "blocked",
    note: "The base fire resistance 5 (scaling with any existing resistance) is unconditional and self-targeted; a real number this domain path has no patch hook to carry.",
  },
  hsPaehLs8BaMEmcj: {
    id: "hsPaehLs8BaMEmcj",
    name: "Void Awareness",
    bucket: "blocked",
    note: "An unconditional insight bonus on saves against spells/spell-likes, scaling with level, with no activation or per-day limit; a real number this school path has no patch hook to carry.",
  },
  "inquisition-power:banishment:dismissive-touch": {
    id: "inquisition-power:banishment:dismissive-touch",
    name: "Dismissive Touch",
    bucket: "subsystem",
    note: "A dismissal-equivalent spell-like effect delivered via touch attack against evil outsiders; not a bonus to the inquisitor.",
  },
  "0BZYhHw4PbbWJuhP": {
    id: "0BZYhHw4PbbWJuhP",
    name: "Earth Glide (WIZ)",
    bucket: "subsystem",
    note: "Grants a temporary earth-glide movement mode gated to a rounds-per-day budget; a movement-mode grant, not a Change-shaped bonus.",
  },
  "1aP0lmJYDqM5pMHY": {
    id: "1aP0lmJYDqM5pMHY",
    name: "Bedeviling Aura",
    bucket: "subsystem",
    note: "An activated aura imposing half speed, no attacks of opportunity, and flanked status on enemies; a debuff bundle on foes, not a bonus for the caster.",
  },
  "7QulGFMelZdF9pPl": {
    id: "7QulGFMelZdF9pPl",
    name: "Unstable Bonds",
    bucket: "subsystem",
    note: "A melee touch that inflicts shaken and staggered on a summoned/called creature; a condition on an enemy, not a self bonus.",
  },
  A3KJJHMNlAjUzcx6: {
    id: "A3KJJHMNlAjUzcx6",
    name: "Change Shape",
    bucket: "subsystem",
    note: "Grants a temporary polymorph-equivalent shapechange gated to a rounds-per-day budget; not a Change-shaped bonus.",
  },
  HMmsaPUiNgB5Xa8u: {
    id: "HMmsaPUiNgB5Xa8u",
    name: "Creator's Will",
    bucket: "subsystem",
    note: "Casts Minor/Major Creation as a spell-like ability on a per-day budget; not a bonus to the caster's sheet.",
  },
  Uo6HdLirmPk8haqz: {
    id: "Uo6HdLirmPk8haqz",
    name: "Elemental Manipulation",
    bucket: "subsystem",
    note: "An activated aura that transforms the energy type of magical effects passing through it; a rules exception, not a bonus.",
  },
  ZgzF1CxwvRBQX8xN: {
    id: "ZgzF1CxwvRBQX8xN",
    name: "Disruption",
    bucket: "subsystem",
    note: "A melee touch that forces a target to make concentration checks to cast; a debuff on an enemy, not a self bonus.",
  },
  "blessing-power:earth:major": {
    id: "blessing-power:earth:major",
    name: "Armor of Earth",
    bucket: "subsystem",
    note: "A touch buff granting DR to an ally; the resistance applies to the ally, not the warpriest.",
  },
  "blessing-power:protection:major": {
    id: "blessing-power:protection:major",
    name: "Aura of Protection",
    bucket: "situational",
    note: "Activated 1-minute aura with a level-gated resistance value that includes the warpriest ('you and your allies'), but only while active; not unconditional.",
  },
  "blessing-power:scalykind:minor": {
    id: "blessing-power:scalykind:minor",
    name: "Scaly Touch",
    bucket: "subsystem",
    note: "A touch buff granting natural armor to an ally; applies to the ally, not the warpriest.",
  },
  "blessing-power:shadow:major": {
    id: "blessing-power:shadow:major",
    name: "Swift as Shadow",
    bucket: "situational",
    note: "A swift-action buff explicitly usable on 'yourself or an ally' for a triggered charge effect; scoped to an activation and a specific action (charging), not unconditional.",
  },
  "druid-domain:monkey:monkey-athletics": {
    id: "druid-domain:monkey:monkey-athletics",
    name: "Monkey Athletics",
    bucket: "situational",
    note: "Free-action activation with a per-day use limit gates a competence bonus to one of four named skill checks.",
  },
  "druid-domain:ruins:ruin-touch": {
    id: "druid-domain:ruins:ruin-touch",
    name: "Ruin Touch",
    bucket: "subsystem",
    note: "A melee touch that alters an object's or construct's hardness; targets an object, not a creature's sheet, and is per-day limited.",
  },
  "druid-domain:wolf:pack-tactics": {
    id: "druid-domain:wolf:pack-tactics",
    name: "Pack Tactics",
    bucket: "situational",
    note: "A free-action ability that substitutes Wisdom modifier for the flanking bonus, gated to a per-day use limit and the specific flanking condition.",
  },
  "inquisition-power:anger:divine-anger": {
    id: "inquisition-power:anger:divine-anger",
    name: "Divine Anger",
    bucket: "subsystem",
    note: "Grants the ability to rage like a barbarian for a limited number of rounds per day; a granted ability, not a Change-shaped bonus.",
  },
  "inquisition-power:damnation:fear-the-flames": {
    id: "inquisition-power:damnation:fear-the-flames",
    name: "Fear the Flames",
    bucket: "subsystem",
    note: "The bonus (+2 morale) applies to obedient evil creatures, not the inquisitor; the effect otherwise shakes or compels a target.",
  },
  "inquisition-power:justice:judicious-force": {
    id: "inquisition-power:justice:judicious-force",
    name: "Judicious Force",
    bucket: "situational",
    note: "An immediate-action bonus explicitly usable by 'you or an ally,' gated to a per-day limit and the specific trigger of confirming a critical threat.",
  },
  "inquisition-power:order:mantle-against-chaos": {
    id: "inquisition-power:order:mantle-against-chaos",
    name: "Mantle against Chaos",
    bucket: "subsystem",
    note: "Casts protection from chaos as a spell-like ability on a limited-minutes-per-day budget; not a plain bonus.",
  },
  "inquisition-power:truth:grasp-of-honesty": {
    id: "inquisition-power:truth:grasp-of-honesty",
    name: "Grasp of Honesty",
    bucket: "subsystem",
    note: "Applies zone of truth to a creature the inquisitor is grappling, pinning, or touching; a spell-like effect on a target, not a self bonus.",
  },
  "inquisition-power:zeal:zealous-surge": {
    id: "inquisition-power:zeal:zealous-surge",
    name: "Zealous Surge",
    bucket: "situational",
    note: "A real self healing amount, but only triggers once per day when reduced to 0 or fewer hit points; not an unconditional bonus.",
  },
  nBCKHaM5edwuFFnk: {
    id: "nBCKHaM5edwuFFnk",
    name: "Aura of Banishment",
    bucket: "subsystem",
    note: "An activated aura that staggers and can banish summoned/called creatures; a debuff/dispel effect on enemies, not a self bonus.",
  },
  wa9VINqzFWWOnS6g: {
    id: "wa9VINqzFWWOnS6g",
    name: "Beguiling Touch",
    bucket: "subsystem",
    note: "A charm-monster-equivalent effect delivered by touch; not a bonus to the caster's sheet.",
  },
  "0nRLmRBWwS7NI7E4": {
    id: "0nRLmRBWwS7NI7E4",
    name: "Dancing Flame",
    bucket: "subsystem",
    note: "Lets the caster move or reshape fire (nonmagical or their own spells); a rules-manipulation ability, not a Change-shaped bonus.",
  },
  "1XDvZLP9UPjr1glZ": {
    id: "1XDvZLP9UPjr1glZ",
    name: "Grave Touch (WIZ)",
    bucket: "subsystem",
    note: "A melee touch that shakes or frightens a living creature; a condition inflicted on an enemy, not a self bonus.",
  },
  "1mwNVTch2j88G8h3": {
    id: "1mwNVTch2j88G8h3",
    name: "Fire Jet",
    bucket: "subsystem",
    note: "A line-shaped fire damage attack with a save; an attack effect, not a stat bonus.",
  },
  "52vhE9asxPlXIr39": {
    id: "52vhE9asxPlXIr39",
    name: "Elemental Wall",
    bucket: "subsystem",
    note: "Creates a Wall of Fire-equivalent barrier gated to a rounds-per-day budget; a spell-like effect, not a bonus.",
  },
  OLh9DNRqDf7yjSwM: {
    id: "OLh9DNRqDf7yjSwM",
    name: "Send Senses",
    bucket: "subsystem",
    note: "A scrying-sensor spell-like effect gated to a per-day use limit; not a Change-shaped bonus.",
  },
  QqMg8O5rYRKoGtHW: {
    id: "QqMg8O5rYRKoGtHW",
    name: "Versatile Evocation",
    bucket: "subsystem",
    note: "Lets the caster reassign the energy type of an evocation spell they cast; a spell-modification rule, not a bonus.",
  },
  UeYdiNoaF0gG08Y5: {
    id: "UeYdiNoaF0gG08Y5",
    name: "Resistance (Power)",
    bucket: "blocked",
    note: "The energy resistance is unconditional once an energy type is chosen for the day, but the type is a player choice reselected daily, and this school path has no patch hook regardless.",
  },
  W1gEXsOJYt7oDOr7: {
    id: "W1gEXsOJYt7oDOr7",
    name: "Inspiring Prediction",
    bucket: "subsystem",
    note: "A swift-action buff shouted to allies within 50 feet who can hear the caster; the luck bonus applies to allies, not the caster.",
  },
  W7nMOLi2kXGEKe72: {
    id: "W7nMOLi2kXGEKe72",
    name: "Invisibility Field",
    bucket: "subsystem",
    note: "Grants greater invisibility as a swift action gated to a rounds-per-day budget; a granted effect, not a Change-shaped bonus.",
  },
  YPqkXzcxHtggndAY: {
    id: "YPqkXzcxHtggndAY",
    name: "Earth Supremacy",
    bucket: "situational",
    note: "The CMD bonus is conditioned on 'touching the ground,' and the melee attack/damage bonus explicitly requires the foe to also be touching the ground; both are state the static sheet cannot detect.",
  },
  aVMtWqERshuxhmr6: {
    id: "aVMtWqERshuxhmr6",
    name: "Irresistible Demand",
    bucket: "subsystem",
    note: "A Dominate Monster-equivalent effect on a target creature, gated to a rounds-per-day budget; not a bonus to the caster.",
  },
  "blessing-power:destruction:minor": {
    id: "blessing-power:destruction:minor",
    name: "Destructive Attacks",
    bucket: "subsystem",
    note: "A touch buff granting a morale damage bonus to an ally's weapon; applies to the ally, not the warpriest.",
  },
  "blessing-power:earthquake:minor": {
    id: "blessing-power:earthquake:minor",
    name: "Stone's Base",
    bucket: "subsystem",
    note: "A touch buff granting a CMD bonus to an ally; applies to the ally, not the warpriest.",
  },
  "blessing-power:magic:minor": {
    id: "blessing-power:magic:minor",
    name: "Hand of the Acolyte",
    bucket: "subsystem",
    note: "Grants a ranged melee-weapon attack option using Wisdom instead of Dexterity for the attack roll; a new attack form, not a plain Change bonus.",
  },
  "blessing-power:repose:minor": {
    id: "blessing-power:repose:minor",
    name: "Gentle Rest",
    bucket: "subsystem",
    note: "A melee touch that staggers or puts a living creature to sleep; a condition on an enemy, not a self bonus.",
  },
  "blessing-power:shadow:minor": {
    id: "blessing-power:shadow:minor",
    name: "Flicker of Shadows",
    bucket: "subsystem",
    note: "A weapon-touch effect that ignores shield AC/cover on the first attack each round; a rules exception on an attack, not a Change-shaped bonus.",
  },
  "blessing-power:sun:minor": {
    id: "blessing-power:sun:minor",
    name: "Blinding Strike",
    bucket: "subsystem",
    note: "A blinding/dazzling effect imposed on an opponent; a condition on an enemy, not a self bonus.",
  },
  "blessing-power:wildfire:minor": {
    id: "blessing-power:wildfire:minor",
    name: "Leaping Flames",
    bucket: "subsystem",
    note: "A touch buff granting speed and a dodge bonus to an ally; applies to the ally, not the warpriest.",
  },
  "druid-domain:crocodile:familiar": {
    id: "druid-domain:crocodile:familiar",
    name: "Familiar",
    bucket: "subsystem",
    note: "Grants a familiar; a granted ability, not a Change-shaped bonus.",
  },
  "druid-domain:eagle:hawkeye": {
    id: "druid-domain:eagle:hawkeye",
    name: "Hawkeye",
    bucket: "situational",
    note: "A swift-action bonus to one ranged attack or Perception check, gated to a per-day use limit.",
  },
  "druid-domain:jungle:trap-sense": {
    id: "druid-domain:jungle:trap-sense",
    name: "Trap Sense",
    bucket: "blocked",
    note: "Mirrors class-feature-effects.ts's precedent on trap sense variants: the bonus is scoped to traps specifically, a scope outside the save/AC vocabulary; this domain path also has no patch hook regardless.",
  },
  "druid-domain:panther:move-in-darkness": {
    id: "druid-domain:panther:move-in-darkness",
    name: "Move in Darkness",
    bucket: "situational",
    note: "The Stealth/initiative bonus only applies in areas of normal or magical darkness, a lighting condition the static sheet cannot detect.",
  },
  "druid-domain:plane-of-air:wind-savant": {
    id: "druid-domain:plane-of-air:wind-savant",
    name: "Wind Savant",
    bucket: "blocked",
    note: "The save bonus against gases/inhaled poison is unconditional (no activation), but scoped to a 'gases' category narrower than any save-category the vocabulary carries; this domain path also has no patch hook.",
  },
  "druid-domain:plane-of-earth:one-with-the-stone": {
    id: "druid-domain:plane-of-earth:one-with-the-stone",
    name: "One with the Stone",
    bucket: "subsystem",
    note: "Grants an earth-glide movement mode (or alternatively a familiar), gated to a rounds-per-day budget; not a Change-shaped bonus.",
  },
  "druid-domain:plane-of-earth:spelunker": {
    id: "druid-domain:plane-of-earth:spelunker",
    name: "Spelunker",
    bucket: "situational",
    note: "Free-action activation, 1-round duration, and a per-day use limit gate the terrain immunity and damage reduction.",
  },
  "druid-domain:the-uskbond:absorb-pain": {
    id: "druid-domain:the-uskbond:absorb-pain",
    name: "Absorb Pain",
    bucket: "situational",
    note: "The save bonus against pain effects only applies for the round after an immediate-action trigger (taking lethal damage and using the ability), gated to a per-day use limit; not unconditional.",
  },
  ei3z5reJYduGyrrC: {
    id: "ei3z5reJYduGyrrC",
    name: "Lingering Evocations",
    bucket: "subsystem",
    note: "Extends the caster's own evocation spell durations; a spell-duration rule, not a Change-shaped bonus.",
  },
  fOGTp6cD9Oy33dcu: {
    id: "fOGTp6cD9Oy33dcu",
    name: "In Accordance with Prophecy",
    bucket: "subsystem",
    note: "Applies an Empower-Spell-equivalent effect (with a fizzle chance) to the caster's next spell, per-day limited; a spell-modification ability, not a bonus.",
  },
  "inquisition-power:clandestine:blessed-secrecy": {
    id: "inquisition-power:clandestine:blessed-secrecy",
    name: "Blessed Secrecy",
    bucket: "subsystem",
    note: "A 'roll twice, take the better result' mechanic on specific skill checks, per-day limited; not expressible as a flat Change bonus.",
  },
  "inquisition-power:heresy:blessed-infiltration": {
    id: "inquisition-power:heresy:blessed-infiltration",
    name: "Blessed Infiltration",
    bucket: "subsystem",
    note: "A 'roll twice, take the better result' mechanic on specific skill checks, per-day limited; not expressible as a flat Change bonus.",
  },
  "inquisition-power:illumination:illuminating-touch": {
    id: "inquisition-power:illumination:illuminating-touch",
    name: "Illuminating Touch",
    bucket: "subsystem",
    note: "A standard-action touch that grants a bonus to a creature the inquisitor touches; ally-directed rather than a bonus on the inquisitor's own sheet.",
  },
  "inquisition-power:politics:labyrinthine-words": {
    id: "inquisition-power:politics:labyrinthine-words",
    name: "Labyrinthine Words",
    bucket: "blocked",
    note: "An unconditional bonus (adding Wisdom modifier alongside Charisma modifier on Bluff/Diplomacy checks); a real self-facing number this granted-power path has no patch hook to carry.",
  },
  "inquisition-power:recovery:focused-search": {
    id: "inquisition-power:recovery:focused-search",
    name: "Focused Search",
    bucket: "situational",
    note: "The Perception/Survival bonus only applies when tracking or perceiving the specific person or object designated as the inquisitor's focus; not a general skill bonus.",
  },
  "inquisition-power:redemption:patient-sensibility": {
    id: "inquisition-power:redemption:patient-sensibility",
    name: "Patient Sensibility",
    bucket: "blocked",
    note: "An unconditional +2 bonus on three named skills with no activation or resource gate; a real self-facing number this granted-power path has no patch hook to carry.",
  },
  "inquisition-power:reformation:blessed-correction": {
    id: "inquisition-power:reformation:blessed-correction",
    name: "Blessed Correction",
    bucket: "subsystem",
    note: "A 'roll twice, take the better result' mechanic on specific skill checks, per-day limited; not expressible as a flat Change bonus.",
  },
  "inquisition-power:sin:sin-sense": {
    id: "inquisition-power:sin:sin-sense",
    name: "Sin Sense",
    bucket: "situational",
    note: "The bonus only applies to the inquisitor's next Charisma-based check against a specific target after a full-round-action read, gated to a per-day use limit.",
  },
  "inquisition-power:tactics:grant-the-initiative": {
    id: "inquisition-power:tactics:grant-the-initiative",
    name: "Grant the Initiative",
    bucket: "blocked",
    note: "An unconditional bonus (Wisdom modifier on initiative checks) for the inquisitor and nearby allies, no activation required; a real self-facing number this granted-power path has no patch hook to carry.",
  },
  "inquisition-power:torture:torturer-s-presence": {
    id: "inquisition-power:torture:torturer-s-presence",
    name: "Torturer's Presence",
    bucket: "blocked",
    note: "An unconditional +2 bonus on Intimidate checks with no activation or resource gate; a real self-facing number this granted-power path has no patch hook to carry.",
  },
  "inquisition-power:true_death:hallowed-rite": {
    id: "inquisition-power:true_death:hallowed-rite",
    name: "Hallowed Rite",
    bucket: "subsystem",
    note: "A day-long funeral ritual that prevents a corpse from being turned undead; a rules exception, not a Change-shaped bonus.",
  },
  "inquisition-power:truth:justice-s-true-path": {
    id: "inquisition-power:truth:justice-s-true-path",
    name: "Justice's True Path",
    bucket: "subsystem",
    note: "A standard-action touch that grants a bonus to a creature the inquisitor touches; ally-directed rather than a bonus on the inquisitor's own sheet.",
  },
  "inquisition-power:zeal:scourge-of-the-enemy": {
    id: "inquisition-power:zeal:scourge-of-the-enemy",
    name: "Scourge of the Enemy",
    bucket: "blocked",
    note: "A favored-enemy-equivalent bonus scoped to a player-chosen rival religion, a choice-dependent target this granted-power path also has no patch hook to carry.",
  },
  mITkHIcXI1Sfax21: {
    id: "mITkHIcXI1Sfax21",
    name: "Diviner's Fortune",
    bucket: "subsystem",
    note: "A standard-action touch that grants an insight bonus to a creature the wizard touches, per-day limited; ally-directed rather than a bonus on the wizard's own sheet.",
  },
  n11lJHH3cBKXdRdj: {
    id: "n11lJHH3cBKXdRdj",
    name: "Hand of the Apprentice",
    bucket: "subsystem",
    note: "Grants a ranged melee-weapon attack option using Intelligence instead of Dexterity for the attack roll; a new attack form, not a plain Change bonus.",
  },
  nys5AYQTTDq8c0OS: {
    id: "nys5AYQTTDq8c0OS",
    name: "Cyclone",
    bucket: "subsystem",
    note: "Creates a vortex that blocks ranged attacks and can down flying creatures, gated to a rounds-per-day budget; a battlefield-control effect, not a bonus.",
  },
  pDaXowPKX4scZL0E: {
    id: "pDaXowPKX4scZL0E",
    name: "Extended Illusions",
    bucket: "subsystem",
    note: "Extends the caster's own illusion spell durations (and can make one permanent at 20th level); a spell-duration rule, not a Change-shaped bonus.",
  },
  qzCj0dGiKmIMw4wf: {
    id: "qzCj0dGiKmIMw4wf",
    name: "Perfection of Self",
    bucket: "situational",
    note: "A swift-action enhancement bonus to a chosen ability score lasting 1 round, gated to a per-day use limit; not unconditional.",
  },
  raSRxU51tCnX2oMy: {
    id: "raSRxU51tCnX2oMy",
    name: "Splintered Spear",
    bucket: "subsystem",
    note: "Creates a spear that makes a ranged attack using Intelligence, then inflicts bleed damage; a granted attack form, not a plain Change bonus.",
  },
  uLPfDpPNzuyiKHKU: {
    id: "uLPfDpPNzuyiKHKU",
    name: "Reveal Weakness",
    bucket: "subsystem",
    note: "A standard-action penalty imposed on a chosen foe's AC and saves, per-day limited; applies to an enemy, not the wizard's own sheet.",
  },
};
