/**
 * Class-feature classification shard: cleric domain and subdomain granted
 * powers. These flow through `collect.ts`'s domains section, which applies
 * vendored `changes` and, via `granted-power-effects/`'s
 * `GRANTED_POWER_CHANGE_PATCHES`, hand-authored patches keyed by the power's
 * name. A real unconditional number here buckets `numeric` once a patch
 * entry exists; `blocked` is reserved for a number with no expressible
 * engine target, a scope outside the `SAVE_CATEGORIES`/targets vocabulary,
 * or a player choice a static entry can't express.
 */

import type { ClassFeatureClassificationEntry } from "./types.js";

export const CLASS_FEATURE_CLASSIFICATION_UNROUTED_DOMAINS: Readonly<
  Record<string, ClassFeatureClassificationEntry>
> = {
  kHXw5V06TkymXxF3: {
    id: "kHXw5V06TkymXxF3",
    name: "Aura of Protection (Domain Power)",
    bucket: "situational",
    note: "The power's text reads \"you and your allies,\" so the deflection AC bonus reaches the cleric too, not allies alone. It already surfaces as an activate/deactivate toggle on this pool's row through the vendored linked buff (`grantsBuffs`) that `resources.ts`'s own `linkedBuffIds` pass resolves, whose `changes[]` carries the deflection bonus; no per-day-activations entry is needed. The elemental-resistance clause named in the power's description isn't captured in that buff's changes and stays unmodeled prose.",
  },
  "3zggJMxuipE68IkT": {
    id: "3zggJMxuipE68IkT",
    name: "Perfected Form",
    bucket: "numeric",
    note: "The +1 sacred bonus on saves versus polymorph, petrification, and transmutation effects (scaling by 5 cleric levels, max +5) is wired via GRANTED_POWER_CHANGE_PATCHES. The once-per-day immediate-action temporary-HP-and-morale surge on a successful save stays prose, resource-gated.",
  },
  "subdomain-power:rivers:current-flow": {
    id: "subdomain-power:rivers:current-flow",
    name: "Current Flow",
    bucket: "situational",
    note: "Requires activating the power and picking one of speed or swim speed to boost; the Swim check bonus and duration (Wisdom modifier rounds) are both gated by that activation.",
  },
  "8hVa9HwekAWpgHid": {
    id: "8hVa9HwekAWpgHid",
    name: "Inspiring Word (Domain Power)",
    bucket: "situational",
    note: "Standard action, uses-per-day resource pool (3 + Wisdom modifier), and the morale bonus targets a creature within 30 feet, not the cleric unconditionally.",
  },
  "subdomain-power:azata:elysium-s-call": {
    id: "subdomain-power:azata:elysium-s-call",
    name: "Elysium's Call",
    bucket: "situational",
    note: "Touch-activated buff bundle (reroll, save bonus, escape-grapple bonus, difficult-terrain ignore) lasting 1/2 cleric level rounds; entirely dependent on the touch action being used.",
  },
  "subdomain-power:feather:eyes-of-the-hawk": {
    id: "subdomain-power:feather:eyes-of-the-hawk",
    name: "Eyes of the Hawk",
    bucket: "numeric",
    note: "The Perception bonus (half cleric level, minimum +1) is wired as a racial-type Change via GRANTED_POWER_CHANGE_PATCHES. The +2 Initiative bonus stays prose: it only applies during a surprise round, a fight state the static sheet can't detect.",
  },
  "subdomain-power:nightmare:fearful-touch": {
    id: "subdomain-power:nightmare:fearful-touch",
    name: "Fearful Touch",
    bucket: "situational",
    note: "Melee touch attack that inflicts a Will-save penalty and attack-roll penalty on the struck target for 1 round; the number belongs to the enemy's state, not an unconditional bonus to the cleric.",
  },
  yDG7xVuH7oqWS4Mt: {
    id: "yDG7xVuH7oqWS4Mt",
    name: "Deflection Aura",
    bucket: "situational",
    note: 'Once-per-day rounds-limited aura; the deflection AC/CMD bonus applies to allies inside the aura (the power\'s text reads "allies," not "you and your allies"), not the cleric unconditionally. It already surfaces as an activate/deactivate toggle on this pool\'s row through the vendored linked buff (`grantsBuffs`) that `resources.ts`\'s own `linkedBuffIds` pass resolves; no per-day-activations entry is needed.',
  },
  "subdomain-power:demon:fury-of-the-abyss": {
    id: "subdomain-power:demon:fury-of-the-abyss",
    name: "Fury of the Abyss",
    bucket: "situational",
    note: "Swift-action activation lasting 1 round with a self-imposed AC penalty tradeoff; the enhancement bonus is not always-on.",
  },
  "subdomain-power:hubris:divine-demand": {
    id: "subdomain-power:hubris:divine-demand",
    name: "Divine Demand",
    bucket: "situational",
    note: "Only usable at the moment of casting a spell with a partial save effect, with escalating consequences (shaken, or losing divine abilities) on a bad outcome; entirely conditional on that trigger.",
  },
  LY6y8GWhXzK8wDDZ: {
    id: "LY6y8GWhXzK8wDDZ",
    name: "Wooden Fist",
    bucket: "situational",
    note: "Free-action activation drawing from a rounds-per-day pool; the unarmed damage bonus is self-facing while active, but it scales with the granting class's level (half cleric level, minimum +1) — a formula this table can't express safely across a domain power's cleric/inquisitor/druid bearers (no `@class.unlevel` context here, and a `classTag` guard would just hide the toggle for the other bearers), so it stays prose.",
  },
  T4q7Ib0ED01PNDyT: {
    id: "T4q7Ib0ED01PNDyT",
    name: "Destructive Smite",
    bucket: "situational",
    note: "Must be declared before a specific attack and draws from a uses-per-day pool (3 + Wisdom modifier); not an unconditional bonus.",
  },
  "domain:destruction:destructive-aura": {
    id: "domain:destruction:destructive-aura",
    name: "Destructive Aura",
    bucket: "situational",
    note: "This synthetic id carries no vendored `uses.maxFormula`, so no pool row derives for it to attach a toggle to. Independently, the damage bonus and automatic-crit-confirmation apply to any attack (including the cleric's own) made against a creature inside the aura, and only while the aura is active, not an unconditional bonus.",
  },
  "subdomain-power:insect:exoskeleton": {
    id: "subdomain-power:insect:exoskeleton",
    name: "Exoskeleton",
    bucket: "situational",
    note: "Growing the exoskeleton is a 1-round-duration activation drawn from this power's own per-day pool, so it would need a per-day-activations toggle rather than a permanent Change; that shard stays empty for domain powers whose numbers scale with the granting class's level (see its header), and this one does (+1 natural armor per 5 cleric levels). Independently, the temporary hit points are dice-valued (1d4 + 1 per 2 cleric levels), which no engine formula path evaluates to a number.",
  },
  "subdomain-power:petrification:fossil-form": {
    id: "subdomain-power:petrification:fossil-form",
    name: "Fossil Form",
    bucket: "situational",
    note: "A per-turn activated choice with a staggered tradeoff; the hardness and save bonus only apply until the start of the cleric's next turn.",
  },
  "7td8qAPvj9YEasha": {
    id: "7td8qAPvj9YEasha",
    name: "Touch of Good",
    bucket: "situational",
    note: "Standard-action touch power drawing from a uses-per-day pool (3 + Wisdom modifier); the sacred bonus applies to the touched creature for 1 round, not unconditionally to the cleric.",
  },
  QkHDkpopJ7P8g14c: {
    id: "QkHDkpopJ7P8g14c",
    name: "Guarded Mind",
    bucket: "numeric",
    note: 'The +2 insight bonus on saves against mind-affecting effects is wired via GRANTED_POWER_CHANGE_PATCHES, scoped with saveCategories: ["mind"] rather than an unconditional Will bonus.',
  },
  "subdomain-power:agathion:protective-aura": {
    id: "subdomain-power:agathion:protective-aura",
    name: "Protective Aura",
    bucket: "situational",
    note: "Activated 30-foot aura; the deflection AC and resistance bonuses (plus protection from evil) apply to allies inside it, not the cleric unconditionally.",
  },
  "subdomain-power:archon:aura-of-menace": {
    id: "subdomain-power:archon:aura-of-menace",
    name: "Aura of Menace",
    bucket: "situational",
    note: "Activated 30-foot aura imposing a penalty on enemies inside it; a penalty on enemies rather than a bonus to the cleric, and only while the aura is maintained.",
  },
  "subdomain-power:cannibalism:consume-the-enemy": {
    id: "subdomain-power:cannibalism:consume-the-enemy",
    name: "Consume the Enemy",
    bucket: "situational",
    note: "Requires committing an evil act against a helpless or freshly killed creature; the profane bonus is conditioned on that trigger and on facing a matching creature type afterward.",
  },
  "subdomain-power:captivation:entrancing-aura": {
    id: "subdomain-power:captivation:entrancing-aura",
    name: "Entrancing Aura",
    bucket: "situational",
    note: "Activated 30-foot aura imposing a Perception penalty and reduced-HD treatment on enemies inside it; not a bonus to the cleric and only while maintained.",
  },
  "subdomain-power:caves:tunnel-runner": {
    id: "subdomain-power:caves:tunnel-runner",
    name: "Tunnel Runner",
    bucket: "situational",
    note: 'An activated state ("while this ability is active") scoped to being underground; the Stealth and Initiative bonuses only apply during that window, alongside the granted spider climb and darkvision.',
  },
  "subdomain-power:devil:hell-s-corruption": {
    id: "subdomain-power:devil:hell-s-corruption",
    name: "Hell's Corruption",
    bucket: "situational",
    note: "Melee touch attack that inflicts a save penalty and doubled-worse-of-two skill checks on the struck target; scoped to the target's state, not an unconditional bonus to the cleric.",
  },
  "subdomain-power:duels:divine-challenge": {
    id: "subdomain-power:duels:divine-challenge",
    name: "Divine Challenge",
    bucket: "situational",
    note: "Requires activating a challenge against one visible foe within 30 feet; the AC bonus and Bluff bonus apply only against that foe for a limited number of rounds.",
  },
  "subdomain-power:fist:wooden-fist": {
    id: "subdomain-power:fist:wooden-fist",
    name: "Wooden Fist",
    bucket: "situational",
    note: "Same activated-state, unarmed-damage-bonus shape as the domain-level Wooden Fist power (a duplicate name in this catalog); mirrors its situational verdict since the bonus only applies while the hands are hardened.",
  },
  "subdomain-power:industry:aura-of-efficiency": {
    id: "subdomain-power:industry:aura-of-efficiency",
    name: "Aura of Efficiency",
    bucket: "situational",
    note: "Activated 30-foot aura; the saving-throw and hardness bonuses apply to allies inside it, not the cleric unconditionally.",
  },
  "subdomain-power:leadership:inspiring-command": {
    id: "subdomain-power:leadership:inspiring-command",
    name: "Inspiring Command",
    bucket: "situational",
    note: "Requires issuing the command as an activated action; the insight bonus applies to designated allies for 1 round only.",
  },
  "subdomain-power:memory:recall": {
    id: "subdomain-power:memory:recall",
    name: "Recall",
    bucket: "situational",
    note: "Touch-activated power scoped to a Knowledge check made within the past minute; the insight bonus (Wisdom modifier) only applies to that retry.",
  },
  "subdomain-power:loyalty:touch-of-loyalty": {
    id: "subdomain-power:loyalty:touch-of-loyalty",
    name: "Touch of Loyalty",
    bucket: "situational",
    note: "Standard-action touch power; the sacred save bonus applies to the touched creature for 1 hour, not an unconditional bonus to the cleric.",
  },
  "subdomain-power:resolve:bestow-resolve": {
    id: "subdomain-power:resolve:bestow-resolve",
    name: "Bestow Resolve",
    bucket: "situational",
    note: "Activated power scoped to allies within 20 feet; the temporary hit points last only 1 minute and require the activation.",
  },
  "subdomain-power:resurrection:gift-of-life": {
    id: "subdomain-power:resurrection:gift-of-life",
    name: "Gift of Life",
    bucket: "subsystem",
    note: "Grants a unique short-term revival ability on a creature that died within the last minute; the returned creature's temporary hit-point total is a one-off ritual detail, not a Change-shaped bonus on the cleric's own sheet.",
  },
  "subdomain-power:revelation:guided-eyes": {
    id: "subdomain-power:revelation:guided-eyes",
    name: "Guided Eyes",
    bucket: "situational",
    note: "The always-on class-skill grant carries no numeric target, but the meaningful number here (+4 sacred bonus) only applies to skill checks made to see through a disguise or find something hidden or concealed, a narrow scoped circumstance the static sheet can't detect.",
  },
  "subdomain-power:smoke:cloud-of-smoke": {
    id: "subdomain-power:smoke:cloud-of-smoke",
    name: "Cloud of Smoke",
    bucket: "situational",
    note: "Standard-action activated cloud imposing a penalty and concealment on enemies inside it for a limited duration; not an unconditional bonus to the cleric.",
  },
  zx0lJIxpj8ZCDh97: {
    id: "zx0lJIxpj8ZCDh97",
    name: "Taboo (Domain Power)",
    bucket: "situational",
    note: "Immediate-action reactive power drawing from a uses-per-day pool, with a tradeoff (losing the Protection domain's resistance bonus) while active; the save penalty applies to whoever triggered it, not the cleric.",
  },
  "2mnWAoFKqKKxWCt4": {
    id: "2mnWAoFKqKKxWCt4",
    name: "Liberation (Domain Power)",
    bucket: "subsystem",
    note: "Grants an automatic freedom-of-movement-style effect (ignore movement impediments) with no bonus number attached; the rounds-per-day cap is a resource-tracking detail, not a Change-shaped target.",
  },
  "90Z23Z4U7ujOcvco": {
    id: "90Z23Z4U7ujOcvco",
    name: "Touch of Evil",
    bucket: "subsystem",
    note: "Melee touch attack that inflicts the sickened condition and an evil-spell-targeting classification on the struck creature; no bonus number applies to the cleric's own sheet.",
  },
  Aw4xfA8YSYHGiUXV: {
    id: "Aw4xfA8YSYHGiUXV",
    name: "Aura of Madness",
    bucket: "subsystem",
    note: "Rounds-per-day aura that forces a Will save or confusion on enemies inside it; a save-DC-gated condition effect on enemies, not a bonus number on the cleric's own sheet.",
  },
  F6D6MV5q8BOjiCTU: {
    id: "F6D6MV5q8BOjiCTU",
    name: "Freedom's Call",
    bucket: "subsystem",
    note: "Rounds-per-day aura granting condition immunity (confused, grappled, frightened, panicked, paralyzed, pinned, shaken) to allies inside it; no bonus number attached.",
  },
  FZdWscHJvJpGPoDz: {
    id: "FZdWscHJvJpGPoDz",
    name: "Lightning Lord",
    bucket: "subsystem",
    note: "Grants a limited-use spell-like ability that literally functions as call lightning, wired via the spell-like-abilities route (attaches to the vendored pool); no bonus number applies to the cleric's own sheet.",
  },
  GidNLmDQBdokwgUn: {
    id: "GidNLmDQBdokwgUn",
    name: "Bramble Armor",
    bucket: "situational",
    note: "Free-action activation drawing from a rounds-per-day pool; the retaliation damage (1d6 + 1 per two cleric levels) is dice-based damage dealt to whoever strikes the cleric, not a bonus number on the cleric's own sheet, so it has no Change-shaped target and stays prose.",
  },
  KF3SgIKeBACJhSZ1: {
    id: "KF3SgIKeBACJhSZ1",
    name: "Ward Against Death",
    bucket: "subsystem",
    note: "Rounds-per-day aura granting immunity to death effects, energy drain, and negative levels to living creatures inside it; no bonus number attached.",
  },
  KXN1Y4DDcWd8ZraE: {
    id: "KXN1Y4DDcWd8ZraE",
    name: "Divine Presence",
    bucket: "subsystem",
    note: "Standard-action, rounds-per-day aura granting a sanctuary-style effect to allies inside it; a rules-exception grant with no Change-shaped bonus on the cleric's own sheet.",
  },
  Le6qmKF8wkhVCPCz: {
    id: "Le6qmKF8wkhVCPCz",
    name: "Touch of Darkness",
    bucket: "situational",
    note: "Melee touch attack imposing a 20% miss chance on the struck creature's perception of others; a penalty scoped to the touched target, not the cleric.",
  },
  M8IQnVMYyqh1Mrl7: {
    id: "M8IQnVMYyqh1Mrl7",
    name: "Eyes of Darkness",
    bucket: "subsystem",
    note: "Grants unimpaired vision in darkness (a sense, effectively superior darkvision) for a rounds-per-day pool; no bonus number attached, the rounds cap is resource tracking.",
  },
  QZJtfwamnWW0mHjJ: {
    id: "QZJtfwamnWW0mHjJ",
    name: "Nimbus of Light",
    bucket: "situational",
    note: "Rounds-per-day aura; the per-round damage to undead inside it is scoped to enemy state and the aura's active window, not an unconditional bonus to the cleric.",
  },
  WMtJbAlvzaLnzYVy: {
    id: "WMtJbAlvzaLnzYVy",
    name: "Might of the Gods",
    bucket: "situational",
    note: "Rounds-per-day activated effect; the Strength enhancement bonus is self-facing while active, but it equals the granting class's level outright — a formula this table can't express safely across a domain power's cleric/inquisitor/druid bearers (no `@class.unlevel` context here, and a `classTag` guard would just hide the toggle for the other bearers), so it stays prose.",
  },
  XhpyFMIbhL5ogMVe: {
    id: "XhpyFMIbhL5ogMVe",
    name: "Part the Veil",
    bucket: "subsystem",
    note: "Adds an extra confusion effect to spells the cleric casts (a swift-action modifier to spellcasting), drawing from a uses-per-day pool; no Change-shaped bonus number applies to the cleric's own sheet.",
  },
  mS7LSsQQkjVvKx9z: {
    id: "mS7LSsQQkjVvKx9z",
    name: "Gentle Rest (Domain Power)",
    bucket: "subsystem",
    note: "Melee touch attack inflicting staggered or sleep on a struck creature; a condition effect on the target, not a bonus number on the cleric.",
  },
  "subdomain-power:flowing:go-with-the-flow": {
    id: "subdomain-power:flowing:go-with-the-flow",
    name: "Go with the Flow",
    bucket: "subsystem",
    note: "This synthetic id carries no vendored `uses.maxFormula`, so no pool row derives for it to attach a toggle to. Independently, it is a touch power applying a calm-emotions-style effect to a target; no bonus number applies to the cleric's own sheet.",
  },
  "subdomain-power:portal:sacred-threshold": {
    id: "subdomain-power:portal:sacred-threshold",
    name: "Sacred Threshold",
    bucket: "situational",
    note: "Standard-action, 1-minute-duration power; the portal-DC adjustment and the temporary hit points (granted only to the first ally through the portal) are both scoped to that activation window.",
  },
  "subdomain-power:portal:travel-as-one": {
    id: "subdomain-power:portal:travel-as-one",
    name: "Travel as One",
    bucket: "situational",
    note: "Only applies when casting a teleportation-descriptor spell; the caster-level increase and temporary hit points are conditioned on that trigger.",
  },
  "subdomain-power:protean:aura-of-chaos": {
    id: "subdomain-power:protean:aura-of-chaos",
    name: "Aura of Chaos",
    bucket: "subsystem",
    note: "This synthetic id carries no vendored `uses.maxFormula`, so no pool row derives for it to attach a toggle to. Independently, it forces enemies within the aura to declare and resolve an action type against a Will save; a condition effect on enemies, not a bonus number on the cleric.",
  },
  u5LefrXZxQgLqmyJ: {
    id: "u5LefrXZxQgLqmyJ",
    name: "Bleeding Touch",
    bucket: "situational",
    note: "Melee touch attack, uses-per-day pool; the bleed damage and duration apply to the struck target, not an unconditional bonus to the cleric.",
  },
  v4wH3dsMLl1Bm542: {
    id: "v4wH3dsMLl1Bm542",
    name: "Vision of Madness",
    bucket: "situational",
    note: "Melee touch attack, uses-per-day pool, and a player-chosen roll category; the bonus/penalty split applies to the struck target for 3 rounds, not the cleric.",
  },
  yUdt1JIkSsQabXTF: {
    id: "yUdt1JIkSsQabXTF",
    name: "Remote Viewing",
    bucket: "subsystem",
    note: "Grants Clairaudience/Clairvoyance itself (the vendored text names the actual combined spell, not a style-alike) as an at-will spell-like ability for a rounds-per-day pool, wired via the spell-like-abilities route (attaches to the vendored pool); no bonus number applies to the cleric's own sheet.",
  },
  zeLaBkwTp9wlzZJv: {
    id: "zeLaBkwTp9wlzZJv",
    name: "Artificer's Touch",
    bucket: "situational",
    note: "The at-will mending is a pure ability grant, but the object/construct damage (with DR/hardness bypass) is a melee-touch, uses-per-day-gated number scoped to that attack action.",
  },
  "01m5lHnOP2E2FS5B": {
    id: "01m5lHnOP2E2FS5B",
    name: "Hand of the Acolyte (Domain Power)",
    bucket: "subsystem",
    note: "Grants an alternate ranged attack action that substitutes Wisdom for Dexterity on the attack roll, drawing from a uses-per-day pool; a rules-exception attack option, not a Change-shaped bonus.",
  },
  "0BFuaPpChxXneJwF": {
    id: "0BFuaPpChxXneJwF",
    name: "Touch of Glory",
    bucket: "situational",
    note: "Standard-action touch power, uses-per-day pool; the banked Charisma-check bonus applies to a single future roll for the touched creature, not an unconditional bonus.",
  },
  "1jMb1iCiNjS5yfwe": {
    id: "1jMb1iCiNjS5yfwe",
    name: "Animal Companion",
    bucket: "subsystem",
    note: "Grants an animal companion, effective druid level = cleric level - 3 (Animal domain) — wired via COMPANION_EFFECT_CLASS_FEATURES onto the tracked companion's stat block, gated on the Animal domain tag. A druid taking the same domain through Nature Bond uses a different offset, tracked separately.",
  },
  Iu8gyBT93dRpGtgH: {
    id: "Iu8gyBT93dRpGtgH",
    name: "Strength Surge (Domain Power)",
    bucket: "situational",
    note: "Standard-action touch power lasting 1 round, uses-per-day pool; the Strength-based enhancement bonus applies to the touched creature only during that window.",
  },
  J4QibEdTUK559sGO: {
    id: "J4QibEdTUK559sGO",
    name: "Staff of Order",
    bucket: "subsystem",
    note: "Grants the axiomatic weapon special quality to a touched weapon for a limited duration, uses-per-day pool; a rules-exception weapon-quality grant, not a Change-shaped bonus.",
  },
  Kgcm3ye8CYGipsg3: {
    id: "Kgcm3ye8CYGipsg3",
    name: "Storm Burst",
    bucket: "situational",
    note: "Standard-action ranged touch attack, uses-per-day pool; the damage and attack penalty apply to the struck target, not an unconditional bonus to the cleric.",
  },
  NDysrxC1AH0gLcqd: {
    id: "NDysrxC1AH0gLcqd",
    name: "Weapon Master",
    bucket: "subsystem",
    note: "Grants temporary use of one combat feat for a rounds-per-day pool; a rules-exception feat grant, not a Change-shaped bonus number.",
  },
  PXdTxpse6nHDdQyR: {
    id: "PXdTxpse6nHDdQyR",
    name: "Battle Rage",
    bucket: "situational",
    note: "Standard-action touch power, uses-per-day pool; the melee damage bonus applies to the touched creature for 1 round, not an unconditional bonus to the cleric.",
  },
  Vf0LVJue8NkXSupp: {
    id: "Vf0LVJue8NkXSupp",
    name: "Chaos Blade",
    bucket: "subsystem",
    note: "Grants the anarchic weapon special quality to a touched weapon for a limited duration, uses-per-day pool; a rules-exception weapon-quality grant, not a Change-shaped bonus.",
  },
  Wj2W2g5Ive3PlIlg: {
    id: "Wj2W2g5Ive3PlIlg",
    name: "Blast Rune (Domain Power)",
    bucket: "situational",
    note: "Standard-action created hazard, uses-per-day pool; the damage applies to whichever creature triggers the rune, not an unconditional bonus to the cleric.",
  },
  YvEe9B32X53ZCuWs: {
    id: "YvEe9B32X53ZCuWs",
    name: "Thundercloud",
    bucket: "situational",
    note: "Standard-action activated cloud, rounds-per-day pool; the deafened condition and per-round damage apply to creatures inside the cloud, not the cleric.",
  },
  hVrmBvlqeeLbwVxn: {
    id: "hVrmBvlqeeLbwVxn",
    name: "Copycat",
    bucket: "subsystem",
    note: "Grants a mirror-image-style illusory double, uses-per-day pool; a defensive rules-exception effect, not a Change-shaped bonus number.",
  },
  "subdomain-power:aeon:void-form": {
    id: "subdomain-power:aeon:void-form",
    name: "Void Form",
    bucket: "situational",
    note: 'An activated form ("you can become semi-tangible") that grants the deflection bonus and critical-hit immunity only while maintained.',
  },
  "subdomain-power:aristocracy:noble-visage": {
    id: "subdomain-power:aristocracy:noble-visage",
    name: "Noble Visage",
    bucket: "situational",
    note: "The Charisma-check bonus (1 + one-fifth cleric level) only applies against creatures sharing the cleric's own creature type and subtype, a scoped condition the static sheet cannot detect without over-applying to every roll.",
  },
  "subdomain-power:blood:wounding-blade": {
    id: "subdomain-power:blood:wounding-blade",
    name: "Wounding Blade",
    bucket: "subsystem",
    note: "Grants the wounding weapon special quality to a touched weapon for a limited duration; a rules-exception weapon-quality grant, not a Change-shaped bonus.",
  },
  "subdomain-power:cooperation:synergistic-touch": {
    id: "subdomain-power:cooperation:synergistic-touch",
    name: "Synergistic Touch",
    bucket: "subsystem",
    note: "Touch power that confers one of the cleric's own teamwork feats onto a touched creature for a limited duration; a rules-exception grant, not a Change-shaped bonus number.",
  },
  "subdomain-power:corruption:spark-malfeasance": {
    id: "subdomain-power:corruption:spark-malfeasance",
    name: "Spark Malfeasance",
    bucket: "subsystem",
    note: "Ranged touch attack inflicting the sickened condition on a target within 30 feet; a condition effect on the enemy, not a bonus number on the cleric.",
  },
  "subdomain-power:curse:malign-eye": {
    id: "subdomain-power:curse:malign-eye",
    name: "Malign Eye",
    bucket: "situational",
    note: "Activated power scoped to one target within 30 feet; the save penalty applies to that target for up to 1 minute, not an unconditional bonus to the cleric.",
  },
  "subdomain-power:decay:aura-of-decay": {
    id: "subdomain-power:decay:aura-of-decay",
    name: "Aura of Decay",
    bucket: "situational",
    note: "An emitted aura; the per-round damage and cumulative Strength penalty apply to living creatures (other than the cleric) inside it, scoped to enemy state and the aura's active area.",
  },
  "subdomain-power:family:binding-ties": {
    id: "subdomain-power:family:binding-ties",
    name: "Binding Ties",
    bucket: "subsystem",
    note: "Touch power that transfers a condition from an ally onto the cleric for a limited duration; a rules-exception effect, not a Change-shaped bonus number.",
  },
  "subdomain-power:home:guarded-hearth": {
    id: "subdomain-power:home:guarded-hearth",
    name: "Guarded Hearth",
    bucket: "situational",
    note: "This synthetic id carries no vendored `uses.maxFormula`, so no pool row derives for it to attach a toggle to, even though the sacred bonus (a flat Wisdom modifier, not level-scaling) could otherwise cover the cleric if self-designated. It also requires a 10-minute setup and only benefits creatures the cleric designates while they remain inside the warded area, a player choice this table has no stored pick to key from.",
  },
  "subdomain-power:imagination:haze-of-daydreams": {
    id: "subdomain-power:imagination:haze-of-daydreams",
    name: "Haze of Daydreams",
    bucket: "subsystem",
    note: "Emitted aura imposing the fascinated condition on enemies inside it (Will save to resist); a condition effect, not a bonus number on the cleric's own sheet.",
  },
  "subdomain-power:insanity:insane-focus": {
    id: "subdomain-power:insanity:insane-focus",
    name: "Insane Focus",
    bucket: "situational",
    note: "Touch-activated power scoped to a willing creature; the save bonus and confusion immunity last 1 minute and depend on that activation.",
  },
  "subdomain-power:kyton:pain-is-power": {
    id: "subdomain-power:kyton:pain-is-power",
    name: "Pain Is Power",
    bucket: "subsystem",
    note: "Triggered by taking damage and passing a DC 25 concentration check; grants the benefits of a referenced spell effect rather than a direct Change-shaped bonus number.",
  },
  "subdomain-power:light:blinding-flash": {
    id: "subdomain-power:light:blinding-flash",
    name: "Blinding Flash",
    bucket: "subsystem",
    note: "Emitted flash that blinds or dazzles creatures in the area (Fortitude save to resist blindness); a condition effect on enemies, not a bonus number on the cleric's own sheet.",
  },
  "subdomain-power:night:night-hunter": {
    id: "subdomain-power:night:night-hunter",
    name: "Night Hunter",
    bucket: "subsystem",
    note: "Grants an invisibility-style effect while in dim light or darkness for a limited duration; a rules-exception sense/concealment grant, not a Change-shaped bonus number.",
  },
  "subdomain-power:radiation:radiating-touch": {
    id: "subdomain-power:radiation:radiating-touch",
    name: "Radiating Touch",
    bucket: "subsystem",
    note: "Irradiates an unattended object that sickens creatures passing near it (Will save to resist); a condition effect on whoever triggers it, not a bonus number on the cleric.",
  },
  "subdomain-power:rage:rage": {
    id: "subdomain-power:rage:rage",
    name: "Rage",
    bucket: "subsystem",
    note: "Grants access to barbarian rage (and, at higher levels, a rage power); the rage state itself is a rules-exception grant tracked as its own mechanic, not a Change-shaped bonus number here.",
  },
  "subdomain-power:riot:aura-of-bedlam": {
    id: "subdomain-power:riot:aura-of-bedlam",
    name: "Aura of Bedlam",
    bucket: "situational",
    note: "Emitted 30-foot aura; the concentration-check penalty applies to enemies inside it, scoped to enemy state and the aura's active window.",
  },
  "subdomain-power:sahkil:touch-of-paranoia": {
    id: "subdomain-power:sahkil:touch-of-paranoia",
    name: "Touch of Paranoia",
    bucket: "subsystem",
    note: "Melee touch attack that strips a target's ally relationships (no more flanking, teamwork feats, aid another with allies) for a limited duration; a rules-exception effect on the target, not a bonus number on the cleric.",
  },
  "subdomain-power:saurian:dinosaur-companion": {
    id: "subdomain-power:saurian:dinosaur-companion",
    name: "Dinosaur Companion",
    bucket: "subsystem",
    note: "Grants an animal companion (a dinosaur); the companion's own stats are computed elsewhere, and this grant carries no Change-shaped bonus number on the cleric's own sheet.",
  },
  "subdomain-power:slavery:master-s-yoke": {
    id: "subdomain-power:slavery:master-s-yoke",
    name: "Master's Yoke",
    bucket: "subsystem",
    note: "Activated power inflicting a dominate-monster-style effect (or Constitution damage and staggered as an alternative) on a target creature; a rules-exception mind-control effect, not a bonus number on the cleric.",
  },
  "subdomain-power:souls:touch-the-spirit-world": {
    id: "subdomain-power:souls:touch-the-spirit-world",
    name: "Touch the Spirit World",
    bucket: "subsystem",
    note: "Touch power granting a weapon the ability to affect incorporeal creatures for a limited duration; a rules-exception weapon-quality grant, not a Change-shaped bonus.",
  },
  "subdomain-power:thirst:withering-nimbus": {
    id: "subdomain-power:thirst:withering-nimbus",
    name: "Withering Nimbus",
    bucket: "situational",
    note: "Emitted nimbus; the per-round damage to aquatic/water-subtype creatures inside it is scoped to enemy state and the nimbus's active window.",
  },
  "subdomain-power:thorns:cruel-thicket": {
    id: "subdomain-power:thorns:cruel-thicket",
    name: "Cruel Thicket",
    bucket: "situational",
    note: "Activated 5-foot-radius hazard lasting 1 minute; the bleed damage and difficult terrain apply to creatures moving through it, not an unconditional bonus to the cleric.",
  },
  "subdomain-power:tyranny:tyrannical-strike": {
    id: "subdomain-power:tyranny:tyrannical-strike",
    name: "Tyrannical Strike",
    bucket: "subsystem",
    note: "On a successful melee hit, forgoes damage to instead inflict a greater-command-style effect on the struck creature; a mind-control effect on the enemy, not a bonus number on the cleric.",
  },
  "subdomain-power:undead:death-s-kiss": {
    id: "subdomain-power:undead:death-s-kiss",
    name: "Death's Kiss",
    bucket: "subsystem",
    note: "Melee touch attack that reclassifies a target as undead for positive/negative energy interactions for a limited duration; a rules-exception effect on the target, not a bonus number on the cleric.",
  },
  "subdomain-power:wards:warding-rune": {
    id: "subdomain-power:wards:warding-rune",
    name: "Warding Rune",
    bucket: "subsystem",
    note: "Triggered when a creature is damaged by the cleric's own blast rune; imposes a sanctuary-style effect on that creature's ability to attack the cleric, a condition effect rather than a Change-shaped bonus.",
  },
  szRzBgTW01Vov922: {
    id: "szRzBgTW01Vov922",
    name: "Serpent Companion",
    bucket: "subsystem",
    note: "Grants a viper/constrictor snake companion, effective druid level = cleric level - 2 — wired via COMPANION_EFFECT_CLASS_FEATURES onto the tracked companion's stat block, gated on the Venom subdomain tag. Despite the ability's own name, this is granted by the VENOM subdomain (Scalykind's subdomain); there is no 'Serpent' subdomain in the vendored data.",
  },
  t3eiENbbesGZBnc2: {
    id: "t3eiENbbesGZBnc2",
    name: "Holy Lance",
    bucket: "subsystem",
    note: "Grants the holy weapon special quality to a touched weapon for a limited duration, uses-per-day pool; a rules-exception weapon-quality grant, not a Change-shaped bonus.",
  },
  wK9bxQqe49GfT9xh: {
    id: "wK9bxQqe49GfT9xh",
    name: "Scythe of Evil",
    bucket: "subsystem",
    note: "Grants the unholy weapon special quality to a touched weapon for a limited duration, uses-per-day pool; a rules-exception weapon-quality grant, not a Change-shaped bonus.",
  },
};
