/**
 * Classification shard for vendored racial traits whose `race` starts with
 * H-R — see `./index.ts` for the shard convention and `./types.ts`
 * for the bucket rubric.
 */

import type { RacialTraitClassificationEntry } from "./types.js";

export const RACIAL_TRAIT_CLASSIFICATION_RACES_HR: Readonly<
  Record<string, RacialTraitClassificationEntry>
> = {
  uPfUcu59YuGhaoFX: {
    id: "uPfUcu59YuGhaoFX",
    race: "Half-Elf",
    name: "Behind the Veil (Half-Elf)",
    bucket: "situational",
    note: "Conditional on benefiting from concealment or cover, a state the static sheet does not track.",
  },
  l3nc7GFcj5yKPNlS: {
    id: "l3nc7GFcj5yKPNlS",
    race: "Half-Elf",
    name: "Darklands Guide (Half-Elf)",
    bucket: "blocked",
    note: "The save bonus is scoped to traps and hazards, which SAVE_CATEGORIES has no entry for, and the initiative bonus is conditional on being underground besides.",
  },
  rqHG1kYNsazeEwDc: {
    id: "rqHG1kYNsazeEwDc",
    race: "Half-Elf",
    name: "Dimdweller (Half-Elf)",
    bucket: "situational",
    note: "Conditional on concealment from darkness or dim light, a state the static sheet does not track.",
  },
  nOZ9tdmFZ4sWgXv0: {
    id: "nOZ9tdmFZ4sWgXv0",
    race: "Half-Elf",
    name: "Elf-Scorned",
    bucket: "situational",
    note: "Scoped to a property of the opponent (being an elf), not the effect, so it cannot be an unconditional Change.",
  },
  "3e5TxgPBqVgYqWmQ": {
    id: "3e5TxgPBqVgYqWmQ",
    race: "Half-Elf",
    name: "Eye for Opportunity",
    bucket: "situational",
    note: "Scoped to attacks of opportunity specifically, narrower than the whole attack target.",
  },
  LgS28VNVT3n6hCKH: {
    id: "LgS28VNVT3n6hCKH",
    race: "Half-Elf",
    name: "Flexible Half-Breed",
    bucket: "situational",
    note: "The Disguise bonus only applies while using the once-per-day alter self spell-like ability to appear as the chosen race.",
  },
  rgteIX0WVM5v9APV: {
    id: "rgteIX0WVM5v9APV",
    race: "Half-Elf",
    name: "Hidden Half-Breed",
    bucket: "situational",
    note: "Scoped to passing as a full-blooded drow, elf, or human specifically, narrower than the whole Bluff/Disguise target.",
  },
  aMGMC5XWT62jCouw: {
    id: "aMGMC5XWT62jCouw",
    race: "Half-Elf",
    name: "Inspire Imitation",
    bucket: "situational",
    note: "A swift-action ability that grants an ally a bonus after the character succeeds at a check, not an unconditional Change on the character's own sheet.",
  },
  CHswbETjpZZan3xy: {
    id: "CHswbETjpZZan3xy",
    race: "Half-Elf",
    name: "Reflexive Improvisation",
    bucket: "situational",
    note: "Scoped to untrained skill checks only, a trained/untrained distinction the sheet does not track per roll.",
  },
  "7uXh24sfHB4VJBhL": {
    id: "7uXh24sfHB4VJBhL",
    race: "Half-Elf",
    name: "Round Ears",
    bucket: "situational",
    note: "The Disguise bonus is conditional on trying to appear human specifically; the granted skilled trait is a separate feature grant, not this entry's flagged number.",
  },
  "5GahxXf5d4aAosVh": {
    id: "5GahxXf5d4aAosVh",
    race: "Half-Elf",
    name: "Shadowhunter (Half-Elf)",
    bucket: "blocked",
    note: "The negative-levels save scope has no SAVE_CATEGORIES entry, and the incorporeal-damage and undead-healing-rate clauses are rules exceptions with no Change-shaped number.",
  },
  Wbsmn2PqBb1r519r: {
    id: "Wbsmn2PqBb1r519r",
    race: "Half-Elf",
    name: "Voice in the Darkness (Half-Elf)",
    bucket: "situational",
    note: "Conditional on being in dim light or darker, a state the static sheet does not track.",
  },
  lBS1mSrNfigoro8L: {
    id: "lBS1mSrNfigoro8L",
    race: "Half-Elf,Darkborn",
    name: "Thinblood Resistance",
    bucket: "numeric",
    note: "Poison and disease are both in SAVE_CATEGORIES and the note text is not yet promoted; propose a save-note entry covering both scopes.",
  },
  RX8XCS2CoFhYwiBG: {
    id: "RX8XCS2CoFhYwiBG",
    race: "Half-Elf,Snowborn",
    name: "Cold-Honed",
    bucket: "blocked",
    note: "The Fortitude bonus is scoped to nonlethal damage from cold climates, which SAVE_CATEGORIES has no entry for.",
  },
  WyTkLcKys4Jy29Q2: {
    id: "WyTkLcKys4Jy29Q2",
    race: "Half-Elf,Wildborn",
    name: "Jungle Affinity",
    bucket: "situational",
    note: "Conditional on being within jungle terrain, a state the static sheet does not track.",
  },
  oEcmHgII4hNU8UJY: {
    id: "oEcmHgII4hNU8UJY",
    race: "Half-Orc",
    name: "Behind the Veil (Half-Orc)",
    bucket: "situational",
    note: "Conditional on benefiting from concealment or cover, a state the static sheet does not track.",
  },
  rmiLxAFaM1Sztn7w: {
    id: "rmiLxAFaM1Sztn7w",
    race: "Half-Orc",
    name: "Cavewight",
    bucket: "situational",
    note: "Conditional on being underground, a state the static sheet does not track.",
  },
  CTGG4ZOaOIvJj09S: {
    id: "CTGG4ZOaOIvJj09S",
    race: "Half-Orc",
    name: "Dimdweller (Half-Orc)",
    bucket: "situational",
    note: "Conditional on concealment from darkness or dim light, a state the static sheet does not track.",
  },
  "4qveM7bUNizrOvka": {
    id: "4qveM7bUNizrOvka",
    race: "Half-Orc",
    name: "Divided Attention",
    bucket: "situational",
    note: "Scoped to foes who are flanking the character, a combat state the static sheet does not track.",
  },
  VavtvA1snnAQD7lX: {
    id: "VavtvA1snnAQD7lX",
    race: "Half-Orc",
    name: "Dragon Slayer",
    bucket: "situational",
    note: "Scoped to a property of the opponent (being a dragon), not the effect, so it cannot be an unconditional Change.",
  },
  "7JHnhD96PeWEnf7U": {
    id: "7JHnhD96PeWEnf7U",
    race: "Half-Orc",
    name: "Feral",
    bucket: "subsystem",
    note: "Grants two other alternate racial traits (forest walker, toothy) rather than carrying its own number.",
  },
  NApPIjNkVNBxzQS3: {
    id: "NApPIjNkVNBxzQS3",
    race: "Half-Orc",
    name: "Gatecrasher",
    bucket: "situational",
    note: "Scoped to breaking objects and sunder attempts specifically, narrower than the whole Strength-check and CMB targets.",
  },
  nmthVcIFBg9PNqhb: {
    id: "nmthVcIFBg9PNqhb",
    race: "Half-Orc",
    name: "Hatred (Half-Orc)",
    bucket: "situational",
    note: "Scoped to a property of the opponent (dwarf/elf/human subtype), not the effect, so it cannot be an unconditional Change.",
  },
  VQJKPH7YtgzXQj4J: {
    id: "VQJKPH7YtgzXQj4J",
    race: "Half-Orc",
    name: "Inured",
    bucket: "blocked",
    note: "Sanity damage has no SAVE_CATEGORIES entry.",
  },
  uDlZlUlvcf9EE1ys: {
    id: "uDlZlUlvcf9EE1ys",
    race: "Half-Orc",
    name: "Monstrous Sympathy",
    bucket: "situational",
    note: "Scoped to a property of the opponent (being evil), not the effect, so it cannot be an unconditional Change.",
  },
  lwZTXQ8zz2awYQh9: {
    id: "lwZTXQ8zz2awYQh9",
    race: "Half-Orc",
    name: "Pain Tolerance",
    bucket: "blocked",
    note: "DR against nonlethal damage has no bypass-shaped target to carry it, and the pain descriptor has no SAVE_CATEGORIES entry.",
  },
  vZvTS5zeW4AVNARd: {
    id: "vZvTS5zeW4AVNARd",
    race: "Half-Orc",
    name: "Shadowhunter (Half-Orc)",
    bucket: "blocked",
    note: "The negative-levels save scope has no SAVE_CATEGORIES entry, and the incorporeal-damage and undead-healing-rate clauses are rules exceptions with no Change-shaped number.",
  },
  htWm9bSBUYHvx4SY: {
    id: "htWm9bSBUYHvx4SY",
    race: "Half-Orc",
    name: "Voice in the Darkness (Half-Orc)",
    bucket: "situational",
    note: "Conditional on being in dim light or darker, a state the static sheet does not track.",
  },
  VmHT9b6yPqZD8typ: {
    id: "VmHT9b6yPqZD8typ",
    race: "Half-Orc,Gloomkin",
    name: "Evader (Gloomkin)",
    bucket: "situational",
    note: "Conditional on being underground, a state the static sheet does not track.",
  },
  a95VioTuysgFg9EZ: {
    id: "a95VioTuysgFg9EZ",
    race: "Halfling",
    name: "Adaptable Luck",
    bucket: "situational",
    note: "A 3/day resource gating the bonus, not an always-on Change.",
  },
  MNzGZ2cMsU7bh6RN: {
    id: "MNzGZ2cMsU7bh6RN",
    race: "Halfling",
    name: "Behind the Veil (Halfling)",
    bucket: "situational",
    note: "Conditional on benefiting from concealment or cover, a state the static sheet does not track.",
  },
  YZ1WIRlAYAAfvbBR: {
    id: "YZ1WIRlAYAAfvbBR",
    race: "Halfling",
    name: "Creepy Doll",
    bucket: "subsystem",
    note: "Grants a Stealth-without-concealment rules exception (a freeze-like ability) and negates an unmodeled Intimidate size penalty, neither a Change-shaped number.",
  },
  s07V8lcVJX3IkC6l: {
    id: "s07V8lcVJX3IkC6l",
    race: "Halfling",
    name: "Danger Detection",
    bucket: "situational",
    note: "Scoped to noticing Stealth, weapon-draws, and hidden traps specifically, narrower than the whole Perception target.",
  },
  p95hpIAifEyv3asz: {
    id: "p95hpIAifEyv3asz",
    race: "Halfling",
    name: "Dimdweller (Halfling)",
    bucket: "situational",
    note: "Conditional on concealment from darkness or dim light, a state the static sheet does not track.",
  },
  KqmKgeDMWBIS2qNP: {
    id: "KqmKgeDMWBIS2qNP",
    race: "Halfling",
    name: "Festive",
    bucket: "situational",
    note: "A once-per-day resource granted to an ally, not an always-on Change on the character's own sheet.",
  },
  D7JILr96IKHWN4vQ: {
    id: "D7JILr96IKHWN4vQ",
    race: "Halfling",
    name: "Halfling Jinx",
    bucket: "subsystem",
    note: "Grants an at-will Su ability that penalizes a target creature's saves, not a bonus to the character's own stats.",
  },
  cblSp9CRry0z790A: {
    id: "cblSp9CRry0z790A",
    race: "Halfling",
    name: "Human Shadow",
    bucket: "situational",
    note: "Conditional on being within 30 feet of a human, a state the static sheet does not track.",
  },
  Ral2Kd4diC6McjqC: {
    id: "Ral2Kd4diC6McjqC",
    race: "Halfling",
    name: "Joyous Companion",
    bucket: "situational",
    note: "Conditional on casting an abjuration or emotion spell, and grants the bonus to adjacent allies rather than the character.",
  },
  NXo6ienQYsNzSdIr: {
    id: "NXo6ienQYsNzSdIr",
    race: "Halfling",
    name: "Low Blow",
    bucket: "blocked",
    note: "critConfirm is not a target compute.ts applies, and the bonus is scoped to opponents larger than the character besides.",
  },
  "27NShcUlmj6wDaAW": {
    id: "27NShcUlmj6wDaAW",
    race: "Halfling",
    name: "Shadowhunter (Halfling)",
    bucket: "blocked",
    note: "The negative-levels save scope has no SAVE_CATEGORIES entry, and the incorporeal-damage and undead-healing-rate clauses are rules exceptions with no Change-shaped number.",
  },
  lTBjKajyJWEfK2nA: {
    id: "lTBjKajyJWEfK2nA",
    race: "Halfling",
    name: "Skulker",
    bucket: "situational",
    note: "Scoped to foes denied their Dexterity bonus to AC, a combat state the static sheet does not track.",
  },
  iSHRZjOWa5TnYKXe: {
    id: "iSHRZjOWa5TnYKXe",
    race: "Halfling",
    name: "Underfoot",
    bucket: "situational",
    note: "Scoped to foes larger than the character and to trample attacks specifically, states the static sheet does not track.",
  },
  NZqjZG4BTjWh0ZaQ: {
    id: "NZqjZG4BTjWh0ZaQ",
    race: "Halfling",
    name: "Underfoot Dodger",
    bucket: "situational",
    note: "Scoped to moving through the spaces of larger foes specifically, narrower than the whole Acrobatics target.",
  },
  LTXZC6b60cP69ZeD: {
    id: "LTXZC6b60cP69ZeD",
    race: "Hobgoblin",
    name: "Magehunter",
    bucket: "situational",
    note: "Scoped to a property of the opponent (arcane spellcasting) and to identifying a spell as it is cast, neither an unconditional Change.",
  },
  d6YoCC2UVK8jUmf8: {
    id: "d6YoCC2UVK8jUmf8",
    race: "Hobgoblin",
    name: "Pit Boss",
    bucket: "situational",
    note: "Scoped to disarm and trip attempts made with a whip specifically, narrower than the whole CMB target.",
  },
  KEijNXH9Jnwa1Ggb: {
    id: "KEijNXH9Jnwa1Ggb",
    race: "Human",
    name: "Dragon Scholar",
    bucket: "blocked",
    note: "The caster-level-vs-SR bonus targets cl, which compute.ts does not apply, and the Knowledge (arcana) bonus is scoped to dragon-related checks, narrower than the skill's whole target.",
  },
  g9H3WgBwfJUfaU4m: {
    id: "g9H3WgBwfJUfaU4m",
    race: "Human",
    name: "Heart of the Snows",
    bucket: "blocked",
    note: "The Fortitude bonus is scoped to cold-climate effects, which SAVE_CATEGORIES has no entry for, and the CMD bonus is scoped to trip specifically, which cmd has no maneuver-specific sub-target for.",
  },
  DsH7y38wfWDPCINE: {
    id: "DsH7y38wfWDPCINE",
    race: "Human",
    name: "Heart of the Sun",
    bucket: "blocked",
    note: "The Fortitude bonus is scoped to hot-climate effects, which SAVE_CATEGORIES has no entry for, and to poison from swarms and vermin specifically, narrower than the poison category the vocabulary offers.",
  },
  wDBLqYPQAER9KNFY: {
    id: "wDBLqYPQAER9KNFY",
    race: "Human",
    name: "Innovative",
    bucket: "blocked",
    note: "The Charisma-skill bonus targets chaSkills, which compute.ts does not apply, and the Knowledge/Spellcraft bonus is scoped to research and identification uses, narrower than the skills' whole targets.",
  },
  DuDqaejBaS9O9bSn: {
    id: "DuDqaejBaS9O9bSn",
    race: "Human",
    name: "Institutional Memory",
    bucket: "situational",
    note: "Scoped to Knowledge checks about the character's own organizations, guilds, or religions specifically, a subject-matter distinction the sheet does not track.",
  },
  dWFPhuI7Vt2QDf0C: {
    id: "dWFPhuI7Vt2QDf0C",
    race: "Human",
    name: "One of the Multitude",
    bucket: "situational",
    note: "Scoped to attacks of opportunity made while flanking and to being within 10 feet of two humanoids, states the static sheet does not track.",
  },
  XOISvyFa8ZziUEak: {
    id: "XOISvyFa8ZziUEak",
    race: "Human",
    name: "Psychic Defense",
    bucket: "blocked",
    note: "Psychic spells and spell-like abilities have no SAVE_CATEGORIES entry; spell and sla are unscoped by school or tradition.",
  },
  s8ViF8uZdu09fKJw: {
    id: "s8ViF8uZdu09fKJw",
    race: "Human",
    name: "Rationalize",
    bucket: "blocked",
    note: "Sanity damage has no SAVE_CATEGORIES entry.",
  },
  VeT8BWM5gpiTLijD: {
    id: "VeT8BWM5gpiTLijD",
    race: "Human",
    name: "Self-Made Fate",
    bucket: "blocked",
    note: "Divine spells and SLAs have no SAVE_CATEGORIES entry, and the aeon/psychopomp/alignment-subtype scope is a property of the opponent besides.",
  },
  JurU0JeI27uBxqLH: {
    id: "JurU0JeI27uBxqLH",
    race: "Human",
    name: "Tribalistic",
    bucket: "situational",
    note: "Scoped to using aid another to help humans of the same ethnicity specifically, a combination of action and opponent property the sheet does not track.",
  },
  AqWhtrTEaKeJ9qZ6: {
    id: "AqWhtrTEaKeJ9qZ6",
    race: "Human",
    name: "Unstoppable Magic",
    bucket: "blocked",
    note: "The bonus targets cl, which compute.ts does not apply.",
  },
  zZg9G22ykBGKWCuw: {
    id: "zZg9G22ykBGKWCuw",
    race: "Ifrit",
    name: "Desert Mirage",
    bucket: "blocked",
    note: "The save bonus is scoped to starvation and thirst, which SAVE_CATEGORIES has no entry for, and the Stealth bonus is separately conditional on being in a desert.",
  },
  s9lJ4v97vOu0TiBP: {
    id: "s9lJ4v97vOu0TiBP",
    race: "Ifrit",
    name: "Fire-Starter",
    bucket: "situational",
    note: "A once-per-creature conditional bonus on the next roll after igniting a target, not an always-on Change.",
  },
  Rx1ayk8e3zpDoslL: {
    id: "Rx1ayk8e3zpDoslL",
    race: "Ifrit",
    name: "Forge-Hardened",
    bucket: "blocked",
    note: "Craft (armor and weapons) is a parameterized subskill with no generic skill.crf target, and fatigue/exhaustion have no SAVE_CATEGORIES entry.",
  },
  vyJuXppTrAQZWfE0: {
    id: "vyJuXppTrAQZWfE0",
    race: "Kobold",
    name: "Echo Whistler",
    bucket: "situational",
    note: "A 3/day Bluff bonus, conditional on being in tunnels or an echoing structure, not an always-on Change.",
  },
  DJJBP96MRHv0t2Ii: {
    id: "DJJBP96MRHv0t2Ii",
    race: "Kobold",
    name: "Shoulder to Shoulder",
    bucket: "situational",
    note: "Conditional on sharing a space with another kobold with this trait or on using aid another, states the static sheet does not track.",
  },
  E8oONe3xMLCowfoc: {
    id: "E8oONe3xMLCowfoc",
    race: "Lashunta",
    name: "Insidious Telepathy",
    bucket: "blocked",
    note: "The bonus targets chaSkills, which compute.ts does not apply, on top of being conditional on active telepathic communication.",
  },
  btAWWOZmbI05bcPK: {
    id: "btAWWOZmbI05bcPK",
    race: "Merfolk",
    name: "Unexpected Ally",
    bucket: "situational",
    note: "Scoped to Diplomacy checks made to influence attitude specifically, narrower than the whole Diplomacy target, and to using aid another besides.",
  },
  "7LMPWVsKB0u2krDQ": {
    id: "7LMPWVsKB0u2krDQ",
    race: "Nagaji",
    name: "Serpent Affinity",
    bucket: "blocked",
    note: "The caster-level bonus has no cl route since compute.ts does not apply that target, and it only applies to one domain's powers for clerics who have it.",
  },
  A7bikGavod3dmWDl: {
    id: "A7bikGavod3dmWDl",
    race: "Orc",
    name: "Feral",
    bucket: "situational",
    note: "Scoped to melee attacks and damage while at negative hit points, a combat state the static sheet does not track.",
  },
  yfJ0rhcQv12UHtau: {
    id: "yfJ0rhcQv12UHtau",
    race: "Orc",
    name: "Reckless Climber",
    bucket: "situational",
    note: "Scoped to climbing without rope and to maintaining balance specifically, narrower than the whole Climb and Acrobatics targets.",
  },
  "20tBxcHiLRujQYvC": {
    id: "20tBxcHiLRujQYvC",
    race: "Oread",
    name: "Crystalline Form",
    bucket: "situational",
    note: "Scoped to ray attacks specifically, an attack-type distinction the static sheet does not track for AC.",
  },
  XXB7Lnp9pMBlS5Or: {
    id: "XXB7Lnp9pMBlS5Or",
    race: "Oread",
    name: "Mountain-Born",
    bucket: "blocked",
    note: "The save bonus is scoped to altitude fatigue and sickness, which SAVE_CATEGORIES has no entry for.",
  },
  dfqSRTRN0zf2BRS0: {
    id: "dfqSRTRN0zf2BRS0",
    race: "Oread",
    name: "Oread Gem Magic",
    bucket: "subsystem",
    note: "Grants a gem-component spell-augmentation system with dozens of per-spell effects, not reducible to a Change.",
  },
  sXLcCq4nFkeFlG5i: {
    id: "sXLcCq4nFkeFlG5i",
    race: "Ratfolk",
    name: "Cornered Fury (Ratfolk)",
    bucket: "situational",
    note: "Scoped to being at or below half HP with no conscious ally within 30 feet, a combat state the static sheet does not track.",
  },
  "4UPvvBKe9UXgCLj2": {
    id: "4UPvvBKe9UXgCLj2",
    race: "Ratfolk",
    name: "Unnatural",
    bucket: "blocked",
    note: "The Charisma-skill penalty targets chaSkills, which compute.ts does not apply, and the dodge bonus is scoped to a property of the opponent (being an animal) besides.",
  },
};
