/**
 * Classification shard for vendored racial traits whose `race` starts with
 * E-G — see `./index.ts` for the shard convention and `./types.ts`
 * for the bucket rubric.
 */

import type { RacialTraitClassificationEntry } from "./types.js";

export const RACIAL_TRAIT_CLASSIFICATION_RACES_EG: Readonly<
  Record<string, RacialTraitClassificationEntry>
> = {
  crZ8xD4Vlvu0pk4U: {
    id: "crZ8xD4Vlvu0pk4U",
    race: "Elf",
    name: "Ageless Patience",
    bucket: "situational",
    note: "Real +2 skills bonus but scoped to taking 20, a resolution mode the static sheet has no way to detect.",
  },
  Yo8LrR6TY4Hq0T6A: {
    id: "Yo8LrR6TY4Hq0T6A",
    race: "Elf",
    name: "Arcane Focus",
    bucket: "situational",
    note: "Concentration bonus scoped to casting defensively; concentration is itself a target the engine never consumes (targets.ts).",
  },
  p61CAuVRzQhhTb2r: {
    id: "p61CAuVRzQhhTb2r",
    race: "Elf",
    name: "Behind the Veil (Elf)",
    bucket: "situational",
    note: "Bluff/Sleight of Hand bonus scoped to having concealment or cover, a battlefield state the static sheet cannot detect.",
  },
  MjM2hFpV8MHQTEwC: {
    id: "MjM2hFpV8MHQTEwC",
    race: "Elf",
    name: "Creepy",
    bucket: "situational",
    note: "Intimidate bonus scoped to the demoralize use of the skill; the enemy save penalty half is a DC effect on OTHERS, not a Change on this sheet.",
  },
  StOjhD9mqHZqSELy: {
    id: "StOjhD9mqHZqSELy",
    race: "Elf",
    name: "Desert Runner",
    bucket: "numeric",
    note: "Fort save is scoped to fatigue, exhaustion, starvation, thirst, and temperature; fatigue/exhaustion now has a SAVE_CATEGORIES entry and the note text matches a VENDORED_RACIAL_TRAIT_SAVE_NOTES key exactly, so that part is wired via collect.ts. Starvation and thirst are Constitution checks rather than saves, and temperature has no category, so both stay prose; the duplicate conChecks-targeted copy of the same text is likewise unwired (conChecks is an unapplied target, targets.ts).",
  },
  uSED8jnh3FejGkiw: {
    id: "uSED8jnh3FejGkiw",
    race: "Elf",
    name: "Devoted Companion",
    bucket: "situational",
    note: "Attack and caster-level bonus scoped to an ally's below-half-HP state, which the static sheet cannot detect, and cl is itself unapplied.",
  },
  gt6rBTzdG0Cub2lr: {
    id: "gt6rBTzdG0Cub2lr",
    race: "Elf",
    name: "Dimdweller (Elf)",
    bucket: "situational",
    note: "Intimidate/Perception/Stealth bonus scoped to benefiting from dim-light or dark concealment, a lighting state the sheet cannot detect.",
  },
  x3JL4aygweVL6wvo: {
    id: "x3JL4aygweVL6wvo",
    race: "Elf",
    name: "Disinterested Observer",
    bucket: "situational",
    note: "Attack and skill bonus scoped to acting as part of a readied action, an action type the static sheet cannot detect.",
  },
  pslPkIsSzbeUteHG: {
    id: "pslPkIsSzbeUteHG",
    race: "Elf",
    name: "Elven Arrogance",
    bucket: "blocked",
    note: "Save bonus is scoped to enchantments cast by non-elf humanoids specifically, an attacker-property carve-out the vocabulary explicitly excludes (vendored-trait-save-notes.ts).",
  },
  O4c045wJE5lLweg3: {
    id: "O4c045wJE5lLweg3",
    race: "Elf",
    name: "Eternal Grudge",
    bucket: "situational",
    note: "Attack bonus scoped to the dwarf and orc subtypes; favored-enemy-shaped bonuses against a creature subtype have no modeled target.",
  },
  zgkOFWDlY1YksSel: {
    id: "zgkOFWDlY1YksSel",
    race: "Elf",
    name: "Fey-Sighted",
    bucket: "subsystem",
    note: "Wired as a castable constant spell-like-ability row (spell-like-abilities/racial.ts); still no Change-shaped number.",
  },
  MQnZG0JAiMqtO91T: {
    id: "MQnZG0JAiMqtO91T",
    race: "Elf",
    name: "Frostmelding",
    bucket: "subsystem",
    note: "Wired as a castable spell-like-ability row (spell-like-abilities/racial.ts), attached to this trait's own daily-use pool; still no Change-shaped number.",
  },
  XWa9YUpaCR5IIqUp: {
    id: "XWa9YUpaCR5IIqUp",
    race: "Elf",
    name: "Keeper of Secrets",
    bucket: "situational",
    note: "Bluff/Linguistics bonus scoped to omitting or covering up facts, and the enchantment DC bump is scoped to humanoid targets with no matching engine target either.",
  },
  "88rQ9iJdzI8Cmr18": {
    id: "88rQ9iJdzI8Cmr18",
    race: "Elf",
    name: "Light against Darkness",
    bucket: "situational",
    note: "Attack bonus scoped to the demon subtype; favored-enemy-shaped bonuses against a creature subtype have no modeled target.",
  },
  RKMn7UZjPlPPU4Nv: {
    id: "RKMn7UZjPlPPU4Nv",
    race: "Elf",
    name: "Perfect",
    bucket: "numeric",
    note: "Save bonus is scoped to the transmutation school, a real SAVE_CATEGORIES entry; the note text matches a VENDORED_RACIAL_TRAIT_SAVE_NOTES key exactly, so it is wired via collect.ts. The Bluff/Diplomacy half is separately scoped to humanoid targets and stays unwired.",
  },
  cL7K05jKkXxOmOt5: {
    id: "cL7K05jKkXxOmOt5",
    race: "Elf",
    name: "Retreat Magic",
    bucket: "blocked",
    note: "This is a caster LEVEL bonus (range/duration), not a caster-level check — cl stays a deliberately unapplied target (moving it would change durations/damage everywhere, spell-dcs.ts) — and it's further scoped to conjuration and illusion spells specifically, which no cl-shaped vocabulary reaches either.",
  },
  agovSwSID6zOPIDN: {
    id: "agovSwSID6zOPIDN",
    race: "Elf",
    name: "Sense Thoughts",
    bucket: "subsystem",
    note: "Wired as a castable spell-like-ability row (spell-like-abilities/racial.ts), attached to this trait's own daily-use pool; still no Change-shaped number.",
  },
  A25WUoiogbprnnzS: {
    id: "A25WUoiogbprnnzS",
    race: "Elf",
    name: "Shadowhunter (Elf)",
    bucket: "subsystem",
    note: "Incorporeal-damage rule and doubled undead-ability-damage healing rate are rules exceptions with no Change target; the negative-level save bonus is also out of vocabulary (negative levels excluded).",
  },
  "7ungQuC9iDjjX2vP": {
    id: "7ungQuC9iDjjX2vP",
    race: "Elf",
    name: "Silent Hunter",
    bucket: "situational",
    note: "Reduces the Stealth-while-moving penalty, scoped to the moving-and-running action state the static sheet cannot detect.",
  },
  SyXfxr53mzenpNu5: {
    id: "SyXfxr53mzenpNu5",
    race: "Elf",
    name: "Urbanite",
    bucket: "situational",
    note: "Diplomacy/Sense Motive bonus scoped to gathering information and reading a social situation, narrower uses than the whole skill.",
  },
  QLhGfJhpG2KXm17L: {
    id: "QLhGfJhpG2KXm17L",
    race: "Elf",
    name: "Vigilance",
    bucket: "situational",
    note: "Dodge AC bonus scoped to chaotic creatures; a creature-alignment-scoped bonus has no modeled target.",
  },
  Lu5fwnybIjW7E4KB: {
    id: "Lu5fwnybIjW7E4KB",
    race: "Elf",
    name: "Voice in the Darkness (Elf)",
    bucket: "situational",
    note: "Intimidate/Stealth bonus scoped to dim light or darker conditions, a lighting state the static sheet cannot detect.",
  },
  b4nkYIUM9HzTUL76: {
    id: "b4nkYIUM9HzTUL76",
    race: "Fetchling",
    name: "Whispers from Shadow",
    bucket: "situational",
    note: "Bluff bonus scoped to lying and wanting to be believed, one use of the skill rather than the whole of it.",
  },
  fVRCBv9JtvU8M6x2: {
    id: "fVRCBv9JtvU8M6x2",
    race: "Ganzi",
    name: "Expanded Oddities",
    bucket: "subsystem",
    note: "A GM-rolled or player-chosen grab-bag of distinct abilities (natural weapon, ranged attack, save bonus, SLA, aura, reactive confusion); the vendored note itself says the option must be picked and set manually.",
  },
  g6M0a4JgcPgjdjJT: {
    id: "g6M0a4JgcPgjdjJT",
    race: "Gathlain",
    name: "Fey Resilience",
    bucket: "numeric",
    note: "Unconditional DR 1/cold iron scaling with HD; dr.cold-iron is an applied target (targets.ts) and the HD-scaling formula is expressible.",
  },
  hvgsnryqs9MglaYI: {
    id: "hvgsnryqs9MglaYI",
    race: "Gathlain",
    name: "Flighty",
    bucket: "subsystem",
    note: "Grants Perception as a class skill, a rules exception with no Change target; the save bonus is scoped to the fascination/pattern subschool, which is excluded from the save vocabulary.",
  },
  hJ17KnzPNXh1xWm2: {
    id: "hJ17KnzPNXh1xWm2",
    race: "Gathlain",
    name: "Intense Curiosity",
    bucket: "situational",
    note: "Perception/Survival bonus scoped to taking 20 to track or predict weather, both a resolution mode and a narrower use than the whole skill.",
  },
  b8mD388daeaoKidm: {
    id: "b8mD388daeaoKidm",
    race: "Gathlain",
    name: "Natural Bounty",
    bucket: "subsystem",
    note: "Wired as castable spell-like-ability rows (goodberry, then plant growth and heroes' feast at higher levels, spell-like-abilities/racial.ts), attached to this trait's own daily-use pool; still no Change-shaped number.",
  },
  "7VH3Akj7yTzcw8Qx": {
    id: "7VH3Akj7yTzcw8Qx",
    race: "Gathlain",
    name: "Soaring Agility",
    bucket: "situational",
    note: "Dodge AC bonus scoped to attacks originating 20+ ft below the character, a battlefield geometry state the static sheet cannot detect.",
  },
  d0h0dzcrBnA3b3Ts: {
    id: "d0h0dzcrBnA3b3Ts",
    race: "Ghoran",
    name: "Disgusting",
    bucket: "situational",
    note: "Escape Artist/CMB bonus scoped to escaping a grapple from a bite-and-grab creature, narrower than the whole skill or maneuver.",
  },
  "2y6Om4T1c7V7Stll": {
    id: "2y6Om4T1c7V7Stll",
    race: "Ghoran",
    name: "Magical Absorption",
    bucket: "subsystem",
    note: "Event-triggered HP regen on a successful save against a spell or spell-like ability, capped per day by level; a reactive resource, not a static Change.",
  },
  zbTaOzflIhoXTqrR: {
    id: "zbTaOzflIhoXTqrR",
    race: "Ghoran",
    name: "Natural Camouflage",
    bucket: "situational",
    note: "Stealth bonus scoped to a chosen terrain type, a location state the static sheet cannot detect.",
  },
  v5W731SKm6CeoMO4: {
    id: "v5W731SKm6CeoMO4",
    race: "Ghoran",
    name: "Spelleater",
    bucket: "subsystem",
    note: "Wired as a castable spell-like-ability row (dispel magic once per day, spell-like-abilities/racial.ts); the dispel-check bonus now has a clCheck.dispel target to land on, but it's conditional on the character's favored class being a spellcasting class, a build-time condition this trait's entry has no way to gate on.",
  },
  FJHJNZFjwC1tvKnM: {
    id: "FJHJNZFjwC1tvKnM",
    race: "Gillman",
    name: "Slimehunter",
    bucket: "blocked",
    note: "Save bonus is scoped to aboleth spells, SLAs, and supernatural abilities, an attacker-property scope the save vocabulary explicitly excludes.",
  },
  wo6yWJXwBCZjPNHm: {
    id: "wo6yWJXwBCZjPNHm",
    race: "Gillman",
    name: "Truthseer",
    bucket: "blocked",
    note: "The +2-vs-everyone-but-aboleths and -2-vs-aboleths pair is the same one-category-two-totals problem as the standard Gillman entry, excluded per vendored-trait-save-notes.ts.",
  },
  DygcxOxDwuPpJmm6: {
    id: "DygcxOxDwuPpJmm6",
    race: "Gnome",
    name: "Behind the Veil (Gnome)",
    bucket: "situational",
    note: "Bluff/Sleight of Hand bonus scoped to having concealment or cover, a battlefield state the static sheet cannot detect.",
  },
  TQUVpXNu7bAbTEAy: {
    id: "TQUVpXNu7bAbTEAy",
    race: "Gnome",
    name: "Bond to the Land",
    bucket: "situational",
    note: "Dodge AC bonus scoped to a chosen terrain type, a location state the static sheet cannot detect.",
  },
  yXdKpYeTHVOwCHvS: {
    id: "yXdKpYeTHVOwCHvS",
    race: "Gnome",
    name: "Dimdweller (Gnome)",
    bucket: "situational",
    note: "Intimidate/Perception/Stealth bonus scoped to benefiting from dim-light or dark concealment, a lighting state the sheet cannot detect.",
  },
  BO8RYKHYIldtwfI1: {
    id: "BO8RYKHYIldtwfI1",
    race: "Gnome",
    name: "Dirty Trickster",
    bucket: "numeric",
    note: "CMB bonus scoped to the dirty trick maneuver, now a real MANEUVER_CATEGORIES entry; the note text matches a VENDORED_RACIAL_TRAIT_MANEUVER_NOTES key exactly, so it is wired via collect.ts.",
  },
  wNE1rlrOUrO4IKnP: {
    id: "wNE1rlrOUrO4IKnP",
    race: "Gnome",
    name: "Fairy Catcher",
    bucket: "blocked",
    note: "Both the save and CL-check bonuses are scoped to fey specifically, an attacker-property scope the vocabulary explicitly excludes; the skill half is scoped to fey targets too.",
  },
  AEFbxJZ9Hr6LIT9l: {
    id: "AEFbxJZ9Hr6LIT9l",
    race: "Gnome",
    name: "Knack with Poison",
    bucket: "numeric",
    note: "The flat +2 Fort vs poison promotes via a new save-note; the bump to +4 for accidental self-poisoning is a second total for the same category and stays unexpressed.",
  },
  lqFhyqE7frSbHfEA: {
    id: "lqFhyqE7frSbHfEA",
    race: "Gnome",
    name: "Magical Linguist (Gnome)",
    bucket: "numeric",
    note: "Save bonus is scoped to the language-dependent descriptor (plus glyphs/symbols/magical writings, narrower than any category); language-dependent is now a real SAVE_CATEGORIES entry and the note text matches a VENDORED_RACIAL_TRAIT_SAVE_NOTES key exactly, so the save half is wired via collect.ts. The DC bonus still has no matching spellEffect target and stays prose.",
  },
  C3Q7w4YJ7ALgd1am: {
    id: "C3Q7w4YJ7ALgd1am",
    race: "Gnome",
    name: "Nature Affinity",
    bucket: "blocked",
    note: "Fort save is scoped to diseases and poisons from fey, plants, and forest hazards, all attacker-property scopes the save vocabulary excludes.",
  },
  gaF64cLXf9NDJgNi: {
    id: "gaF64cLXf9NDJgNi",
    race: "Gnome",
    name: "Nosophobia",
    bucket: "numeric",
    note: "Unconditional +4 Fort vs disease and poison, both in SAVE_CATEGORIES with no unexpressible caveat; promotes via a new save-note.",
  },
  DB36Ptkf1JFl5H37: {
    id: "DB36Ptkf1JFl5H37",
    race: "Gnome",
    name: "Shadow Dodger",
    bucket: "situational",
    note: "Dodge AC bonus conditional on successfully disbelieving an illusion, a resolution the static sheet cannot detect.",
  },
  C6ShN5EYe8WUtbY1: {
    id: "C6ShN5EYe8WUtbY1",
    race: "Gnome",
    name: "Shadow Foe",
    bucket: "situational",
    note: "Attack and AC bonus scoped to dark-folk, wayang, and Shadow-Plane outsiders; favored-enemy-shaped bonuses against a creature subtype have no modeled target.",
  },
  eqdCFnuUmo68fMPd: {
    id: "eqdCFnuUmo68fMPd",
    race: "Gnome",
    name: "Shadowhunter (Gnome)",
    bucket: "subsystem",
    note: "Incorporeal-damage rule and doubled undead-ability-damage healing rate are rules exceptions with no Change target; the negative-level save bonus is also out of vocabulary (negative levels excluded).",
  },
  "9iLQf70RGSRIPYMK": {
    id: "9iLQf70RGSRIPYMK",
    race: "Gnome",
    name: "Sound Mimicry",
    bucket: "situational",
    note: "Bluff bonus scoped to mimicking a specific sound heard for 10 minutes, one use of the skill rather than the whole of it.",
  },
  lnahx05blmymRHUA: {
    id: "lnahx05blmymRHUA",
    race: "Gnome",
    name: "Stalker",
    bucket: "situational",
    note: "Attack/damage and skill bonus limited to once per day and scoped to a specific observed creature, a resource-and-target state the static sheet cannot detect.",
  },
  f9g94BzVWjntaNQg: {
    id: "f9g94BzVWjntaNQg",
    race: "Gnome",
    name: "Warden of Nature",
    bucket: "numeric",
    note: "The dodge AC bonus vs. aberrations is now a real AC_CATEGORIES entry; the note text matches a VENDORED_RACIAL_TRAIT_AC_NOTES key exactly, so it is wired via collect.ts (partial: oozes and vermin have no key, and the attack half has no attacker-type target, so both stay prose).",
  },
  OcHofX7dmPTO2FJc: {
    id: "OcHofX7dmPTO2FJc",
    race: "Gnome",
    name: "Wright",
    bucket: "situational",
    note: "Craft bonus scoped to vehicles and the remaining bonuses are to an unmodeled homebrew driving-check mechanic, not a whole-skill bonus.",
  },
  scKsrtwKWy4eGdZx: {
    id: "scKsrtwKWy4eGdZx",
    race: "Goblin",
    name: "Eat Anything",
    bucket: "numeric",
    note: "Save bonus is scoped to the nauseated/sickened conditions, now the nausea SAVE_CATEGORIES entry; the note text matches a VENDORED_RACIAL_TRAIT_SAVE_NOTES key exactly, so it is wired via collect.ts. The Survival-to-forage half is separately narrower than the whole skill and stays unwired.",
  },
  eYZTYsiT5ssa2jrK: {
    id: "eYZTYsiT5ssa2jrK",
    race: "Goblin",
    name: "Junk Tinker",
    bucket: "situational",
    note: "Craft bonus scoped to building or repairing without proper tools and the remaining bonuses are to an unmodeled homebrew driving-check mechanic, not a whole-skill bonus.",
  },
  RypMqnONgwnba8aC: {
    id: "RypMqnONgwnba8aC",
    race: "Grippli",
    name: "Defensive Training (Grippli)",
    bucket: "situational",
    note: "Dodge AC bonus scoped to Large-or-larger animals and magical beasts; a creature-size/type-scoped bonus has no modeled target.",
  },
};
