/**
 * Classification shard for vendored racial traits whose `race` starts with
 * A-D — see `./index.ts` for the shard convention and `./types.ts`
 * for the bucket rubric.
 */

import type { RacialTraitClassificationEntry } from "./types.js";

export const RACIAL_TRAIT_CLASSIFICATION_RACES_AD: Readonly<
  Record<string, RacialTraitClassificationEntry>
> = {
  SnhFeGgq8qpGMVDh: {
    id: "SnhFeGgq8qpGMVDh",
    race: "Aasimar",
    name: "Celestial Crusader",
    bucket: "situational",
    note: "Attack/AC/Knowledge(planes)/Spellcraft bonuses are all scoped to evil outsiders, a property of the opponent the static sheet can't detect without over-applying, so this stays situational rather than an unconditional Change.",
  },
  "2NXp8S2ZZ2Lh5LS3": {
    id: "2NXp8S2ZZ2Lh5LS3",
    race: "Aasimar",
    name: "Halo",
    bucket: "subsystem",
    note: "Grants an at-will light spell-like ability; the +2 Intimidate and blind/dazzle-save bonuses only apply while the halo is active and are gated to the linked Halo buff (Related Buff), so this trait record carries no Change-shaped number of its own.",
  },
  ZW41vB78wXvRWWfs: {
    id: "ZW41vB78wXvRWWfs",
    race: "Aasimar",
    name: "Variant Aasimar Abilities",
    bucket: "subsystem",
    note: "A d100 table of 100 distinct GM/player-chosen abilities with an explicit note that the option must be picked and applied to the actor by hand, so there is no single fixed number to wire.",
  },
  r6mgpoYE0rnJjrsv: {
    id: "r6mgpoYE0rnJjrsv",
    race: "Aquatic Elf",
    name: "Surface Features",
    bucket: "situational",
    note: "The Bluff/Disguise bonus only applies when passing as a surface elf, a roleplay scenario the sheet has no way to detect automatically, so situational rather than an unconditional Change.",
  },
  Xq02Qwpj4FBfGGJn: {
    id: "Xq02Qwpj4FBfGGJn",
    race: "Aquatic Elf",
    name: "Surfacer Antagonist",
    bucket: "situational",
    note: "Attack bonus is scoped to humans, a property of the opponent the sheet can't detect without over-applying to every attack roll.",
  },
  "3vfffr4tidJuzisG": {
    id: "3vfffr4tidJuzisG",
    race: "Catfolk",
    name: "Nimble Faller",
    bucket: "situational",
    note: "The CMD bonus is scoped to trip attempts only; CMD is a single flat total, so scoping it to one maneuver would over-apply it against every other maneuver. The fall-safely half of the trait has no number at all.",
  },
  xy56alprFFyhWR0y: {
    id: "xy56alprFFyhWR0y",
    race: "Cecaelia",
    name: "Dexterous Tentacles",
    bucket: "situational",
    note: "The Sleight of Hand penalty only applies if the player chooses to use tentacles instead of hands, a condition the sheet can't assume by default; the sense-range increase alongside it has no Change target.",
  },
  Hi2xxPj8RqlQ5NYn: {
    id: "Hi2xxPj8RqlQ5NYn",
    race: "Cecaelia",
    name: "Tripping Tentacles",
    bucket: "situational",
    note: "The CMB bonus is scoped to trip attempts only; CMB is a single flat total, so scoping it to one maneuver would over-apply it against every other maneuver check.",
  },
  uvFRWmR4IU1kPbyM: {
    id: "uvFRWmR4IU1kPbyM",
    race: "Changeling",
    name: "Annis-Born (Slag May)",
    bucket: "subsystem",
    note: "Inert bundle by design: the ability array is applied by the sibling 'Ability Modifiers (Changeling - ...)' entry the picker also grants, with the base array suppressed via the 'Ability Modifiers (' prefix inference (see VENDORED_STANDARD_TRAIT_TARGETS's doc in racial-traits.ts). Wiring this bundle entry too would double-apply the array; the bundled hag-trait prose likewise belongs to its own sibling entries.",
  },
  To9CTavwqfCUqpuZ: {
    id: "To9CTavwqfCUqpuZ",
    race: "Changeling",
    name: "Ash-Born (Hearth May)",
    bucket: "subsystem",
    note: "Inert bundle by design: the ability array is applied by the sibling 'Ability Modifiers (Changeling - ...)' entry the picker also grants, with the base array suppressed via the 'Ability Modifiers (' prefix inference (see VENDORED_STANDARD_TRAIT_TARGETS's doc in racial-traits.ts). Wiring this bundle entry too would double-apply the array; the bundled hag-trait prose likewise belongs to its own sibling entries.",
  },
  Rj3X80eJLvjX0SpQ: {
    id: "Rj3X80eJLvjX0SpQ",
    race: "Changeling",
    name: "Blood-Born (Veil May)",
    bucket: "subsystem",
    note: "Inert bundle by design: the ability array is applied by the sibling 'Ability Modifiers (Changeling - ...)' entry the picker also grants, with the base array suppressed via the 'Ability Modifiers (' prefix inference (see VENDORED_STANDARD_TRAIT_TARGETS's doc in racial-traits.ts). Wiring this bundle entry too would double-apply the array; the bundled hag-trait prose likewise belongs to its own sibling entries.",
  },
  LzFbBJDJsOh7wy8t: {
    id: "LzFbBJDJsOh7wy8t",
    race: "Changeling",
    name: "Dreamthief-Born (Waker May)",
    bucket: "subsystem",
    note: "Inert bundle by design: the ability array is applied by the sibling 'Ability Modifiers (Changeling - ...)' entry the picker also grants, with the base array suppressed via the 'Ability Modifiers (' prefix inference (see VENDORED_STANDARD_TRAIT_TARGETS's doc in racial-traits.ts). Wiring this bundle entry too would double-apply the array; the bundled hag-trait prose likewise belongs to its own sibling entries.",
  },
  QoUMSih2Xyc3GRR7: {
    id: "QoUMSih2Xyc3GRR7",
    race: "Changeling",
    name: "Green-Born (Callow May)",
    bucket: "subsystem",
    note: "Inert bundle by design: the ability array is applied by the sibling 'Ability Modifiers (Changeling - ...)' entry the picker also grants, with the base array suppressed via the 'Ability Modifiers (' prefix inference (see VENDORED_STANDARD_TRAIT_TARGETS's doc in racial-traits.ts). Wiring this bundle entry too would double-apply the array; the bundled hag-trait prose likewise belongs to its own sibling entries.",
  },
  W199gG02chF53jD4: {
    id: "W199gG02chF53jD4",
    race: "Changeling",
    name: "Mute-Born (Sorrow May)",
    bucket: "subsystem",
    note: "Inert bundle by design: the ability array is applied by the sibling 'Ability Modifiers (Changeling - ...)' entry the picker also grants, with the base array suppressed via the 'Ability Modifiers (' prefix inference (see VENDORED_STANDARD_TRAIT_TARGETS's doc in racial-traits.ts). Wiring this bundle entry too would double-apply the array; the bundled hag-trait prose likewise belongs to its own sibling entries.",
  },
  BNpMu00YoQaJyRUt: {
    id: "BNpMu00YoQaJyRUt",
    race: "Changeling",
    name: "Night-Born (Moon May)",
    bucket: "subsystem",
    note: "Inert bundle by design: the ability array is applied by the sibling 'Ability Modifiers (Changeling - ...)' entry the picker also grants, with the base array suppressed via the 'Ability Modifiers (' prefix inference (see VENDORED_STANDARD_TRAIT_TARGETS's doc in racial-traits.ts). Wiring this bundle entry too would double-apply the array; the bundled hag-trait prose likewise belongs to its own sibling entries.",
  },
  BD8FBL0PfVe5qfrt: {
    id: "BD8FBL0PfVe5qfrt",
    race: "Changeling",
    name: "Pyrophile",
    bucket: "blocked",
    note: "The damage-roll bonus is scoped to spells with the fire descriptor; there is no engine target for a spell-descriptor-scoped damage bonus (the vendored 'spellEffect' label is not in targets.ts's APPLIED_TARGETS or its prefixes), so this stays blocked.",
  },
  "1a6WuPBFKqhIk4DC": {
    id: "1a6WuPBFKqhIk4DC",
    race: "Changeling",
    name: "Sea-Born (Brine May)",
    bucket: "subsystem",
    note: "Inert bundle by design: the ability array is applied by the sibling 'Ability Modifiers (Changeling - ...)' entry the picker also grants, with the base array suppressed via the 'Ability Modifiers (' prefix inference (see VENDORED_STANDARD_TRAIT_TARGETS's doc in racial-traits.ts). Wiring this bundle entry too would double-apply the array; the bundled hag-trait prose likewise belongs to its own sibling entries.",
  },
  jXo1JOAbSAm1iC5M: {
    id: "jXo1JOAbSAm1iC5M",
    race: "Changeling",
    name: "Storm-Born (Virga May)",
    bucket: "subsystem",
    note: "Inert bundle by design: the ability array is applied by the sibling 'Ability Modifiers (Changeling - ...)' entry the picker also grants, with the base array suppressed via the 'Ability Modifiers (' prefix inference (see VENDORED_STANDARD_TRAIT_TARGETS's doc in racial-traits.ts). Wiring this bundle entry too would double-apply the array; the bundled hag-trait prose likewise belongs to its own sibling entries.",
  },
  PHryxw5cbuUqi07S: {
    id: "PHryxw5cbuUqi07S",
    race: "Changeling",
    name: "Winter-Born (Snow May)",
    bucket: "subsystem",
    note: "Inert bundle by design: the ability array is applied by the sibling 'Ability Modifiers (Changeling - ...)' entry the picker also grants, with the base array suppressed via the 'Ability Modifiers (' prefix inference (see VENDORED_STANDARD_TRAIT_TARGETS's doc in racial-traits.ts). Wiring this bundle entry too would double-apply the array; the bundled hag-trait prose likewise belongs to its own sibling entries.",
  },
  uQXWDV9ooUimkH43: {
    id: "uQXWDV9ooUimkH43",
    race: "Changeling,Callow May",
    name: "Hag Racial Trait (Changeling - Callow May)",
    bucket: "situational",
    note: "The Bluff bonus only applies against creatures that could be sexually attracted to the character, a property of the opponent the sheet can't detect without over-applying it to every Bluff check.",
  },
  xJ6s1PyLYiXqYZgo: {
    id: "xJ6s1PyLYiXqYZgo",
    race: "Changeling,Hearth May",
    name: "Hag Racial Trait (Changeling - Hearth May)",
    bucket: "blocked",
    note: "Same fire-descriptor spell damage bonus as Changeling Pyrophile; there is no engine target for a spell-descriptor-scoped damage bonus (the vendored 'spellEffect' label is not in targets.ts's APPLIED_TARGETS or its prefixes), so blocked.",
  },
  Son5Vq5HQepEZIzC: {
    id: "Son5Vq5HQepEZIzC",
    race: "Changeling,Snow May",
    name: "Hag Racial Trait (Changeling - Snow May)",
    bucket: "situational",
    note: "The Acrobatics/Climb bonus only applies on icy or slippery surfaces, a terrain condition the sheet can't detect automatically, so situational rather than an unconditional Change.",
  },
  eLnDyBKNO6J5VbOI: {
    id: "eLnDyBKNO6J5VbOI",
    race: "Changeling,Sorrow May",
    name: "Hag Racial Trait (Changeling - Sorrow May)",
    bucket: "blocked",
    note: "The save bonus is scoped to gaze attacks, one of the documented note scopes in vendored-trait-save-notes.ts with no SAVE_CATEGORIES entry, so blocked.",
  },
  Nrfb2H4Ll6lnjzUt: {
    id: "Nrfb2H4Ll6lnjzUt",
    race: "Dhampir",
    name: "Vampire Hunter",
    bucket: "situational",
    note: "Attack bonus is scoped to vampires, a property of the opponent the sheet can't detect without over-applying to every attack roll.",
  },
  "5lsAtsSAJ25y69ST": {
    id: "5lsAtsSAJ25y69ST",
    race: "Dhampir",
    name: "Vampiric Empathy",
    bucket: "situational",
    note: "The Diplomacy bonus only applies when dealing with bats, rats, or wolves, a scope the sheet can't detect without over-applying to every Diplomacy check; the speak-with-animals ability alongside it has no Change-shaped number.",
  },
  JtvsIm1JAxjAL2YL: {
    id: "JtvsIm1JAxjAL2YL",
    race: "Dhampir,Ancient-Born",
    name: "Alternate Weakness (Dhampir - Ancient-Born)",
    bucket: "blocked",
    note: "The penalty is scoped to effects that damage, drain, or reduce physical ability scores; ability damage/drain has no SAVE_CATEGORIES entry (a documented exclusion in vendored-trait-save-notes.ts), so blocked.",
  },
  LdbfPqPoza3xBUde: {
    id: "LdbfPqPoza3xBUde",
    race: "Dhampir,Ru-Shi",
    name: "Alternate Weakness (Dhampir - Ru-Shi)",
    bucket: "blocked",
    note: "The penalty is scoped to sonic effects and spells; sonic has no SAVE_CATEGORIES entry (a documented exclusion in vendored-trait-save-notes.ts), so blocked.",
  },
  ph1cjGR44M6Cwycc: {
    id: "ph1cjGR44M6Cwycc",
    race: "Dhampir,Svetocher",
    name: "Alternate Weakness (Dhampir - Svetocher)",
    bucket: "blocked",
    note: "The penalty is scoped to effects that deal positive energy damage; there is no SAVE_CATEGORIES entry for positive energy, so blocked.",
  },
  "9krrIkXBMYXxnEaE": {
    id: "9krrIkXBMYXxnEaE",
    race: "Drow",
    name: "Ancestral Grudge",
    bucket: "situational",
    note: "Attack bonus is scoped to humanoids with the dwarf or elf subtype, a property of the opponent the sheet can't detect without over-applying to every attack roll.",
  },
  Ol8AbEHSbXnbj9eC: {
    id: "Ol8AbEHSbXnbj9eC",
    race: "Drow",
    name: "Blasphemous Covenant",
    bucket: "situational",
    note: "The Diplomacy bonus only applies against unbound demons, a property of the opponent the sheet can't detect without over-applying; the summoned-demon HP boost and planar ally cost reduction affect creatures other than the character and have no Change target on this sheet.",
  },
  "20MZKzAdXq7r91VL": {
    id: "20MZKzAdXq7r91VL",
    race: "Drow",
    name: "Darklands Guide",
    bucket: "situational",
    note: "The initiative and trap/hazard save bonuses only apply while underground, a location the sheet can't detect automatically, so situational rather than an unconditional Change.",
  },
  gW9EZhxSnPytPicG: {
    id: "gW9EZhxSnPytPicG",
    race: "Drow",
    name: "Defensive Training (Drow)",
    bucket: "situational",
    note: "The dodge bonus to AC is scoped to aberrations, a property of the opponent the sheet can't detect without over-applying to every attack.",
  },
  zOmlqno4V0mvAO4m: {
    id: "zOmlqno4V0mvAO4m",
    race: "Drow",
    name: "Voice in the Darkness (Drow)",
    bucket: "situational",
    note: "The Intimidate/Stealth bonus only applies in dim light or darker conditions, a lighting state the sheet can't detect automatically, so situational rather than an unconditional Change.",
  },
  GL7VJG5KSRQDF4GS: {
    id: "GL7VJG5KSRQDF4GS",
    race: "Duergar",
    name: "Blood Enmity",
    bucket: "situational",
    note: "Attack bonus is scoped to humanoids of the dwarf or elf subtype, a property of the opponent the sheet can't detect without over-applying to every attack roll.",
  },
  WLj6hpVMQwt2vRRP: {
    id: "WLj6hpVMQwt2vRRP",
    race: "Duergar",
    name: "Deep Magic",
    bucket: "blocked",
    note: "The bonus targets caster level checks to overcome SR and dispel checks; targets.ts lists 'cl' as collected but never applied by compute.ts, so there is no wireable route and this stays blocked.",
  },
  QdzlzrqWtgfjE4Fs: {
    id: "QdzlzrqWtgfjE4Fs",
    race: "Dwarf",
    name: "Ancient Enmity",
    bucket: "situational",
    note: "Attack bonus is scoped to humanoids of the elf subtype, a property of the opponent the sheet can't detect without over-applying to every attack roll.",
  },
  w24Veg7ttOZfc7eF: {
    id: "w24Veg7ttOZfc7eF",
    race: "Dwarf",
    name: "Barrow Scholar",
    bucket: "situational",
    note: "The Knowledge (religion) bonus only applies when identifying undead; the sheet carries one aggregate bonus per skill, so applying it unconditionally would inflate every other Knowledge (religion) check.",
  },
  ZnBQOspblXzYNloj: {
    id: "ZnBQOspblXzYNloj",
    race: "Dwarf",
    name: "Barrow Warden",
    bucket: "situational",
    note: "Attack and AC bonuses are scoped to undead, a property of the opponent the sheet can't detect without over-applying to every roll.",
  },
  pYC7FKoEJIuinY8t: {
    id: "pYC7FKoEJIuinY8t",
    race: "Dwarf",
    name: "Behind the Veil (Dwarf)",
    bucket: "situational",
    note: "The Bluff/Sleight of Hand bonus only applies while benefiting from concealment or cover, a battlefield state the sheet can't detect automatically, so situational rather than an unconditional Change.",
  },
  HFKHorjMw2dERwBo: {
    id: "HFKHorjMw2dERwBo",
    race: "Dwarf",
    name: "Craftsman",
    bucket: "situational",
    note: "The Craft/Profession bonus only applies to objects made of metal or stone; the sheet carries one aggregate bonus per skill, so applying it unconditionally would inflate every other Craft/Profession check.",
  },
  rkFSqqFnqfXUWjNv: {
    id: "rkFSqqFnqfXUWjNv",
    race: "Dwarf",
    name: "Death's End",
    bucket: "situational",
    note: "AC and save bonuses are scoped to undead and their spells/spell-like abilities, a property of the opponent the sheet can't detect without over-applying to every roll.",
  },
  "0732ZhCzO00426kM": {
    id: "0732ZhCzO00426kM",
    race: "Dwarf",
    name: "Deep Tradition",
    bucket: "situational",
    note: "Attack and AC-vs-attacks-of-opportunity bonuses are scoped to a fixed list of opponent types (drow, duergar, aberrations, giants, orcs), a property of the opponent the sheet can't detect without over-applying to every roll.",
  },
  "7LSKyC0eM1uQgBvm": {
    id: "7LSKyC0eM1uQgBvm",
    race: "Dwarf",
    name: "Deep Warrior",
    bucket: "situational",
    note: "The dodge-AC bonus is scoped to aberrations and the CMB bonus is further scoped to grapple attempts against them; CMB is a single flat total, and the opponent type is a property the sheet can't detect, so both stay situational.",
  },
  fRLqG0NKrKPmpHUr: {
    id: "fRLqG0NKrKPmpHUr",
    race: "Dwarf",
    name: "Dimdweller (Dwarf)",
    bucket: "situational",
    note: "The Intimidate/Perception/Stealth bonus only applies while benefiting from concealment due to dim light or darkness, a lighting state the sheet can't detect automatically.",
  },
  Xx0q0xnySBBY3OUr: {
    id: "Xx0q0xnySBBY3OUr",
    race: "Dwarf",
    name: "Giant Hunter",
    bucket: "situational",
    note: "The attack bonus is scoped to humanoids with the giant subtype and the Survival bonus is scoped to tracking them, both properties/uses the sheet can't detect without over-applying.",
  },
  TQxW5qAgBZQbiyTH: {
    id: "TQxW5qAgBZQbiyTH",
    race: "Dwarf",
    name: "Healthy",
    bucket: "numeric",
    note: "The contextNotes text matches an existing VENDORED_RACIAL_TRAIT_SAVE_NOTES key ('+2 Racial bonus vs. diseases and poisons; Requires 1 less save to heal diseases and poisons (min. 1 save)') exactly, so this note is already wired via collect.ts; the one-fewer-save-to-cure rider stays prose per that entry's own doc comment.",
  },
  BvVgHyKfrWZxpi5x: {
    id: "BvVgHyKfrWZxpi5x",
    race: "Dwarf",
    name: "Industrious Urbanite",
    bucket: "situational",
    note: "The Profession bonus only applies when earning money, one use among the skill's several purposes, so applying it to the sheet's single aggregate Profession bonus would over-apply; the doubled Craft progress rate has no Change-shaped number at all.",
  },
  pH0k5yxjVndAoFB6: {
    id: "pH0k5yxjVndAoFB6",
    race: "Dwarf",
    name: "Iron Within",
    bucket: "subsystem",
    note: "Grants a ki point plus an activated swift-action toggle (+2 dodge AC or +20 ft. speed for 1 round) that the description says is already modeled via the linked Iron Within (AC)/(Speed) buffs (Related Buffs), so this trait record itself carries no unconditional number.",
  },
  AvVAnxyxjjnvja9E: {
    id: "AvVAnxyxjjnvja9E",
    race: "Dwarf",
    name: "Lasting Grudge",
    bucket: "situational",
    note: "Attack bonus only applies against a creature that attacked the character a day or longer ago, a history the sheet has no way to track automatically.",
  },
  wG1e906wkQGlk3eE: {
    id: "wG1e906wkQGlk3eE",
    race: "Dwarf",
    name: "Lorekeeper",
    bucket: "situational",
    note: "The Knowledge (history) bonus only applies to checks about dwarves or their enemies; the sheet carries one aggregate bonus per skill, so applying it unconditionally would inflate every other Knowledge (history) check.",
  },
  T7dJVz4m8zpUQERB: {
    id: "T7dJVz4m8zpUQERB",
    race: "Dwarf",
    name: "Mountaineer",
    bucket: "subsystem",
    note: "Grants immunity to altitude sickness, one of the documented no-vocabulary-entry scopes, plus a rule exception against losing Dex-to-AC on Acrobatics/Climb checks; neither is a flat Change-shaped bonus.",
  },
  HzKBmWjSHjYSNsU9: {
    id: "HzKBmWjSHjYSNsU9",
    race: "Dwarf",
    name: "Relentless",
    bucket: "situational",
    note: "The CMB bonus is scoped to bull rush or overrun while both combatants stand on the ground; CMB is a single flat total, so scoping it to two maneuvers under a battlefield condition would over-apply it to every other check.",
  },
  huJk8pF1KRKfeWzL: {
    id: "huJk8pF1KRKfeWzL",
    race: "Dwarf",
    name: "Saltbeard",
    bucket: "situational",
    note: "Every numeric part of this trait is scoped: Profession(sailor) and Survival bonuses apply only at sea, and the attack/AC bonuses only against creatures with the aquatic or water subtype, all conditions the sheet can't detect without over-applying.",
  },
  SLZIXlmsbFFwnRo4: {
    id: "SLZIXlmsbFFwnRo4",
    race: "Dwarf",
    name: "Shadowhunter (Dwarf)",
    bucket: "blocked",
    note: "The save bonus is scoped to removing negative levels, one of the documented no-vocabulary-entry scopes; the 50%-damage-to-incorporeal rule and the doubled Heal-recovery-rate rule have no Change target either, so blocked.",
  },
  k3BZrtmbJvxCHeHt: {
    id: "k3BZrtmbJvxCHeHt",
    race: "Dwarf",
    name: "Sky Sentinel",
    bucket: "situational",
    note: "Attack, AC, and Perception bonuses are all scoped to flying creatures, a property of the opponent the sheet can't detect without over-applying; the higher-ground attack-bonus denial has no Change-shaped number.",
  },
  iejEnNBqCFQ097Eh: {
    id: "iejEnNBqCFQ097Eh",
    race: "Dwarf",
    name: "Spell Smasher",
    bucket: "situational",
    note: "Attack bonus only applies against a creature in the process of casting a spell or spell-like ability, an action state the sheet has no way to detect automatically.",
  },
  YAHItKOPu2o8Mrsd: {
    id: "YAHItKOPu2o8Mrsd",
    race: "Dwarf",
    name: "Spiritual Support",
    bucket: "blocked",
    note: "The caster-level bonus is scoped to conjuration (healing) spells cast on allies, i.e. a 'cl.school.*' path; targets.ts only consumes the skill./attack.weapon./damage.weapon./dr./eres./imm./immEffect. prefixes, so there is no wireable route and this stays blocked.",
  },
  eew9hWENxwAiLP8S: {
    id: "eew9hWENxwAiLP8S",
    race: "Dwarf",
    name: "Stubborn",
    bucket: "numeric",
    note: "The Will-save bonus is scoped to the enchantment (charm) and enchantment (compulsion) schools, both real SAVE_CATEGORIES keys under the enchantment parent; proposed as a supplement Change on target 'will' with those saveCategories. The reroll-after-1-round rider has no expressible form and stays prose.",
  },
  qJGhs3rHo8bT01FW: {
    id: "qJGhs3rHo8bT01FW",
    race: "Dwarf",
    name: "Tightfisted",
    bucket: "situational",
    note: "The CMD bonus is scoped to steal and disarm maneuvers only; CMD is a single flat total, so scoping it to two maneuvers would over-apply it to every other maneuver. The Sleight-of-Hand-notice/attack-of-opportunity rider is likewise conditional on an opponent's action.",
  },
  XVm7uHb6cw0AiUOh: {
    id: "XVm7uHb6cw0AiUOh",
    race: "Dwarf",
    name: "Voice in the Darkness (Dwarf)",
    bucket: "situational",
    note: "The Intimidate/Stealth bonus only applies in dim light or darker conditions, a lighting state the sheet can't detect automatically, so situational rather than an unconditional Change.",
  },
  nnyOoCfyIRKs3xcQ: {
    id: "nnyOoCfyIRKs3xcQ",
    race: "Dwarf",
    name: "Wyrmscourged",
    bucket: "situational",
    note: "Attack, AC, save, and Knowledge (arcana) bonuses are all scoped to dragons, a property of the opponent the sheet can't detect without over-applying to every roll.",
  },
  "3z3EDcQxrBgW8hIu": {
    id: "3z3EDcQxrBgW8hIu",
    race: "Dwarf",
    name: "Xenophobic",
    bucket: "blocked",
    note: "The save bonus is against mind-affecting effects except fear effects; that except-fear carve-out is explicitly named in vendored-trait-save-notes.ts as unexpressible, so this stays blocked.",
  },
};
