/**
 * Classification shard for vendored racial traits whose `race` starts with
 * S-Z — see `./index.ts` for the shard convention and `./types.ts`
 * for the bucket rubric.
 */

import type { RacialTraitClassificationEntry } from "./types.js";

export const RACIAL_TRAIT_CLASSIFICATION_RACES_SZ: Readonly<
  Record<string, RacialTraitClassificationEntry>
> = {
  ZDYzHXisxHABCWza: {
    id: "ZDYzHXisxHABCWza",
    race: "Sahuagin",
    name: "Stoic Defender",
    bucket: "situational",
    note: "Once-per-day activated self-buff (+2 AC, +2 Will) lasting 1 minute; a limited-use resource, never an unconditional Change.",
  },
  jsIag110h3yFKi0q: {
    id: "jsIag110h3yFKi0q",
    race: "Samsaran",
    name: "Mountaineer",
    bucket: "subsystem",
    note: "Grants immunity to altitude sickness (no vocabulary entry, per vendored-trait-save-notes.ts) and preserves Dex-to-AC while climbing or tumbling narrow surfaces; a rules exception with no Change-shaped number.",
  },
  "3sFVS1F5eFcCUABV": {
    id: "3sFVS1F5eFcCUABV",
    race: "Shabti",
    name: "Pharaonic Will",
    bucket: "situational",
    note: "Once-per-day reroll with a +2 bonus after failing a charm, compulsion, or fear save; a limited-use reroll, explicitly named in vendored-trait-save-notes.ts as not promoted.",
  },
  MHNxeoT3fFxa3kL2: {
    id: "MHNxeoT3fFxa3kL2",
    race: "Skinwalker,Aerieborn",
    name: "Change Shape (Skinwalker - Aerieborn)",
    bucket: "subsystem",
    note: "Perception bonus, fly-speed increase, and natural attacks apply only while shapechanged; apps/web's model/skinwalker.ts documents that Change Shape's bestial features beyond the ability-score rider are deliberately unmodeled, apply by hand.",
  },
  K0OwTmAv3gNkTc8B: {
    id: "K0OwTmAv3gNkTc8B",
    race: "Skinwalker,Bloodmarked",
    name: "Change Shape (Skinwalker - Bloodmarked)",
    bucket: "subsystem",
    note: "Perception bonus, scent, reduced falling damage, and a natural attack apply only while shapechanged; apps/web's model/skinwalker.ts documents that Change Shape's bestial features beyond the ability-score rider are deliberately unmodeled, apply by hand.",
  },
  Qgkfifudu74ghm0o: {
    id: "Qgkfifudu74ghm0o",
    race: "Skinwalker,Witchwolf",
    name: "Change Shape (Skinwalker - Witchwolf)",
    bucket: "subsystem",
    note: "All-saving-throws bonus, darkvision, and natural attacks apply only while shapechanged; apps/web's model/skinwalker.ts documents that Change Shape's bestial features beyond the ability-score rider are deliberately unmodeled, apply by hand.",
  },
  GvDRYlMwK8yy6Wlj: {
    id: "GvDRYlMwK8yy6Wlj",
    race: "Strix",
    name: "Cautious Brawler",
    bucket: "situational",
    note: "The damage bonus and the lifted attack penalty apply only when dealing nonlethal damage, a per-attack choice the static sheet can't detect without over-applying.",
  },
  i13oyCR6gkLrhRSg: {
    id: "i13oyCR6gkLrhRSg",
    race: "Svirfneblin",
    name: "Healthy",
    bucket: "numeric",
    note: "The +4 racial bonus vs. disease and poison fits the SAVE_CATEGORIES vocabulary; this exact note text is not yet in VENDORED_RACIAL_TRAIT_SAVE_NOTES, so a new promotion is proposed.",
  },
  "8vByVIUdiF70ApWv": {
    id: "8vByVIUdiF70ApWv",
    race: "Svirfneblin",
    name: "Stoneseer (Svirfneblin)",
    bucket: "blocked",
    note: "The caster-level bonus is scoped to the earth descriptor, but 'cl' is not even an applied target for an unscoped bonus (see targets.ts's UNAPPLIED_TARGET_LABELS), and the vendored note itself says to add the bonus manually.",
  },
  K7YBN0QKQeWCJZ9K: {
    id: "K7YBN0QKQeWCJZ9K",
    race: "Sylph",
    name: "Breeze-Kissed (Sylph)",
    bucket: "situational",
    note: "The AC bonus is scoped to nonmagical ranged attacks and is consumed for 24 hours once the bull rush/trip is spent; a conditional, depletable defense, never an unconditional Change.",
  },
  zd8EJDQt5XGFNXV1: {
    id: "zd8EJDQt5XGFNXV1",
    race: "Sylph",
    name: "Sky Speaker",
    bucket: "subsystem",
    note: "Grants speak with animals (to birds) once per day as a spell-like ability; no Change-shaped number.",
  },
  n2lCTokOhbEJ35Nu: {
    id: "n2lCTokOhbEJ35Nu",
    race: "Syrinx",
    name: "Oppressive",
    bucket: "situational",
    note: "The Intimidate and fear-DC bonuses apply only after a successful swift-action Sense Motive check against a specific target, a per-target activated condition.",
  },
  F6e0vnGCV8OO2tyz: {
    id: "F6e0vnGCV8OO2tyz",
    race: "Tengu",
    name: "Deft Swords",
    bucket: "situational",
    note: "The CMD dodge bonus applies only while wielding a swordlike weapon, an equipped-weapon state the static sheet can't detect without over-applying to every CMD roll.",
  },
  vt3mK2P7RkUqA7nE: {
    id: "vt3mK2P7RkUqA7nE",
    race: "Tiefling",
    name: "Beguiling Liar",
    bucket: "situational",
    note: "The Bluff bonus is scoped to convincing a target of a lie specifically, not the whole skill; the sheet has no per-use scoping for a single skill's Change.",
  },
  I6yOviSAKlkZqshg: {
    id: "I6yOviSAKlkZqshg",
    race: "Tiefling",
    name: "Bullying",
    bucket: "situational",
    note: "The CMB bonus is scoped to disarm and steal maneuvers only; an unconditional 'cmb' Change would over-apply to every combat maneuver.",
  },
  tTnTbwQMUCVklGGl: {
    id: "tTnTbwQMUCVklGGl",
    race: "Tiefling",
    name: "Darklands Guide",
    bucket: "situational",
    note: "Both the initiative and save bonuses apply only underground, an environmental state the static sheet can't detect, and 'traps and hazards' has no SAVE_CATEGORIES entry either.",
  },
  "5YDsKDGSzLMoH1dv": {
    id: "5YDsKDGSzLMoH1dv",
    race: "Tiefling",
    name: "Variant Tiefling Abilities",
    bucket: "blocked",
    note: "A d% table of 100 disparate abilities; the vendored note itself says the option must be determined and applied to the actor manually, so no single Change route exists.",
  },
  ETapFH3D6SF1WwVn: {
    id: "ETapFH3D6SF1WwVn",
    race: "Tiefling,Beastbrood",
    name: "Spell-Like Ability (Tiefling - Beastbrood)",
    bucket: "subsystem",
    note: "Grants a single spell-like ability once per day at character-level caster level; no Change-shaped number.",
  },
  v6eFa2pTphzZzFDP: {
    id: "v6eFa2pTphzZzFDP",
    race: "Tiefling,Faultspawn",
    name: "Spell-Like Ability (Tiefling - Faultspawn)",
    bucket: "subsystem",
    note: "Grants a single spell-like ability once per day at character-level caster level; no Change-shaped number.",
  },
  fLfQPOGCnNhp6Q5A: {
    id: "fLfQPOGCnNhp6Q5A",
    race: "Tiefling,Foulspawn",
    name: "Spell-Like Ability (Tiefling - Foulspawn)",
    bucket: "subsystem",
    note: "Grants a single spell-like ability once per day at character-level caster level; no Change-shaped number.",
  },
  dagWgGQYv20usVZW: {
    id: "dagWgGQYv20usVZW",
    race: "Tiefling,Grimspawn",
    name: "Spell-Like Ability (Tiefling - Grimspawn)",
    bucket: "subsystem",
    note: "Grants a single spell-like ability once per day at character-level caster level; no Change-shaped number.",
  },
  OayRgLPHanjzhdK0: {
    id: "OayRgLPHanjzhdK0",
    race: "Tiefling,Hellspawn",
    name: "Spell-Like Ability (Tiefling - Hellspawn)",
    bucket: "subsystem",
    note: "Grants a single spell-like ability once per day at character-level caster level; no Change-shaped number.",
  },
  gDO7etqF3QCXKyWZ: {
    id: "gDO7etqF3QCXKyWZ",
    race: "Tiefling,Hungerseed",
    name: "Spell-Like Ability (Tiefling - Hungerseed)",
    bucket: "subsystem",
    note: "Grants a single spell-like ability once per day at character-level caster level; no Change-shaped number.",
  },
  TNbX1iRPplCIvhdO: {
    id: "TNbX1iRPplCIvhdO",
    race: "Tiefling,Pitborn",
    name: "Spell-Like Ability (Tiefling - Pitborn)",
    bucket: "subsystem",
    note: "Grants a single spell-like ability once per day at character-level caster level; no Change-shaped number.",
  },
  "93KXq6n1wiX0ifEy": {
    id: "93KXq6n1wiX0ifEy",
    race: "Tiefling,Shackleborn",
    name: "Spell-Like Ability (Tiefling - Shackleborn)",
    bucket: "subsystem",
    note: "Grants a single spell-like ability once per day at character-level caster level; no Change-shaped number.",
  },
  eNSivYdOXqQpPe52: {
    id: "eNSivYdOXqQpPe52",
    race: "Tiefling,Spitespawn",
    name: "Spell-Like Ability (Tiefling - Spitespawn)",
    bucket: "subsystem",
    note: "Grants a single spell-like ability once per day at character-level caster level; no Change-shaped number.",
  },
  n98kLjKTeMEM5rdx: {
    id: "n98kLjKTeMEM5rdx",
    race: "Tiefling,the Motherless",
    name: "Spell-Like Ability (Tiefling - the Motherless)",
    bucket: "subsystem",
    note: "Grants a single spell-like ability once per day at character-level caster level; no Change-shaped number.",
  },
  sNyXq295yfcoKOrb: {
    id: "sNyXq295yfcoKOrb",
    race: "Undine",
    name: "Flesh Chameleon",
    bucket: "situational",
    note: "The Disguise bonus requires a standard action to activate and only helps the specific 'appear human' use of the check; an activated, scoped bonus.",
  },
  fIZiHRwjPPqelrGs: {
    id: "fIZiHRwjPPqelrGs",
    race: "Undine",
    name: "Terrain Chameleon",
    bucket: "situational",
    note: "The Stealth bonus requires a standard action to activate and only applies underwater; an activated, scoped bonus.",
  },
  vXfdoGjzMenvozlp: {
    id: "vXfdoGjzMenvozlp",
    race: "Vanara",
    name: "Whitecape",
    bucket: "situational",
    note: "The CMD bonus is scoped to resisting bull rush or trip specifically; an unconditional 'cmd' Change would over-apply to every combat maneuver.",
  },
  xmVIIWMr8jcAFnhw: {
    id: "xmVIIWMr8jcAFnhw",
    race: "Vine Leshy",
    name: "Grapevine",
    bucket: "subsystem",
    note: "Grants goodberry once per day as a spell-like ability; no Change-shaped number.",
  },
  qJVDmYLzQmuc0v5j: {
    id: "qJVDmYLzQmuc0v5j",
    race: "Vishkanya",
    name: "Subtle Appearance",
    bucket: "situational",
    note: "The Disguise bonus is scoped to looking fully human, not the whole skill check; the sheet has no per-use scoping for a single skill's Change.",
  },
  EEjvlHbyXB1yYEgU: {
    id: "EEjvlHbyXB1yYEgU",
    race: "Wayang",
    name: "Shadow Speaker",
    bucket: "situational",
    note: "A three-per-day, once-per-turn insight bonus to a roll type chosen before rolling; a limited-use resource, never an unconditional Change.",
  },
  P32v41a5IFStjrX2: {
    id: "P32v41a5IFStjrX2",
    race: "Wyrwood",
    name: "Experimental Body: Blessed",
    bucket: "subsystem",
    note: "Grants divine favor once per day as a spell-like ability (caster level equal to Hit Dice); no Change-shaped number.",
  },
  "4tq1PgGZzIsYSVkH": {
    id: "4tq1PgGZzIsYSVkH",
    race: "Wyrwood",
    name: "Experimental Body: Enchanted",
    bucket: "blocked",
    note: "Raises Intelligence by 2 only for computing bonus spells or extracts, not a real ability-score Change; the vendored note itself instructs manually adding +2 to the Spell Slot Ability Bonus field.",
  },
  WJO1PMH4T8qWg9wK: {
    id: "WJO1PMH4T8qWg9wK",
    race: "Wyrwood",
    name: "Experimental Body: Fey-Touched",
    bucket: "subsystem",
    note: "Grants charm animal once per day as a spell-like ability (caster level equal to Hit Dice); no Change-shaped number.",
  },
  "4eZSNsHGXAwZm4dk": {
    id: "4eZSNsHGXAwZm4dk",
    race: "Wyrwood",
    name: "Experimental Body: Scorched",
    bucket: "situational",
    note: "The bonus melee damage is a once-per-day, post-hit free action, a limited-use resource never given as an unconditional Change.",
  },
  BsjoXUFny0rPD6xc: {
    id: "BsjoXUFny0rPD6xc",
    race: "Wyvaran",
    name: "Evasive Maneuvers",
    bucket: "situational",
    note: "The fly-maneuverability change requires manual setup per the vendored note, and the dodge bonus to AC and Reflex is scoped to siege-weapon attacks specifically, a rare attacker-source condition.",
  },
  Z4bfgptrjWdN7Ugb: {
    id: "Z4bfgptrjWdN7Ugb",
    race: "Wyvaran",
    name: "Neglected Heritage",
    bucket: "situational",
    note: "The Diplomacy bonus is scoped to making requests and gathering information specifically, not the whole skill; the sheet has no per-use scoping for a single skill's Change.",
  },
};
