import { describe, expect, it } from "bun:test";

import type { CharacterDoc, WeaponInstance } from "@pf1/schema";
import { loadRefData } from "@pf1/data-pipeline";

import { compute } from "../src/index.js";

/**
 * Fixture coverage for the Gun Training family (Ultimate Combat) and the
 * firearm-specific attack-line surface (rangeIncrement/misfire/capacity/
 * touch AC). Rules text verified against aonprd.com:
 *
 * - Gun Training (gunslinger 5th, +1 firearm TYPE at 9th/13th/17th):
 *   "She gains a bonus equal to her Dexterity modifier on damage rolls when
 *   firing that type of firearm." (Gunslinger class page, "Gun Training".)
 * - Musket Training (musket master 5th) / Pistol Training (pistolero 5th):
 *   "She gains a bonus on damage rolls equal to her Dexterity modifier"
 *   with ALL two-handed (resp. one-handed) firearms, no per-type picks —
 *   "This replaces firearm training 1, 2, 3, and 4." (Ultimate Combat
 *   pp.50-51, `archetype-features.json` "Musket Training"/"Pistol Training".)
 * - Touch AC (Firearms equipment rules, aonprd.com/Rules.aspx?Name=Firearms):
 *   an early firearm resolves against touch AC within its first range
 *   increment; an advanced firearm within its first FIVE range increments.
 *   Nothing in the published rules distinguishes "modern" (Reign of Winter)
 *   firearms from advanced ones for this purpose, so they're treated
 *   identically (`WeaponInstance.firearmEra`'s doc comment).
 *
 * `WeaponInstance` fixtures are constructed directly rather than pulled from
 * vendored weapon data (concurrently regenerated by another wave), so these
 * tests only exercise engine logic, not the data pipeline.
 */
const ref = loadRefData();

function raceId(name: string): string {
  const entry = Object.entries(ref.races).find(([, r]) => r.name === name);
  if (!entry) throw new Error(`race not found: ${name}`);
  return entry[0];
}

const ABILITIES = { str: 14, dex: 18, con: 12, int: 10, wis: 10, cha: 10 } as const;

function musket(overrides: Partial<WeaponInstance> = {}): WeaponInstance {
  return {
    name: "Musket",
    category: "ranged",
    attackAbility: "dex",
    group: "musket",
    weaponGroups: ["firearmsTwoHanded"],
    rangeIncrement: 20,
    misfire: 4,
    capacity: 1,
    firearmEra: "early",
    ...overrides,
  };
}

function pistol(overrides: Partial<WeaponInstance> = {}): WeaponInstance {
  return {
    name: "Pistol",
    category: "ranged",
    attackAbility: "dex",
    group: "pistol",
    weaponGroups: ["firearmsOneHanded"],
    rangeIncrement: 10,
    misfire: 4,
    firearmEra: "early",
    ...overrides,
  };
}

function makeDoc(opts: {
  level: number;
  weapons: WeaponInstance[];
  gunTrainingPicks?: Partial<Record<string, string[]>>;
  archetypes?: string[];
  classTag?: string;
  abilities?: typeof ABILITIES;
}): CharacterDoc {
  return {
    schemaVersion: 1,
    id: "test",
    ownerId: "owner",
    version: 1,
    updatedAt: "2026-01-01T00:00:00.000Z",
    identity: {
      name: "Test",
      race: raceId("Human"),
      classes: [{ tag: opts.classTag ?? "gunslinger", level: opts.level }],
    },
    abilities: opts.abilities ?? ABILITIES,
    build: {
      feats: [],
      skillRanks: {},
      classFeatureChoices: [],
      spells: { known: [] },
      gear: [],
      weapons: opts.weapons,
      gunTrainingPicks: opts.gunTrainingPicks,
      archetypes: opts.archetypes,
    },
    live: {
      hp: { current: 0, temp: 0, nonlethal: 0 },
      conditions: [],
      activeBuffs: [],
      resources: {},
    },
  };
}

describe("Gun Training (base gunslinger): picked firearm type gets Dex to damage", () => {
  it("applies Dex mod (×1) to a matching, picked firearm at 5th level", () => {
    const doc = makeDoc({
      level: 5,
      weapons: [musket()],
      gunTrainingPicks: { gunslinger: ["musket"] },
    });
    const sheet = compute(doc, ref);
    const attack = sheet.attacks[0]!;
    // dex 18 -> mod +4.
    expect(attack.damageBonus.total).toBe(4);
    expect(attack.damageAbilityMod).toBe(4);
    expect(attack.damageMultiplier).toBe(1);
    expect(attack.damageBonus.components.some((c) => c.source === "Dexterity")).toBe(true);
  });

  it("carries misfire and touchRangeFt (early era: ×1 range increment) on the attack line", () => {
    const doc = makeDoc({
      level: 5,
      weapons: [musket()],
      gunTrainingPicks: { gunslinger: ["musket"] },
    });
    const sheet = compute(doc, ref);
    const attack = sheet.attacks[0]!;
    expect(attack.rangeIncrement).toBe(20);
    expect(attack.firearm?.misfire).toBe(4);
    expect(attack.firearm?.capacity).toBe(1);
    expect(attack.firearm?.touchRangeFt).toBe(20);
  });

  it("does not apply to a non-matching firearm (Pistol not picked)", () => {
    const doc = makeDoc({
      level: 5,
      weapons: [pistol()],
      gunTrainingPicks: { gunslinger: ["musket"] },
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.damageBonus.total).toBe(0);
  });

  it("does not apply below 5th level (tier not yet unlocked)", () => {
    const doc = makeDoc({
      level: 4,
      weapons: [musket()],
      gunTrainingPicks: { gunslinger: ["musket"] },
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.damageBonus.total).toBe(0);
  });

  it("only the first pick is unlocked at 5th level even if a 2nd is stored (9th-level tier not reached)", () => {
    const doc = makeDoc({
      level: 5,
      weapons: [musket(), pistol()],
      gunTrainingPicks: { gunslinger: ["musket", "pistol"] },
    });
    const sheet = compute(doc, ref);
    // musket = pick index 0 (5th level, unlocked) -> Dex applies.
    expect(sheet.attacks[0]!.damageBonus.total).toBe(4);
    // pistol = pick index 1 (9th level, NOT unlocked at level 5) -> no Dex.
    expect(sheet.attacks[1]!.damageBonus.total).toBe(0);
  });
});

describe("Musket Training (musket master archetype): all two-handed firearms, no picks needed", () => {
  it("applies Dex to a firearms-two-handed weapon at 5th level with no picks stored", () => {
    const doc = makeDoc({
      level: 5,
      weapons: [musket()],
      archetypes: ["gunslinger:musket-master"],
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.damageBonus.total).toBe(4);
  });

  it("does not apply to a one-handed firearm", () => {
    const doc = makeDoc({
      level: 5,
      weapons: [pistol()],
      archetypes: ["gunslinger:musket-master"],
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.damageBonus.total).toBe(0);
  });

  it("suppresses the base Gun Training picks entry, even if a matching pick is stored", () => {
    const doc = makeDoc({
      level: 5,
      weapons: [pistol()],
      archetypes: ["gunslinger:musket-master"],
      // A "pistol" pick would normally match under base Gun Training, but
      // musket master replaces Gun Training entirely, so the base picks
      // entry must not apply even with a matching pick on file.
      gunTrainingPicks: { gunslinger: ["pistol"] },
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.damageBonus.total).toBe(0);
  });
});

describe("Ranged Dex-to-damage escape hatch and defaults", () => {
  it("an explicit damageAbility 'dex' applies ×1 with no Gun Training in play", () => {
    const doc = makeDoc({
      level: 1,
      classTag: "fighter",
      weapons: [
        {
          name: "Longbow",
          category: "ranged",
          attackAbility: "dex",
          damageAbility: "dex",
        },
      ],
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.damageBonus.total).toBe(4);
    expect(sheet.attacks[0]!.damageMultiplier).toBe(1);
  });

  it("explicit 'none' on an otherwise-matching firearm applies nothing", () => {
    const doc = makeDoc({
      level: 5,
      weapons: [musket({ damageAbility: "none" })],
      gunTrainingPicks: { gunslinger: ["musket"] },
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.damageBonus.total).toBe(0);
  });

  it("the default/unset 'str' on a plain ranged weapon contributes nothing (bows gain no Str damage)", () => {
    const doc = makeDoc({
      level: 1,
      classTag: "fighter",
      weapons: [{ name: "Longbow", category: "ranged", attackAbility: "dex" }],
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.damageBonus.total).toBe(0);
  });

  it("melee ability damage is unaffected (a Str longsword still gets Str to damage)", () => {
    const doc = makeDoc({
      level: 1,
      classTag: "fighter",
      weapons: [
        {
          name: "Longsword",
          category: "melee",
          attackAbility: "str",
          group: "longsword",
          damageMultiplier: 1,
        },
      ],
    });
    const sheet = compute(doc, ref);
    // str 14 -> mod +2.
    expect(sheet.attacks[0]!.damageBonus.total).toBe(2);
    expect(sheet.attacks[0]!.damageBonus.components.some((c) => c.source === "Strength")).toBe(
      true,
    );
  });
});

describe("Firearm era and touch AC", () => {
  it("advanced era: touchRangeFt = 5 × rangeIncrement", () => {
    const doc = makeDoc({
      level: 5,
      weapons: [musket({ name: "Advanced Musket", firearmEra: "advanced", rangeIncrement: 20 })],
      gunTrainingPicks: { gunslinger: ["musket"] },
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.firearm?.touchRangeFt).toBe(100);
  });

  it("modern era is treated like advanced: touchRangeFt = 5 × rangeIncrement", () => {
    const doc = makeDoc({
      level: 5,
      weapons: [musket({ name: "Modern Musket", firearmEra: "modern", rangeIncrement: 20 })],
      gunTrainingPicks: { gunslinger: ["musket"] },
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.firearm?.touchRangeFt).toBe(100);
  });

  it("no firearm data is surfaced for a non-firearm ranged weapon", () => {
    const doc = makeDoc({
      level: 1,
      classTag: "fighter",
      weapons: [{ name: "Longbow", category: "ranged", attackAbility: "dex", group: "bow" }],
    });
    const sheet = compute(doc, ref);
    expect(sheet.attacks[0]!.firearm).toBeUndefined();
  });
});
