/**
 * `DISCORD_CLIENT_SECRET` is a Worker secret (`wrangler secret put
 * DISCORD_CLIENT_SECRET` — see README.md), so it never lives in
 * `wrangler.jsonc` `vars` and `wrangler types` can't see it. Merge it into the
 * generated global `Env` (see `worker-configuration.d.ts`, regenerated by
 * `bun run cf-typegen`) here rather than hand-writing the whole binding shape
 * — the KV bindings and `vars` stay generated, per the workers-best-practices
 * convention of never hand-writing `Env`.
 */
declare global {
  interface Env {
    readonly DISCORD_CLIENT_SECRET: string;
    // Feedback -> GitHub-issue path (feedback.ts / githubApp.ts / turnstile.ts).
    // The App private key (PKCS#8 PEM) and the Turnstile secret are Worker
    // secrets; the App id, installation id, and target repo are non-secret
    // `vars` in wrangler.jsonc and stay generated in worker-configuration.d.ts.
    readonly GITHUB_APP_PRIVATE_KEY: string;
    readonly TURNSTILE_SECRET: string;
  }
}

// `cloudflare:test`'s `env` export (used by the vitest-pool-workers test
// suite) is typed as `Cloudflare.Env`, a separate declaration from the
// top-level global `Env` above (see worker-configuration.d.ts) — augment
// both so tests and the Worker itself see the same shape.
declare global {
  namespace Cloudflare {
    interface Env {
      readonly DISCORD_CLIENT_SECRET: string;
      readonly GITHUB_APP_PRIVATE_KEY: string;
      readonly TURNSTILE_SECRET: string;
    }
  }
}

export {};
