/**
 * Renders the markdown body for GitHub issue #74 (the canonical content-gap
 * inventory) from `apps/web/src/model/coverageNotes.ts` — the single source
 * of truth. Prints to stdout; pipe it wherever it needs to go
 * (`gh issue edit 74 --body-file -` or a review file). Never writes to the
 * issue itself — that stays a deliberate, reviewed act.
 *
 * Run via `bun run coverage:issue`.
 */
import {
  COVERAGE_NOTES,
  INTERNAL_GAPS,
  type CoverageNote,
  type InternalGap,
} from "../apps/web/src/model/coverageNotes.js";

function renderCoverageNote(n: CoverageNote): string {
  const detail = n.issueDetail ? `\n\n  ${n.issueDetail}` : "";
  return `### ${n.category}\n\n${n.note}${detail}`;
}

function renderInternalGap(g: InternalGap): string {
  return `### ${g.category}\n\n${g.detail}`;
}

const body = `<!--
Generated by \`bun run coverage:issue\` (scripts/coverage-issue.ts) from
apps/web/src/model/coverageNotes.ts. Do not hand-edit this issue body — edit
the source file and regenerate.
-->

# Deliberately-not-covered content (reference)

A reference inventory of content Ledgermain does not cover today, so gaps are known rather than surprising. Nothing here blocks play.

This is generated from \`apps/web/src/model/coverageNotes.ts\`, the same content that renders as the "What's Not Covered" panel in Settings, plus technical detail with no player-facing surface. To update this issue: edit that file, then run \`bun run coverage:issue\` and paste the output here.

## Known gaps

${COVERAGE_NOTES.map(renderCoverageNote).join("\n\n")}

## Technical / pipeline notes

Gaps with no player-facing surface — not shown in the Settings panel.

${INTERNAL_GAPS.map(renderInternalGap).join("\n\n")}

---

When something on this list comes up at a real table, file an issue for that item and reference this one. This issue stays open as a reference.
`;

console.log(body);
