/**
 * Renders the markdown body for GitHub issue #74 (the canonical content-gap
 * inventory) from `apps/web/src/model/coverageNotes.ts` — the single source
 * of truth.
 *
 * Any edit to `coverageNotes.ts` — a filled gap, a new gap, or a pure copy
 * tweak — leaves #74 stale until this runs.
 *
 * `bun run coverage:issue` prints the body to stdout.
 * `bun run coverage:issue --write` pushes it to #74, which needs write
 * access to the repo. Without that access the write is skipped and the body
 * is printed instead — not an error, since syncing the issue is a maintainer
 * step that a fork-based contributor can't perform and isn't asked to.
 */
import { spawnSync } from "node:child_process";

import {
  COVERAGE_NOTES,
  INTERNAL_GAPS,
  type CoverageGroup,
  type CoverageNote,
  type InternalGap,
} from "../apps/web/src/model/coverageNotes.js";

const ISSUE_NUMBER = "74";

/**
 * Section per gap shape, in render order (object key order). Typing it as a
 * total `Record` means a new `CoverageGroup` can't be added without giving it
 * a section here, so no entry can quietly fall out of the issue.
 */
const GROUPS: Record<CoverageGroup, { heading: string; blurb: string }> = {
  "not-modeled": {
    heading: "Browsable, not modeled",
    blurb:
      'In the picker with its full rules text, but no live number moves. Pickers badge the modeled entries with an "M".',
  },
  "not-adjudicated": {
    heading: "Shown, not adjudicated",
    blurb: "The sheet displays the number and leaves the ruling to the table.",
  },
};

/**
 * One gap. The technical line is the visible one, since this issue is the
 * maintainer's inventory; the player-facing copy is the same text Settings
 * renders, folded away so fifteen entries stay scannable. Entries with no
 * technical line show their copy directly rather than an empty section.
 */
function renderCoverageNote(n: CoverageNote): string {
  if (!n.issueDetail) return `### ${n.category}\n\n${n.note}`;
  return (
    `### ${n.category}\n\n${n.issueDetail}\n\n` +
    `<details><summary>In the app</summary>\n\n${n.note}\n\n</details>`
  );
}

function renderGroup(group: CoverageGroup): string {
  const { heading, blurb } = GROUPS[group];
  const notes = COVERAGE_NOTES.filter((n) => n.group === group);
  return `## ${heading}\n\n${blurb}\n\n${notes.map(renderCoverageNote).join("\n\n")}`;
}

function renderInternalGap(g: InternalGap): string {
  return `### ${g.category}\n\n${g.detail}`;
}

/** Render order, minus any shape every gap of which has since been closed. */
const groupKeys = (Object.keys(GROUPS) as CoverageGroup[]).filter((g) =>
  COVERAGE_NOTES.some((n) => n.group === g),
);

const body = `<!--
Generated by \`bun run coverage:issue --write\` (scripts/coverage-issue.ts)
from apps/web/src/model/coverageNotes.ts. Do not hand-edit this issue body.
Edit the source file and regenerate. Any edit to that file, copy tweaks
included, must be followed by a regenerate, or this issue is stale.
-->

# Deliberately-not-covered content (reference)

What Ledgermain does not cover today, so gaps are known rather than surprising. Nothing here blocks play. ${COVERAGE_NOTES.length} player-facing gaps below, plus ${INTERNAL_GAPS.length} pipeline notes.

Generated from \`apps/web/src/model/coverageNotes.ts\` (the "What's Not Covered" panel in Settings). To update: edit that file, then run \`bun run coverage:issue --write\`.

${groupKeys.map(renderGroup).join("\n\n")}

## Pipeline notes

No player-facing surface, so these aren't in the Settings panel.

${INTERNAL_GAPS.map(renderInternalGap).join("\n\n")}

---

When something on this list comes up at a real table, file an issue for that item and reference this one. This issue stays open as a reference.
`;

/**
 * Whether this checkout can edit the issue body. Only WRITE and above can;
 * TRIAGE and READ can't, which is the normal state for a fork-based
 * contributor. A missing, unauthenticated, or offline `gh` fails the same
 * way and is treated the same, so the fallback path covers every reason the
 * write can't happen rather than only the permissions one.
 */
function canEditIssues(): boolean {
  const result = spawnSync(
    "gh",
    ["repo", "view", "--json", "viewerPermission", "-q", ".viewerPermission"],
    { encoding: "utf8" },
  );
  if (result.error || result.status !== 0) return false;
  return ["ADMIN", "MAINTAIN", "WRITE"].includes(result.stdout.trim());
}

if (!process.argv.includes("--write")) {
  console.log(body);
} else if (!canEditIssues()) {
  console.error(
    `[coverage-issue] Can't write to #${ISSUE_NUMBER} from this checkout, so it was left alone.\n` +
      `[coverage-issue] Expected on a fork: a maintainer syncs the issue. Note the coverageNotes.ts\n` +
      `[coverage-issue] change in your PR and you're done. The rendered body follows.\n`,
  );
  console.log(body);
} else {
  const result = spawnSync("gh", ["issue", "edit", ISSUE_NUMBER, "--body-file", "-"], {
    input: body,
    stdio: ["pipe", "inherit", "inherit"],
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    console.error(
      `[coverage-issue] "gh issue edit ${ISSUE_NUMBER}" failed (exit ${result.status}).`,
    );
    process.exit(result.status ?? 1);
  }
}
