/**
 * Aggregator for the batch-extraction pipeline: composes every per-class file
 * in this directory into the single flat tables `archetype-effects-resolve.ts`
 * (effects) and the engine barrel (classification, an audit artifact — nothing
 * in `compute`/`collect.ts` reads it) already expect. This is the ONLY file a
 * new wave agent's diff should need to touch outside its own new per-class
 * file.
 *
 * Per-class file convention (read this before adding a class): each class gets
 * its own `./<class-tag>.ts` file exporting two `Readonly<Record<string,...>>`
 * consts, both keyed by the archetype feature's own `RefEntity.id`
 * (`"<classTag>:<archetypeSlug>:<featureSlug>:<level>"`):
 *
 *   - `<CLASS>_ARCHETYPE_EFFECTS_EXTRACTED` — machine-extracted `Change`-shaped
 *     effects (`ExtractedArchetypeFeatureEffect`, from `./types.js`).
 *   - `<CLASS>_ARCHETYPE_FEATURE_CLASSIFICATION` — the full per-feature audit
 *     (`ArchetypeFeatureClassificationEntry`, from `./types.js`), covering
 *     EVERY feature of EVERY vendored archetype for that class, not just the
 *     ones that got an entry in the effects table.
 *
 * A class file never imports another class's file, and never needs to touch
 * `./types.js` (shared types + the `c` Change-builder helper already live
 * there). Adding a class means: one new `./<class-tag>.ts` file, plus one new
 * import + one new object-spread line in EACH of the two merges below — no
 * other file in the pipeline changes. Key collisions across classes can't
 * happen because every key is prefixed with its own class tag.
 */

import { BARD_ARCHETYPE_EFFECTS_EXTRACTED, BARD_ARCHETYPE_FEATURE_CLASSIFICATION } from "./bard.js";
import {
  ARCANIST_ARCHETYPE_EFFECTS_EXTRACTED,
  ARCANIST_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./arcanist.js";
import {
  DRUID_ARCHETYPE_EFFECTS_EXTRACTED,
  DRUID_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./druid.js";
import {
  BARBARIAN_ARCHETYPE_EFFECTS_EXTRACTED,
  BARBARIAN_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./barbarian.js";
import {
  FIGHTER_ARCHETYPE_EFFECTS_EXTRACTED,
  FIGHTER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./fighter.js";
import {
  MAGUS_ARCHETYPE_EFFECTS_EXTRACTED,
  MAGUS_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./magus.js";
import { MONK_ARCHETYPE_EFFECTS_EXTRACTED, MONK_ARCHETYPE_FEATURE_CLASSIFICATION } from "./monk.js";
import {
  ORACLE_ARCHETYPE_EFFECTS_EXTRACTED,
  ORACLE_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./oracle.js";
import {
  PALADIN_ARCHETYPE_EFFECTS_EXTRACTED,
  PALADIN_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./paladin.js";
import {
  RANGER_ARCHETYPE_EFFECTS_EXTRACTED,
  RANGER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./ranger.js";
import {
  ROGUE_ARCHETYPE_EFFECTS_EXTRACTED,
  ROGUE_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./rogue.js";
import {
  SORCERER_ARCHETYPE_EFFECTS_EXTRACTED,
  SORCERER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./sorcerer.js";
import {
  WIZARD_ARCHETYPE_EFFECTS_EXTRACTED,
  WIZARD_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./wizard.js";
import {
  WITCH_ARCHETYPE_EFFECTS_EXTRACTED,
  WITCH_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./witch.js";
import {
  ALCHEMIST_ARCHETYPE_EFFECTS_EXTRACTED,
  ALCHEMIST_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./alchemist.js";
import {
  BARBARIAN_UNCHAINED_ARCHETYPE_EFFECTS_EXTRACTED,
  BARBARIAN_UNCHAINED_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./barbarianUnchained.js";
import {
  CAVALIER_ARCHETYPE_EFFECTS_EXTRACTED,
  CAVALIER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./cavalier.js";
import {
  CLERIC_ARCHETYPE_EFFECTS_EXTRACTED,
  CLERIC_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./cleric.js";
import {
  INQUISITOR_ARCHETYPE_EFFECTS_EXTRACTED,
  INQUISITOR_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./inquisitor.js";
import {
  INVESTIGATOR_ARCHETYPE_EFFECTS_EXTRACTED,
  INVESTIGATOR_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./investigator.js";
import {
  ROGUE_UNCHAINED_ARCHETYPE_EFFECTS_EXTRACTED,
  ROGUE_UNCHAINED_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./rogueUnchained.js";
import {
  SLAYER_ARCHETYPE_EFFECTS_EXTRACTED,
  SLAYER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./slayer.js";
import {
  SPIRITUALIST_ARCHETYPE_EFFECTS_EXTRACTED,
  SPIRITUALIST_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./spiritualist.js";
import {
  VIGILANTE_ARCHETYPE_EFFECTS_EXTRACTED,
  VIGILANTE_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./vigilante.js";
import {
  GUNSLINGER_ARCHETYPE_EFFECTS_EXTRACTED,
  GUNSLINGER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./gunslinger.js";
import {
  HUNTER_ARCHETYPE_EFFECTS_EXTRACTED,
  HUNTER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./hunter.js";
import {
  KINETICIST_ARCHETYPE_EFFECTS_EXTRACTED,
  KINETICIST_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./kineticist.js";
import {
  MEDIUM_ARCHETYPE_EFFECTS_EXTRACTED,
  MEDIUM_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./medium.js";
import {
  MESMERIST_ARCHETYPE_EFFECTS_EXTRACTED,
  MESMERIST_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./mesmerist.js";
import {
  MONK_UNCHAINED_ARCHETYPE_EFFECTS_EXTRACTED,
  MONK_UNCHAINED_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./monkUnchained.js";
import {
  OCCULTIST_ARCHETYPE_EFFECTS_EXTRACTED,
  OCCULTIST_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./occultist.js";
import {
  SKALD_ARCHETYPE_EFFECTS_EXTRACTED,
  SKALD_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./skald.js";
import {
  SUMMONER_ARCHETYPE_EFFECTS_EXTRACTED,
  SUMMONER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./summoner.js";
import {
  WARPRIEST_ARCHETYPE_EFFECTS_EXTRACTED,
  WARPRIEST_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./warpriest.js";
import {
  ANTIPALADIN_ARCHETYPE_EFFECTS_EXTRACTED,
  ANTIPALADIN_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./antipaladin.js";
import {
  BLOODRAGER_ARCHETYPE_EFFECTS_EXTRACTED,
  BLOODRAGER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./bloodrager.js";
import {
  BRAWLER_ARCHETYPE_EFFECTS_EXTRACTED,
  BRAWLER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./brawler.js";
import {
  NINJA_ARCHETYPE_EFFECTS_EXTRACTED,
  NINJA_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./ninja.js";
import {
  PSYCHIC_ARCHETYPE_EFFECTS_EXTRACTED,
  PSYCHIC_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./psychic.js";
import {
  SAMURAI_ARCHETYPE_EFFECTS_EXTRACTED,
  SAMURAI_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./samurai.js";
import {
  SHAMAN_ARCHETYPE_EFFECTS_EXTRACTED,
  SHAMAN_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./shaman.js";
import {
  SHIFTER_ARCHETYPE_EFFECTS_EXTRACTED,
  SHIFTER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./shifter.js";
import {
  SUMMONER_UNCHAINED_ARCHETYPE_EFFECTS_EXTRACTED,
  SUMMONER_UNCHAINED_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./summonerUnchained.js";
import {
  SWASHBUCKLER_ARCHETYPE_EFFECTS_EXTRACTED,
  SWASHBUCKLER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./swashbuckler.js";
import type {
  ArchetypeFeatureClassificationEntry,
  ExtractedArchetypeFeatureEffect,
} from "./types.js";

export const ARCHETYPE_FEATURE_EFFECTS_EXTRACTED: Readonly<
  Record<string, ExtractedArchetypeFeatureEffect>
> = {
  ...ARCANIST_ARCHETYPE_EFFECTS_EXTRACTED,
  ...BARBARIAN_ARCHETYPE_EFFECTS_EXTRACTED,
  ...BARD_ARCHETYPE_EFFECTS_EXTRACTED,
  ...DRUID_ARCHETYPE_EFFECTS_EXTRACTED,
  ...FIGHTER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...MAGUS_ARCHETYPE_EFFECTS_EXTRACTED,
  ...MONK_ARCHETYPE_EFFECTS_EXTRACTED,
  ...ORACLE_ARCHETYPE_EFFECTS_EXTRACTED,
  ...PALADIN_ARCHETYPE_EFFECTS_EXTRACTED,
  ...RANGER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...ROGUE_ARCHETYPE_EFFECTS_EXTRACTED,
  ...SORCERER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...WITCH_ARCHETYPE_EFFECTS_EXTRACTED,
  ...WIZARD_ARCHETYPE_EFFECTS_EXTRACTED,
  ...ALCHEMIST_ARCHETYPE_EFFECTS_EXTRACTED,
  ...BARBARIAN_UNCHAINED_ARCHETYPE_EFFECTS_EXTRACTED,
  ...CAVALIER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...CLERIC_ARCHETYPE_EFFECTS_EXTRACTED,
  ...INQUISITOR_ARCHETYPE_EFFECTS_EXTRACTED,
  ...INVESTIGATOR_ARCHETYPE_EFFECTS_EXTRACTED,
  ...ROGUE_UNCHAINED_ARCHETYPE_EFFECTS_EXTRACTED,
  ...SLAYER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...SPIRITUALIST_ARCHETYPE_EFFECTS_EXTRACTED,
  ...VIGILANTE_ARCHETYPE_EFFECTS_EXTRACTED,
  ...GUNSLINGER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...HUNTER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...KINETICIST_ARCHETYPE_EFFECTS_EXTRACTED,
  ...MEDIUM_ARCHETYPE_EFFECTS_EXTRACTED,
  ...MESMERIST_ARCHETYPE_EFFECTS_EXTRACTED,
  ...MONK_UNCHAINED_ARCHETYPE_EFFECTS_EXTRACTED,
  ...OCCULTIST_ARCHETYPE_EFFECTS_EXTRACTED,
  ...SKALD_ARCHETYPE_EFFECTS_EXTRACTED,
  ...SUMMONER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...WARPRIEST_ARCHETYPE_EFFECTS_EXTRACTED,
  ...ANTIPALADIN_ARCHETYPE_EFFECTS_EXTRACTED,
  ...BLOODRAGER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...BRAWLER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...NINJA_ARCHETYPE_EFFECTS_EXTRACTED,
  ...PSYCHIC_ARCHETYPE_EFFECTS_EXTRACTED,
  ...SAMURAI_ARCHETYPE_EFFECTS_EXTRACTED,
  ...SHAMAN_ARCHETYPE_EFFECTS_EXTRACTED,
  ...SHIFTER_ARCHETYPE_EFFECTS_EXTRACTED,
  ...SUMMONER_UNCHAINED_ARCHETYPE_EFFECTS_EXTRACTED,
  ...SWASHBUCKLER_ARCHETYPE_EFFECTS_EXTRACTED,
};

export const ARCHETYPE_FEATURE_CLASSIFICATION: Readonly<
  Record<string, ArchetypeFeatureClassificationEntry>
> = {
  ...ARCANIST_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...BARBARIAN_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...BARD_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...DRUID_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...FIGHTER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...MAGUS_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...MONK_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...ORACLE_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...PALADIN_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...RANGER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...ROGUE_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...SORCERER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...WITCH_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...WIZARD_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...ALCHEMIST_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...BARBARIAN_UNCHAINED_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...CAVALIER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...CLERIC_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...INQUISITOR_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...INVESTIGATOR_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...ROGUE_UNCHAINED_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...SLAYER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...SPIRITUALIST_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...VIGILANTE_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...GUNSLINGER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...HUNTER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...KINETICIST_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...MEDIUM_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...MESMERIST_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...MONK_UNCHAINED_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...OCCULTIST_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...SKALD_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...SUMMONER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...WARPRIEST_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...ANTIPALADIN_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...BLOODRAGER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...BRAWLER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...NINJA_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...PSYCHIC_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...SAMURAI_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...SHAMAN_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...SHIFTER_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...SUMMONER_UNCHAINED_ARCHETYPE_FEATURE_CLASSIFICATION,
  ...SWASHBUCKLER_ARCHETYPE_FEATURE_CLASSIFICATION,
};

export {
  type ExtractionConfidence,
  type ExtractedArchetypeFeatureEffect,
  type ArchetypeFeatureClassificationBucket,
  type ArchetypeFeatureClassificationEntry,
} from "./types.js";
// Re-exported for callers that want a specific class's slice directly (e.g.
// fixture tests spot-checking one class) without importing the aggregator's
// merged table.
export { BARD_ARCHETYPE_EFFECTS_EXTRACTED, BARD_ARCHETYPE_FEATURE_CLASSIFICATION } from "./bard.js";
export {
  ARCANIST_ARCHETYPE_EFFECTS_EXTRACTED,
  ARCANIST_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./arcanist.js";
export {
  DRUID_ARCHETYPE_EFFECTS_EXTRACTED,
  DRUID_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./druid.js";
export {
  FIGHTER_ARCHETYPE_EFFECTS_EXTRACTED,
  FIGHTER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./fighter.js";
export { MONK_ARCHETYPE_EFFECTS_EXTRACTED, MONK_ARCHETYPE_FEATURE_CLASSIFICATION } from "./monk.js";
export {
  ORACLE_ARCHETYPE_EFFECTS_EXTRACTED,
  ORACLE_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./oracle.js";
export {
  PALADIN_ARCHETYPE_EFFECTS_EXTRACTED,
  PALADIN_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./paladin.js";
export {
  RANGER_ARCHETYPE_EFFECTS_EXTRACTED,
  RANGER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./ranger.js";
export {
  ROGUE_ARCHETYPE_EFFECTS_EXTRACTED,
  ROGUE_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./rogue.js";
export {
  SORCERER_ARCHETYPE_EFFECTS_EXTRACTED,
  SORCERER_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./sorcerer.js";
export {
  BARBARIAN_ARCHETYPE_EFFECTS_EXTRACTED,
  BARBARIAN_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./barbarian.js";
export {
  MAGUS_ARCHETYPE_EFFECTS_EXTRACTED,
  MAGUS_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./magus.js";
export {
  WIZARD_ARCHETYPE_EFFECTS_EXTRACTED,
  WIZARD_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./wizard.js";
export {
  WITCH_ARCHETYPE_EFFECTS_EXTRACTED,
  WITCH_ARCHETYPE_FEATURE_CLASSIFICATION,
} from "./witch.js";
