/**
 * Witch's slice of the pipeline, repeating the fighter pilot's methodology
 * (`./fighter.ts`) for the 42 vendored witch archetypes / 188 archetype
 * features. Per the per-class file convention (`./index.ts`'s doc comment),
 * this file owns BOTH of witch's pipeline artifacts —
 * `WITCH_ARCHETYPE_EFFECTS_EXTRACTED` (the machine-extracted `Change`-shaped
 * effects table) and `WITCH_ARCHETYPE_FEATURE_CLASSIFICATION` (the full
 * per-feature audit) — so a future wave working on a different class never
 * has a reason to touch this file; only `index.ts` (the aggregator) needs
 * one new import + one new spread per class.
 *
 * ── WITCH_ARCHETYPE_FEATURE_CLASSIFICATION ────────────────────────────────
 *
 * Every feature of every vendored witch archetype, read in full (188 is
 * small enough to read exhaustively rather than sample) and bucketed as
 * `numeric` / `situational` / `subsystem` / `blocked` per the same rubric
 * `fighter.ts` established:
 *  - "numeric": an unconditional bonus expressible via a real
 *    `packages/engine/src/targets.ts` target.
 *  - "situational": a REAL number scoped to a specific maneuver, weapon,
 *    location, relationship condition, or trigger the engine can't check
 *    without over-applying — vendored prose stays the source of truth.
 *  - "subsystem": grants an unrelated ability/resource/choice list, swaps
 *    the familiar/patron/spell-list for a differently-flavored version of
 *    the same subsystem, buffs a creature OTHER than the witch (an ally or
 *    an aura target), or otherwise has no Change-shaped number to extract.
 *  - "blocked": a genuine composition trap the engine structurally can't
 *    express without new machinery — recorded rather than guessed at.
 *
 * Witch is overwhelmingly hex/patron/familiar-flavored: the class's whole
 * identity is trading one flavor of hex/patron/familiar for another, or
 * bolting on an activated, resource-gated ability (swift/standard action,
 * uses/day) in the same vein as ki/grit/panache/Archaeologist's Luck
 * (`archetype-effects.ts`) — none of which is a flat always-on number. That
 * makes the `subsystem` bucket dominant here (172 of 188 features) and the
 * `numeric` bucket genuinely small (2) — honesty over volume, per this
 * pipeline's own rule (`docs/engine-cookbook.md` §3.4): a feature is only
 * promoted to `numeric` when the text is unconditional and lands on a real
 * target, never because a bucket "should" have more entries.
 *
 * One `blocked` entry: Seducer's Otherworldly Allure substitutes Charisma
 * for Intelligence across every witch class feature (bonus spells, max
 * spell level, spells known, every spell/hex save DC) — a real,
 * unconditional effect, but `ability-substitution.ts`'s registry only covers
 * a fixed set of derived slots (AC, initiative, attack/damage, CMB/CMD,
 * Reflex saves) and has no "casting ability" slot, while the witch's
 * spellcasting formulas hardcode Intelligence rather than reading through a
 * swappable slot. Composing this correctly needs a new substitution slot
 * (engine work), not a table entry.
 */

import {
  c,
  type ArchetypeFeatureClassificationEntry,
  type ExtractedArchetypeFeatureEffect,
} from "./types.js";

/**
 * Keyed by the archetype feature's own `RefEntity.id` (same key
 * `archetype-effects.ts` uses).
 */
export const WITCH_ARCHETYPE_EFFECTS_EXTRACTED: Readonly<
  Record<string, ExtractedArchetypeFeatureEffect>
> = {
  // Hagbound's "Hunched Muscle" (Pathfinder Player Companion: Blood of the
  // Coven p. 16): "She gains a +2 size bonus to her Strength score. This
  // bonus increases by 2 at 8th level and 14th level, to a maximum of +6."
  // Unconditional, no gating clause — a flat, always-on ability-score bonus,
  // same target shape as the sorcerer bloodline power/eidolon evolution
  // ability-score bumps elsewhere in the engine (`c("...", "str", "size")`).
  "witch:hagbound:hunched-muscle:2": {
    changes: [
      c("2 + if(gte(@class.unlevel, 8), 2, 0) + if(gte(@class.unlevel, 14), 2, 0)", "str", "size"),
    ],
    detail: (level) => `+${level >= 14 ? 6 : level >= 8 ? 4 : 2} size bonus to Strength`,
    confidence: "high",
    provenance:
      "She gains a +2 size bonus to her Strength score. This bonus increases by 2 at 8th level and 14th level, to a maximum of +6.",
  },

  // Herb Witch's "Herb Lore" (Ultimate Wilderness p. 89): "she gains a bonus
  // on Profession (herbalist) checks equal to half her class level."
  // Unconditional, no stated minimum (unlike Cloistered Cleric's Breadth of
  // Knowledge). Targets a specific named Profession instance, same
  // "player must have created a matching-slug skill instance" shape as the
  // hand-verified table's Sorcerer of Sleep -> `skill.crf.alchemy` precedent
  // (`archetype-effects.ts`).
  "witch:herb-witch:herb-lore:0": {
    changes: [c("floor(@class.unlevel / 2)", "skill.pro.herbalist")],
    detail: (level) => `+${Math.floor(level / 2)} Profession (herbalist)`,
    confidence: "high",
    provenance: "she gains a bonus on Profession (herbalist) checks equal to half her class level.",
  },
};

export const WITCH_ARCHETYPE_FEATURE_CLASSIFICATION: Readonly<
  Record<string, ArchetypeFeatureClassificationEntry>
> = {
  "witch:alley-witch:child-of-the-streets:0": {
    archetypeId: "witch:alley-witch",
    name: "Child of the Streets",
    level: 0,
    bucket: "subsystem",
    note: "class-skill list swap, no Change-shaped target",
  },
  "witch:alley-witch:crowd-patron:0": {
    archetypeId: "witch:alley-witch",
    name: "Crowd Patron",
    level: 1,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself (a fixed bonus-spell schedule replacing the normal patron choice)",
  },
  "witch:alley-witch:hex-trader:6": {
    archetypeId: "witch:alley-witch",
    name: "Hex Trader",
    level: 6,
    bucket: "subsystem",
    note: "lets her seal a known hex into a token another creature can trigger later — a delivery-mechanism reflavor of an existing hex, no independent number",
  },
  "witch:alley-witch:speak-to-the-city:0": {
    archetypeId: "witch:alley-witch",
    name: "Speak to the City",
    level: 1,
    bucket: "situational",
    note: "+2 (scaling +2 every 5 levels from 6th) on initiative/Knowledge (local)/Perception/Stealth/Sense Motive, but only within a single settlement she's bonded to — a location the engine has no concept of tracking, so real but conditional/narrowly-scoped number (specific maneuver, target state, location, or relationship condition) — not expressible without over-applying, per the honesty bar",
  },
  "witch:ashiftah:deliver-touch-spells:3": {
    archetypeId: "witch:ashiftah",
    name: "Deliver Touch Spells",
    level: 3,
    bucket: "subsystem",
    note: "touch-spell delivery mechanism (via a torn strip of her veil) — a range/logistics rider, no independent number",
  },
  "witch:ashiftah:fog-of-war:6": {
    archetypeId: "witch:ashiftah",
    name: "Fog of War",
    level: 6,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:ashiftah:ghostwalk:2": {
    archetypeId: "witch:ashiftah",
    name: "Ghostwalk",
    level: 2,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:ashiftah:protecting-veil:0": {
    archetypeId: "witch:ashiftah",
    name: "Protecting Veil",
    level: 0,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself",
  },
  "witch:beast-bonded:bonded-item:1": {
    archetypeId: "witch:beast-bonded",
    name: "Bonded Item",
    level: 1,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself",
  },
  "witch:bonded-witch:bonded-item:1": {
    archetypeId: "witch:bonded-witch",
    name: "Bonded Item",
    level: 1,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself",
  },
  "witch:bouda:alignment:0": {
    archetypeId: "witch:bouda",
    name: "Alignment",
    level: 0,
    bucket: "subsystem",
    note: "narrative/utility text, no numeric or Change-shaped effect",
  },
  "witch:bouda:bouda-s-eye:0": {
    archetypeId: "witch:bouda",
    name: "Bouda’s Eye",
    level: 8,
    bucket: "situational",
    note: "a hex effect: a -2 (-4 at 8th level) penalty to one of AC/ability checks/attack rolls/saving throws/skill checks on a single willing-to-attempt target, Will save applies — a per-use hex targeting an enemy, real but conditional/narrowly-scoped number (specific maneuver, target state, location, or relationship condition) — not expressible without over-applying, per the honesty bar",
  },
  "witch:bouda:fetish:0": {
    archetypeId: "witch:bouda",
    name: "Fetish",
    level: 3,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself",
  },
  "witch:bouda:hyena-shape:10": {
    archetypeId: "witch:bouda",
    name: "Hyena Shape",
    level: 10,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:cartomancer:deadly-dealer:2": {
    archetypeId: "witch:cartomancer",
    name: "Deadly Dealer",
    level: 2,
    bucket: "subsystem",
    note: "grants the Deadly Dealer feat (see sidebar) plus Arcane Strike's benefit scoped only to using it — a named-feat grant, no independent number",
  },
  "witch:cartomancer:grand-hexes:0": {
    archetypeId: "witch:cartomancer",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:cartomancer:hexes:0": {
    archetypeId: "witch:cartomancer",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:cartomancer:major-hexes:0": {
    archetypeId: "witch:cartomancer",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:cartomancer:spell-deck:0": {
    archetypeId: "witch:cartomancer",
    name: "Spell Deck",
    level: 3,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself",
  },
  "witch:coral-witch:coral-familiar:0": {
    archetypeId: "witch:coral-witch",
    name: "Coral Familiar",
    level: 0,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself",
  },
  "witch:coral-witch:grand-hexes:0": {
    archetypeId: "witch:coral-witch",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:coral-witch:hexes:0": {
    archetypeId: "witch:coral-witch",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:coral-witch:immovability:8": {
    archetypeId: "witch:coral-witch",
    name: "Immovability",
    level: 8,
    bucket: "situational",
    note: "class level to CMD, but only against bull rush/overrun/reposition/grapple-to-move/pull/push AND only if she didn't move last round and stands on solid ground — a specific-maneuver-plus-posture gate, real but conditional/narrowly-scoped number (specific maneuver, target state, location, or relationship condition) — not expressible without over-applying, per the honesty bar",
  },
  "witch:coral-witch:major-hexes:0": {
    archetypeId: "witch:coral-witch",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:coral-witch:patron:0": {
    archetypeId: "witch:coral-witch",
    name: "Patron",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:coral-witch:waves-spirit-hex:0": {
    archetypeId: "witch:coral-witch",
    name: "Waves Spirit Hex",
    level: 0,
    bucket: "subsystem",
    note: "grants access to the shaman waves spirit's hex list — an option-list grant, no numeric effect",
  },
  "witch:demon-sworn:cruel-hex:0": {
    archetypeId: "witch:demon-sworn",
    name: "Cruel Hex",
    level: 0,
    bucket: "subsystem",
    note: "adds a nonlethal (and self-damaging on a natural 4) damage die to every hex she casts — hexes carry no damage-dealing Change target in this engine to attach a rider to",
  },
  "witch:demon-sworn:demonic-pact:0": {
    archetypeId: "witch:demon-sworn",
    name: "Demonic Pact",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:demon-sworn:manifest-pact:6": {
    archetypeId: "witch:demon-sworn",
    name: "Manifest Pact",
    level: 6,
    bucket: "subsystem",
    note: "grants Improved Familiar as a bonus feat (forced to a quasit) plus a permanent negative level on replacement — a named-feat/narrative grant, no independent number",
  },
  "witch:dimensional-occultist:commune-with-familiar:8": {
    archetypeId: "witch:dimensional-occultist",
    name: "Commune with Familiar",
    level: 8,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:dimensional-occultist:dimensional-augmentation:2": {
    archetypeId: "witch:dimensional-occultist",
    name: "Dimensional Augmentation",
    level: 2,
    bucket: "subsystem",
    note: "a limited-use ritual that boosts one spell's effective caster level — 'cl' isn't a target compute() consumes (see targets.ts's UNAPPLIED_TARGET_LABELS), and it's additionally a per-day activated ability, not a baseline number",
  },
  "witch:dimensional-occultist:dimensional-waypoints:12": {
    archetypeId: "witch:dimensional-occultist",
    name: "Dimensional Waypoints",
    level: 12,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:dimensional-occultist:patron:0": {
    archetypeId: "witch:dimensional-occultist",
    name: "Patron",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:dreamweaver:class-skills:0": {
    archetypeId: "witch:dreamweaver",
    name: "Class Skills",
    level: 0,
    bucket: "subsystem",
    note: "class-skill list swap, no Change-shaped target",
  },
  "witch:dreamweaver:dream-possession:10": {
    archetypeId: "witch:dreamweaver",
    name: "Dream Possession",
    level: 10,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:dreamweaver:dream-spinner:2": {
    archetypeId: "witch:dreamweaver",
    name: "Dream Spinner",
    level: 2,
    bucket: "situational",
    note: "+1 to a mind-affecting spell's DC, but only against a target already sleeping from her own slumber hex or spell — real but conditional/narrowly-scoped number (specific maneuver, target state, location, or relationship condition) — not expressible without over-applying, per the honesty bar",
  },
  "witch:dreamweaver:dream-thief:6": {
    archetypeId: "witch:dreamweaver",
    name: "Dream Thief",
    level: 6,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:dreamweaver:grand-hexes:0": {
    archetypeId: "witch:dreamweaver",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:dreamweaver:hexes:0": {
    archetypeId: "witch:dreamweaver",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:dreamweaver:major-hexes:0": {
    archetypeId: "witch:dreamweaver",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:dreamweaver:patron:0": {
    archetypeId: "witch:dreamweaver",
    name: "Patron",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:dreamweaver:spells:0": {
    archetypeId: "witch:dreamweaver",
    name: "Spells",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:flood-walker:alignment:0": {
    archetypeId: "witch:flood-walker",
    name: "Alignment",
    level: 0,
    bucket: "subsystem",
    note: "narrative/utility text, no numeric or Change-shaped effect",
  },
  "witch:flood-walker:breath-siphon:10": {
    archetypeId: "witch:flood-walker",
    name: "Breath Siphon",
    level: 10,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:flood-walker:class-skills:0": {
    archetypeId: "witch:flood-walker",
    name: "Class Skills",
    level: 0,
    bucket: "subsystem",
    note: "class-skill list swap, no Change-shaped target",
  },
  "witch:flood-walker:gasping-breath-aura:0": {
    archetypeId: "witch:flood-walker",
    name: "Gasping Breath Aura",
    level: 1,
    bucket: "subsystem",
    note: "grants its benefit to a creature other than the witch herself (an ally, or a battlefield-wide aura affecting allies/undead) — no engine mechanism for a sheet's Change to buff a third party",
  },
  "witch:flood-walker:grand-hexes:0": {
    archetypeId: "witch:flood-walker",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:flood-walker:hexes:0": {
    archetypeId: "witch:flood-walker",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:flood-walker:major-hexes:0": {
    archetypeId: "witch:flood-walker",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:flood-walker:patron-spells:0": {
    archetypeId: "witch:flood-walker",
    name: "Patron Spells",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:flood-walker:river-stride:6": {
    archetypeId: "witch:flood-walker",
    name: "River Stride",
    level: 6,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:gingerbread-witch:cauldron-cook:0": {
    archetypeId: "witch:gingerbread-witch",
    name: "Cauldron Cook",
    level: 1,
    bucket: "subsystem",
    note: "grants the cauldron and child-scent hexes (plus cook people at 10th) — a fixed-hex grant, no independent number",
  },
  "witch:gingerbread-witch:confection-conjuring:8": {
    archetypeId: "witch:gingerbread-witch",
    name: "Confection Conjuring",
    level: 8,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:gingerbread-witch:gingerbread-familiar:0": {
    archetypeId: "witch:gingerbread-witch",
    name: "Gingerbread Familiar",
    level: 0,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself",
  },
  "witch:gingerbread-witch:gruesome-gobbler:12": {
    archetypeId: "witch:gingerbread-witch",
    name: "Gruesome Gobbler",
    level: 12,
    bucket: "subsystem",
    note: "grants a natural weapon attack — no Change target for adding a new attack option (same posture as every other archetype's granted natural attack)",
  },
  "witch:gingerbread-witch:horrible-hunger:16": {
    archetypeId: "witch:gingerbread-witch",
    name: "Horrible Hunger",
    level: 16,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:gingerbread-witch:tricky-treats-hex:4": {
    archetypeId: "witch:gingerbread-witch",
    name: "Tricky Treats Hex",
    level: 4,
    bucket: "subsystem",
    note: "a unique crafted-item hex (feast of ashes/goodberry-like effects) — no baseline numeric effect on the witch's own sheet",
  },
  "witch:gravewalker:aura-of-desecration:1": {
    archetypeId: "witch:gravewalker",
    name: "Aura of Desecration",
    level: 1,
    bucket: "subsystem",
    note: "grants its benefit to a creature other than the witch herself (an ally, or a battlefield-wide aura affecting allies/undead) — no engine mechanism for a sheet's Change to buff a third party (boosts allies' channeled negative energy DC and undead's turn resistance within a radius)",
  },
  "witch:gravewalker:bonethrall:1": {
    archetypeId: "witch:gravewalker",
    name: "Bonethrall",
    level: 1,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:gravewalker:grand-hexes:0": {
    archetypeId: "witch:gravewalker",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:gravewalker:hexes:0": {
    archetypeId: "witch:gravewalker",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:gravewalker:major-hexes:0": {
    archetypeId: "witch:gravewalker",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:gravewalker:possess-undead:0": {
    archetypeId: "witch:gravewalker",
    name: "Possess Undead",
    level: 8,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:gravewalker:spell-poppet:0": {
    archetypeId: "witch:gravewalker",
    name: "Spell Poppet",
    level: 3,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself",
  },
  "witch:gravewalker:spells:0": {
    archetypeId: "witch:gravewalker",
    name: "Spells",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:hag-of-gyronna:curdle-thoughts:2": {
    archetypeId: "witch:hag-of-gyronna",
    name: "Curdle Thoughts",
    level: 2,
    bucket: "situational",
    note: "+2 Diplomacy/Bluff scoped to 'sowing suspicion/hatred' specifically, plus a limited-uses-per-day +2 fear-spell DC bump — both narrowly scoped/resource-gated, real but conditional/narrowly-scoped number (specific maneuver, target state, location, or relationship condition) — not expressible without over-applying, per the honesty bar",
  },
  "witch:hag-of-gyronna:hag-crony:12": {
    archetypeId: "witch:hag-of-gyronna",
    name: "Hag Crony",
    level: 12,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:hag-of-gyronna:patron:0": {
    archetypeId: "witch:hag-of-gyronna",
    name: "Patron",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:hag-of-gyronna:spells:0": {
    archetypeId: "witch:hag-of-gyronna",
    name: "Spells",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:hag-of-gyronna:sunder-hope:8": {
    archetypeId: "witch:hag-of-gyronna",
    name: "Sunder Hope",
    level: 8,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:hagbound:hag-s-claws:0": {
    archetypeId: "witch:hagbound",
    name: "Hag’s Claws",
    level: 1,
    bucket: "subsystem",
    note: "grants a natural weapon attack — no Change target for adding a new attack option (same posture as every other archetype's granted natural attack)",
  },
  "witch:hagbound:hag-transformation:20": {
    archetypeId: "witch:hagbound",
    name: "Hag Transformation",
    level: 20,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:hagbound:hagbound:0": {
    archetypeId: "witch:hagbound",
    name: "Hagbound",
    level: 0,
    bucket: "subsystem",
    note: "narrative/utility text, no numeric or Change-shaped effect",
  },
  "witch:hagbound:hunched-muscle:2": {
    archetypeId: "witch:hagbound",
    name: "Hunched Muscle",
    level: 2,
    bucket: "numeric",
    note: "flat, always-on +2 size bonus to Strength score, +2 more at 8th and 14th (max +6) — unconditional, no gating clause in the text",
  },
  "witch:hagbound:vain-glamour:4": {
    archetypeId: "witch:hagbound",
    name: "Vain Glamour",
    level: 4,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:hagbound:vile-curse:10": {
    archetypeId: "witch:hagbound",
    name: "Vile Curse",
    level: 10,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:havocker:infusion:2": {
    archetypeId: "witch:havocker",
    name: "Infusion",
    level: 2,
    bucket: "subsystem",
    note: "grants a kineticist infusion wild talent — a whole borrowed subsystem (kinetic blast infusions), no Change-shaped number",
  },
  "witch:havocker:patron-element:0": {
    archetypeId: "witch:havocker",
    name: "Patron Element",
    level: 1,
    bucket: "subsystem",
    note: "replaces the patron with a kineticist elemental focus + kinetic blast — a whole borrowed subsystem, no Change-shaped number",
  },
  "witch:havocker:spellburn:0": {
    archetypeId: "witch:havocker",
    name: "Spellburn",
    level: 2,
    bucket: "subsystem",
    note: "a resource-conversion mechanic (spend a prepared spell to fuel a kinetic blast infusion), not a flat number",
  },
  "witch:hedge-witch:empathic-healing:0": {
    archetypeId: "witch:hedge-witch",
    name: "Empathic Healing",
    level: 8,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:hedge-witch:patron:0": {
    archetypeId: "witch:hedge-witch",
    name: "Patron",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:hedge-witch:spontaneous-healing:0": {
    archetypeId: "witch:hedge-witch",
    name: "Spontaneous Healing",
    level: 4,
    bucket: "subsystem",
    note: "a spell-conversion mechanic (spend a prepared spell to cast an unprepared cure spell), not a flat number",
  },
  "witch:herb-witch:grand-hexes:0": {
    archetypeId: "witch:herb-witch",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:herb-witch:herb-lore:0": {
    archetypeId: "witch:herb-witch",
    name: "Herb Lore",
    level: 0,
    bucket: "numeric",
    note: "flat, unconditional bonus on Profession (herbalist) checks equal to half class level (no minimum stated) — same 'name a specific Craft/Profession instance' shape as the hand-verified table's Sorcerer of Sleep -> skill.crf.alchemy precedent",
  },
  "witch:herb-witch:hexes:0": {
    archetypeId: "witch:herb-witch",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:herb-witch:major-hexes:0": {
    archetypeId: "witch:herb-witch",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:herb-witch:patron-spells:0": {
    archetypeId: "witch:herb-witch",
    name: "Patron Spells",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:hex-channeler:channel-energy:2": {
    archetypeId: "witch:hex-channeler",
    name: "Channel Energy",
    level: 2,
    bucket: "subsystem",
    note: "grants a full cleric-style Channel Energy subsystem (uses/day, 1d6 healing/damage pool) — a whole borrowed subsystem, no Change-shaped number to extract for a single feature entry",
  },
  "witch:hex-channeler:grand-hexes:0": {
    archetypeId: "witch:hex-channeler",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:hex-channeler:hexes:0": {
    archetypeId: "witch:hex-channeler",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:hex-channeler:major-hexes:0": {
    archetypeId: "witch:hex-channeler",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:invoker:invoke-patron:1": {
    archetypeId: "witch:invoker",
    name: "Invoke Patron",
    level: 1,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply (a hunter's-animal-focus-style ability with 10 player-chosen facets, each granting a different rider — none of them baseline)",
  },
  "witch:invoker:second-invocation:10": {
    archetypeId: "witch:invoker",
    name: "Second Invocation",
    level: 10,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:jinx-witch:class-skills:0": {
    archetypeId: "witch:jinx-witch",
    name: "Class Skills",
    level: 0,
    bucket: "subsystem",
    note: "class-skill list swap, no Change-shaped target",
  },
  "witch:jinx-witch:grand-hexes:0": {
    archetypeId: "witch:jinx-witch",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:jinx-witch:hexes:0": {
    archetypeId: "witch:jinx-witch",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:jinx-witch:jinx-eating:2": {
    archetypeId: "witch:jinx-witch",
    name: "Jinx-Eating",
    level: 2,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:jinx-witch:jinx-feast:10": {
    archetypeId: "witch:jinx-witch",
    name: "Jinx-Feast",
    level: 10,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:jinx-witch:jinx-gorging:6": {
    archetypeId: "witch:jinx-witch",
    name: "Jinx-Gorging",
    level: 6,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:jinx-witch:major-hexes:0": {
    archetypeId: "witch:jinx-witch",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:jinx-witch:spell-awareness:0": {
    archetypeId: "witch:jinx-witch",
    name: "Spell Awareness",
    level: 0,
    bucket: "situational",
    note: "+1/2 witch level to Spellcraft, but only to identify a spell that is currently targeting her — real but conditional/narrowly-scoped number (specific maneuver, target state, location, or relationship condition) — not expressible without over-applying, per the honesty bar",
  },
  "witch:ley-line-guardian:conduit-surge:1": {
    archetypeId: "witch:ley-line-guardian",
    name: "Conduit Surge",
    level: 1,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:ley-line-guardian:ley-line-powered:0": {
    archetypeId: "witch:ley-line-guardian",
    name: "Ley Line Powered",
    level: 0,
    bucket: "subsystem",
    note: "converts the witch to spontaneous casting — a spellcasting-mechanics change, no Change-shaped number",
  },
  "witch:medium:ectoplasmic-aptitude:2": {
    archetypeId: "witch:medium",
    name: "Ectoplasmic Aptitude",
    level: 2,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:medium:grand-hexes:0": {
    archetypeId: "witch:medium",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:medium:hexes:0": {
    archetypeId: "witch:medium",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:medium:major-hexes:0": {
    archetypeId: "witch:medium",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:medium:patron:0": {
    archetypeId: "witch:medium",
    name: "Patron",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:medium:shared-subconscious:6": {
    archetypeId: "witch:medium",
    name: "Shared Subconscious",
    level: 6,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:medium:soul-walker:20": {
    archetypeId: "witch:medium",
    name: "Soul Walker",
    level: 20,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:mirror-witch:hardness:0": {
    archetypeId: "witch:mirror-witch",
    name: "Hardness",
    level: 0,
    bucket: "subsystem",
    note: "a table entry describing the patron mirror OBJECT's own hardness, not a bonus to the witch — no numeric effect on her sheet",
  },
  "witch:mirror-witch:hit-points:0": {
    archetypeId: "witch:mirror-witch",
    name: "Hit Points",
    level: 0,
    bucket: "subsystem",
    note: "a table entry describing the patron mirror OBJECT's own hit points, not a bonus to the witch — no numeric effect on her sheet",
  },
  "witch:mirror-witch:intelligence:0": {
    archetypeId: "witch:mirror-witch",
    name: "Intelligence",
    level: 0,
    bucket: "subsystem",
    note: "a table entry describing the patron mirror's own (non-witch) Intelligence score — no numeric effect on the witch's sheet",
  },
  "witch:mirror-witch:special:0": {
    archetypeId: "witch:mirror-witch",
    name: "Special",
    level: 0,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply (a bundle of once-per-day insight bonuses/spell-likes gated on consulting the mirror)",
  },
  "witch:mountain-witch:grand-hexes:0": {
    archetypeId: "witch:mountain-witch",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:mountain-witch:hexes:0": {
    archetypeId: "witch:mountain-witch",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:mountain-witch:major-hexes:0": {
    archetypeId: "witch:mountain-witch",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:mountain-witch:mountain-beast-empathy:2": {
    archetypeId: "witch:mountain-witch",
    name: "Mountain Beast Empathy",
    level: 2,
    bucket: "subsystem",
    note: "wild empathy reflavor (mountain animals only) — wild empathy itself isn't modeled anywhere in this engine, not even for its native classes, so there's no formula to reuse",
  },
  "witch:mountain-witch:spells:0": {
    archetypeId: "witch:mountain-witch",
    name: "Spells",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:mountain-witch:stone-spirit-hex:0": {
    archetypeId: "witch:mountain-witch",
    name: "Stone Spirit Hex",
    level: 0,
    bucket: "subsystem",
    note: "grants access to the shaman stone spirit's hex list — an option-list grant, no numeric effect",
  },
  "witch:nexian-spellspy:grand-hex:0": {
    archetypeId: "witch:nexian-spellspy",
    name: "Grand Hex",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:nexian-spellspy:hexes:0": {
    archetypeId: "witch:nexian-spellspy",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:nexian-spellspy:infiltrating-vessel:0": {
    archetypeId: "witch:nexian-spellspy",
    name: "Infiltrating Vessel",
    level: 0,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:nexian-spellspy:major-hexes:0": {
    archetypeId: "witch:nexian-spellspy",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:nexian-spellspy:nondetection:0": {
    archetypeId: "witch:nexian-spellspy",
    name: "Nondetection",
    level: 0,
    bucket: "subsystem",
    note: "reclassifies a spell's effective spell level for her own spell list — a spellcasting-mechanics change, no Change-shaped number",
  },
  "witch:nexian-spellspy:prepare-results:4": {
    archetypeId: "witch:nexian-spellspy",
    name: "Prepare Results",
    level: 4,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:pact-witch:planar-familiar:0": {
    archetypeId: "witch:pact-witch",
    name: "Planar Familiar",
    level: 6,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself",
  },
  "witch:pact-witch:planar-pact:0": {
    archetypeId: "witch:pact-witch",
    name: "Planar Pact",
    level: 6,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:putrefactor:disgorge-familiar:0": {
    archetypeId: "witch:putrefactor",
    name: "Disgorge Familiar",
    level: 1,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:putrefactor:disgorge-swarm:6": {
    archetypeId: "witch:putrefactor",
    name: "Disgorge Swarm",
    level: 6,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:putrefactor:infestation-of-entropy:0": {
    archetypeId: "witch:putrefactor",
    name: "Infestation of Entropy",
    level: 0,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself",
  },
  "witch:putrefactor:putrefied-innards:4": {
    archetypeId: "witch:putrefactor",
    name: "Putrefied Innards",
    level: 4,
    bucket: "subsystem",
    note: "a 25/50/75% fortification-style chance to negate extra crit/sneak-attack damage — no fortification target exists in this engine's defenses model",
  },
  "witch:putrefactor:verminous-blood:2": {
    archetypeId: "witch:putrefactor",
    name: "Verminous Blood",
    level: 2,
    bucket: "situational",
    note: "1d6 (scaling) reactive damage to an attacker, but only when she takes slashing/piercing damage from a melee attack — real but conditional/narrowly-scoped number (specific maneuver, target state, location, or relationship condition) — not expressible without over-applying, per the honesty bar",
  },
  "witch:rhetorican:debater:0": {
    archetypeId: "witch:rhetorican",
    name: "Debater",
    level: 1,
    bucket: "subsystem",
    note: "an opposed-Diplomacy-check counterplay mechanic, not a flat number",
  },
  "witch:rhetorican:eldritch-glibness:2": {
    archetypeId: "witch:rhetorican",
    name: "Eldritch Glibness",
    level: 2,
    bucket: "subsystem",
    note: "adds fixed spells to her known list at set levels — a spell-list grant, no independent number",
  },
  "witch:rhetorican:public-speaker:0": {
    archetypeId: "witch:rhetorican",
    name: "Public Speaker",
    level: 0,
    bucket: "subsystem",
    note: "reduces the DC to hear her speak in difficult conditions — no engine target models a 'be heard' DC",
  },
  "witch:scarred-witch-doctor:fetish-mask:1": {
    archetypeId: "witch:scarred-witch-doctor",
    name: "Fetish Mask",
    level: 1,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself (the ancillary +2 Heal/Intimidate/pain-save bonuses are additionally gated on 'wearing the mask,' a state this engine has no field for tracking)",
  },
  "witch:scarred-witch-doctor:fierce-intelligence:0": {
    archetypeId: "witch:scarred-witch-doctor",
    name: "Fierce Intelligence",
    level: 1,
    bucket: "situational",
    note: "treats Intelligence as 2 points higher, but ONLY for spellcasting-derived values (spells/day, spell DCs, spells known, hex effects) — a flat Change to the 'int' target would leak into unrelated Int-based skill checks the published text doesn't touch, over-applying per the honesty bar",
  },
  "witch:scarred-witch-doctor:grand-hexes:0": {
    archetypeId: "witch:scarred-witch-doctor",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:scarred-witch-doctor:hex-scar:0": {
    archetypeId: "witch:scarred-witch-doctor",
    name: "Hex Scar",
    level: 0,
    bucket: "subsystem",
    note: "narrative/utility text, no numeric or Change-shaped effect",
  },
  "witch:scarred-witch-doctor:hexes:0": {
    archetypeId: "witch:scarred-witch-doctor",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:scarred-witch-doctor:major-hexes:0": {
    archetypeId: "witch:scarred-witch-doctor",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:scarred-witch-doctor:scarshield:1": {
    archetypeId: "witch:scarred-witch-doctor",
    name: "Scarshield",
    level: 1,
    bucket: "situational",
    note: "an enhancement bonus to natural armor equal to half class level (min +1), but usable only for a limited minutes/day pool — activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:sea-witch:grand-hexes:0": {
    archetypeId: "witch:sea-witch",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:sea-witch:hexes:0": {
    archetypeId: "witch:sea-witch",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:sea-witch:know-direction:0": {
    archetypeId: "witch:sea-witch",
    name: "Know Direction",
    level: 0,
    bucket: "subsystem",
    note: "a location-gated (near a large body of water) at-will spell-like ability — no baseline number",
  },
  "witch:sea-witch:major-hexes:0": {
    archetypeId: "witch:sea-witch",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:sea-witch:patron:0": {
    archetypeId: "witch:sea-witch",
    name: "Patron",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:sea-witch:sea-creature-empathy:0": {
    archetypeId: "witch:sea-witch",
    name: "Sea Creature Empathy",
    level: 0,
    bucket: "subsystem",
    note: "wild empathy reflavor (water/coastal animals only) — wild empathy itself isn't modeled anywhere in this engine, not even for its native classes, so there's no formula to reuse",
  },
  "witch:sea-witch:spells:0": {
    archetypeId: "witch:sea-witch",
    name: "Spells",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:season-witch:grand-hexes:0": {
    archetypeId: "witch:season-witch",
    name: "Grand Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:season-witch:hexes:0": {
    archetypeId: "witch:season-witch",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:season-witch:major-hexes:0": {
    archetypeId: "witch:season-witch",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:season-witch:season-of-the-witch:0": {
    archetypeId: "witch:season-witch",
    name: "Season of the Witch",
    level: 1,
    bucket: "situational",
    note: "+1 spell save DC, but only for spells dealing one specific energy type tied to the chosen season — a descriptor-scoped DC bump the engine's flat spell-DC number can't filter by damage type, real but conditional/narrowly-scoped number (specific maneuver, target state, location, or relationship condition) — not expressible without over-applying, per the honesty bar",
  },
  "witch:seducer:fey-charm:0": {
    archetypeId: "witch:seducer",
    name: "Fey Charm",
    level: 1,
    bucket: "situational",
    note: "+1/+2/+3 DC to the charm hex, scaled by the target's romantic/sexual history with the seducer — an inherently roleplay-judged condition, real but conditional/narrowly-scoped number (specific maneuver, target state, location, or relationship condition) — not expressible without over-applying, per the honesty bar",
  },
  "witch:seducer:garden-of-delight:8": {
    archetypeId: "witch:seducer",
    name: "Garden of Delight",
    level: 8,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:seducer:otherworldly-allure:0": {
    archetypeId: "witch:seducer",
    name: "Otherworldly Allure",
    level: 0,
    bucket: "blocked",
    note: "blocked: substitutes Charisma for Intelligence across EVERY witch class feature (bonus spells, max spell level, spells known, all spell/hex save DCs) — this engine's ability-substitution registry (ability-substitution.ts) only covers a fixed set of derived slots (AC, initiative, attack/damage, CMB/CMD, Reflex saves); it has no 'spellcasting ability' slot, and the witch's spell DC/bonus-spell/spells-known formulas hardcode Intelligence rather than reading through a swappable slot. Composing this correctly needs a new substitution slot (engine work), not a table entry.",
  },
  "witch:seducer:patron:0": {
    archetypeId: "witch:seducer",
    name: "Patron",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:seducer:seducer-s-kiss:6": {
    archetypeId: "witch:seducer",
    name: "Seducer’s Kiss",
    level: 6,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:synergist:symbiosis:1": {
    archetypeId: "witch:synergist",
    name: "Symbiosis",
    level: 1,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:tatterdermalion:cantrips:0": {
    archetypeId: "witch:tatterdermalion",
    name: "Cantrips",
    level: 1,
    bucket: "subsystem",
    note: "restricts which cantrips she must prepare — no numeric effect",
  },
  "witch:tatterdermalion:dancing-strings:0": {
    archetypeId: "witch:tatterdermalion",
    name: "Dancing Strings",
    level: 1,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:tatterdermalion:lace-weaver:8": {
    archetypeId: "witch:tatterdermalion",
    name: "Lace Weaver",
    level: 8,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:tatterdermalion:sinister-stitching:12": {
    archetypeId: "witch:tatterdermalion",
    name: "Sinister Stitching",
    level: 12,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:tatterdermalion:unravel:16": {
    archetypeId: "witch:tatterdermalion",
    name: "Unravel",
    level: 16,
    bucket: "subsystem",
    note: "activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:tatterdermalion:weapon-proficiency:0": {
    archetypeId: "witch:tatterdermalion",
    name: "Weapon Proficiency",
    level: 0,
    bucket: "subsystem",
    note: "a proficiency change, no Change-shaped target",
  },
  "witch:tatterdermalion:witchweaver:0": {
    archetypeId: "witch:tatterdermalion",
    name: "Witchweaver",
    level: 4,
    bucket: "subsystem",
    note: "a duplicate wrapper bundling Moth-Eaten/Lace Weaver/Sinister Stitching/Unravel (each also its own separately-leveled feature entry above) — activated, resource-gated ability (swift/standard action, uses/day, or minutes/day) — same posture as ki/grit/panache/Archaeologist's Luck; no baseline always-on number to apply",
  },
  "witch:vellemancer:expanded-wishgranter:8": {
    archetypeId: "witch:vellemancer",
    name: "Expanded Wishgranter",
    level: 8,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:vellemancer:invested-hex:2": {
    archetypeId: "witch:vellemancer",
    name: "Invested Hex",
    level: 2,
    bucket: "subsystem",
    note: "lets her implant a hex into an ally to trigger later — a delivery-mechanism reflavor of existing hexes, no independent number",
  },
  "witch:vellemancer:keen-counselor:0": {
    archetypeId: "witch:vellemancer",
    name: "Keen Counselor",
    level: 0,
    bucket: "subsystem",
    note: "class-skill list swap, no Change-shaped target",
  },
  "witch:vellemancer:wishgranter:0": {
    archetypeId: "witch:vellemancer",
    name: "Wishgranter",
    level: 6,
    bucket: "situational",
    note: "real +1 caster-level bonus when using a granted wish as a spell's verbal component, but 'cl' isn't a target compute() consumes (targets.ts's UNAPPLIED_TARGET_LABELS) and the bonus is additionally conditional on a creature having made a usable wish — same shape as the hand-verified table's own note on the sorcerer analogue of this ability",
  },
  "witch:veneficus-witch:grand-hex:0": {
    archetypeId: "witch:veneficus-witch",
    name: "Grand Hex",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:veneficus-witch:hexes:0": {
    archetypeId: "witch:veneficus-witch",
    name: "Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:veneficus-witch:major-hexes:0": {
    archetypeId: "witch:veneficus-witch",
    name: "Major Hexes",
    level: 0,
    bucket: "subsystem",
    note: "lists hexes/major hexes/grand hexes exclusive to the archetype — an option-list grant, not a numeric effect",
  },
  "witch:veneficus-witch:poison-use:2": {
    archetypeId: "witch:veneficus-witch",
    name: "Poison Use",
    level: 2,
    bucket: "subsystem",
    note: "narrative/utility text, no numeric or Change-shaped effect",
  },
  "witch:veneficus-witch:poisoner:0": {
    archetypeId: "witch:veneficus-witch",
    name: "Poisoner",
    level: 0,
    bucket: "subsystem",
    note: "grants access to alchemist discoveries as hexes — an option-list grant, no numeric effect",
  },
  "witch:veneficus-witch:toxic-words:2": {
    archetypeId: "witch:veneficus-witch",
    name: "Toxic Words",
    level: 2,
    bucket: "subsystem",
    note: "a poison/hex DC-reduction tradeoff mechanic tied to imbuing a hex with poison — not a baseline number",
  },
  "witch:venom-siphoner:poisonous-familiar:0": {
    archetypeId: "witch:venom-siphoner",
    name: "Poisonous Familiar",
    level: 0,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:venom-siphoner:toxic-blood:6": {
    archetypeId: "witch:venom-siphoner",
    name: "Toxic Blood",
    level: 6,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:venom-siphoner:venom-expert:2": {
    archetypeId: "witch:venom-siphoner",
    name: "Venom Expert",
    level: 2,
    bucket: "subsystem",
    note: "narrative/utility text, no numeric or Change-shaped effect",
  },
  "witch:white-haired-witch:rogue-talents:10": {
    archetypeId: "witch:white-haired-witch",
    name: "Rogue Talents",
    level: 10,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:white-haired-witch:white-hair:1": {
    archetypeId: "witch:white-haired-witch",
    name: "White Hair",
    level: 1,
    bucket: "subsystem",
    note: "grants a natural weapon attack — no Change target for adding a new attack option (same posture as every other archetype's granted natural attack)",
  },
  "witch:winter-witch:frostfoot:1": {
    archetypeId: "witch:winter-witch",
    name: "Frostfoot",
    level: 1,
    bucket: "subsystem",
    note: "grants an unrelated ability/subsystem, no exploitable number",
  },
  "witch:winter-witch:frozen-caress:1": {
    archetypeId: "witch:winter-witch",
    name: "Frozen Caress",
    level: 1,
    bucket: "situational",
    note: "adds 1d4 cold damage to a touch spell, but only when she chooses to infuse it as a swift action on that specific casting — real but conditional/narrowly-scoped number (specific maneuver, target state, location, or relationship condition) — not expressible without over-applying, per the honesty bar",
  },
  "witch:witch-watcher:covenant-ally:0": {
    archetypeId: "witch:witch-watcher",
    name: "Covenant Ally",
    level: 0,
    bucket: "subsystem",
    note: "grants its benefit to a creature other than the witch herself (an ally, or a battlefield-wide aura affecting allies/undead) — no engine mechanism for a sheet's Change to buff a third party (every listed benefit targets her covenant ally, not herself)",
  },
  "witch:witch-watcher:diminished-spellcasting:0": {
    archetypeId: "witch:witch-watcher",
    name: "Diminished Spellcasting",
    level: 0,
    bucket: "subsystem",
    note: "reduces her OWN spells-known count by one per level — no engine target exists for adjusting spells-known/spells-per-day",
  },
  "witch:wyrm-witch:draconic-patronage:0": {
    archetypeId: "witch:wyrm-witch",
    name: "Draconic Patronage",
    level: 0,
    bucket: "subsystem",
    note: "patron restriction or patron-spell-list swap — narrative choice-gating, no numeric effect",
  },
  "witch:wyrm-witch:wyrmwitch-s-hoard:0": {
    archetypeId: "witch:wyrm-witch",
    name: "Wyrmwitch's Hoard",
    level: 0,
    bucket: "subsystem",
    note: "replaces or alters the familiar with a differently-flavored spell-storing vessel — no independent numeric effect beyond the swap itself (a treasure hoard instead of a living creature)",
  },
};
