// Ties the test-runtime's provided bindings to this Worker's `Env`
// (generated by `wrangler types` into `../worker-configuration.d.ts`), per
// the vitest-pool-workers setup convention.
declare module "cloudflare:test" {
  interface ProvidedEnv extends Env {}
}
